In [ ]:
# 1. Install standard modern Selenium (4.x includes built-in driver/browser management)
!pip install selenium

Collecting selenium
  Downloading selenium-4.51.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: certifi>=2026.2.25 in /usr/local/lib/python3.13/dist-packages (from selenium) (2026.7.22)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.34.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.13/dist-packages (from selenium) (4.16.0)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading urllib3-2.8.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.13/dist-packages (from selenium) (1.9.2)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.13/dist-packages (from trio<1.0,>=0.31.0->selenium) (26.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.13/dist-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from trio<1.0,>=0.31.0->selenium) (3.20)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.13/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.13/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.51.0-py3-none-any.whl (11.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 84.6 MB/s eta 0:00:00
Downloading trio-0.34.0-py3-none-any.whl (511 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.8/511.8 kB 31.9 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.8.0-py3-none-any.whl (135 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.7/135.7 kB 10.4 MB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, urllib3, outcome, trio, trio-websocket, selenium
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
Successfully installed outcome-1.3.0.post0 selenium-4.51.0 trio-0.34.0 trio-websocket-0.12.2 urllib3-2.8.0 wsproto-1.3.2

In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
import pandas as pd
import time
import random
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from google.colab import drive
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
with open("/content/drive/MyDrive/my.flutter.2025/Instant_ai_training/SPRINT_01/DATA.csv","r") as f:
  df=pd.read_csv(f)
cities = df['City.Name'].unique().tolist()

In [ ]:
df["room_type"].value_counts()

room_type
Entire home/apt    32648
Private room       18693
Shared room          366
Name: count, dtype: int64

In [ ]:
df['bedrooms'].value_counts().sort_values(ascending=False)

bedrooms
1     36333
2      9290
0      4485
3      1477
4        96
5        10
9        10
6         2
10        2
8         2
Name: count, dtype: int64

In [ ]:
# filter number of bedrooms by room_type = Entire home/apt and count them
df[df['room_type'] == 'Entire home/apt']['bedrooms'].value_counts()

bedrooms
1    18489
2     8650
0     4026
3     1410
4       67
5        4
6        2
Name: count, dtype: int64

In [ ]:
df_copy = df[(df['room_type'] == 'Entire home/apt') & (df['bedrooms'] == 2)].copy()
df_copy

,ID,City.Name,Day.type,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,...,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat
36356,591,athens,weekdays,81.081714,Entire home/apt,False,False,2,False,0,...,40,2,0.645994,0.614437,373.834226,14.095104,421.777164,31.669596,23.73117,37.97080
36357,1297,athens,weekdays,185.128770,Entire home/apt,False,False,4,False,0,...,40,2,2.546158,0.655264,67.022833,2.527039,99.349435,7.459760,23.73358,37.99845
36358,1409,athens,weekdays,92.798725,Entire home/apt,False,False,4,False,1,...,20,2,2.937913,0.758379,57.872178,2.182022,85.494093,6.419417,23.73372,38.00199
36359,1438,athens,weekdays,92.798725,Entire home/apt,False,False,3,False,0,...,80,2,1.161515,1.064091,126.861854,4.783219,182.200284,13.680706,23.74338,37.96723
36360,1681,athens,weekdays,125.137675,Entire home/apt,False,False,5,False,0,...,40,2,2.272546,0.106206,68.690918,2.589933,105.230591,7.901353,23.75636,37.98754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45462,517,paris,weekends,195.498183,Entire home/apt,False,False,2,False,0,...,100,2,3.432411,0.116077,446.342721,21.703447,867.041037,39.998625,2.31479,48.87463
45463,2637,paris,weekends,516.823562,Entire home/apt,False,False,2,False,1,...,100,2,5.704736,0.178499,224.442989,10.913557,439.936551,20.295299,2.28073,48.83722
45464,3045,paris,weekends,207.381862,Entire home/apt,False,False,2,False,0,...,100,2,3.644568,0.193911,299.068461,14.542226,641.114138,29.576090,2.35224,48.88935
45465,1696,vienna,weekdays,278.147862,Entire home/apt,False,False,2,False,0,...,100,2,1.826678,0.444272,116.232687,8.324088,170.394517,4.073404,16.39706,48.20349
45466,1749,vienna,weekends,278.147862,Entire home/apt,False,False,2,False,0,...,100,2,1.826629,0.444225,116.235199,8.323998,170.399505,4.118490,16.39706,48.20349

In [ ]:
cities

['Amsterdam',
 'Athens',
 'Barcelona',
 'Berlin',
 'Budapest',
 'Lisbon',
 'London',
 'Paris',
 'Rome',
 'Vienna']

In [ ]:
# 1. Install standard modern Selenium (4.x includes built-in driver/browser management)
!pip install selenium

import time
import random
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options

# --- ROBUST RATING/FAV EXTRACTOR ---
def get_details_and_fav(driver, wait):
    rating, reviews, is_fav = "N/A", "0", 0

    try:
        # Locate the review anchor (link or button)
        try:
            review_link = wait.until(EC.presence_of_element_located(
                (By.XPATH, "//a[contains(@href, 'reviews')] | //button[contains(., 'reviews')]")
            ))
        except:
            # Fallback for "New" listings
            try:
                h1_parent = driver.find_element(By.TAG_NAME, "h1").find_element(By.XPATH, "./..").text
                if "New" in h1_parent: return "New", "0", 0
            except: pass
            return rating, reviews, is_fav

        # Get text content (cleanly)
        link_text = review_link.get_attribute("textContent").strip()
        clean_link = " ".join(link_text.split())

        # Get parent text (for standard listings where rating is outside link)
        parent_text = review_link.find_element(By.XPATH, "./..").get_attribute("textContent").strip()
        clean_parent = " ".join(parent_text.split())

        # --- SCENARIO A: GUEST FAVORITE ---
        if "Guest favorite" in clean_link or "Guest favorite" in clean_parent:
            is_fav = 1
            # Rating logic for fav
            r_match = re.search(r"(\d\.\d{1,2})", clean_parent)
            if r_match: rating = r_match.group(1)
            # Review logic for fav
            rev_match = re.search(r"(\d+)\s*Review", clean_parent, re.IGNORECASE)
            if rev_match: reviews = rev_match.group(1)

        # --- SCENARIO B: STANDARD ---
        else:
            is_fav = 0
            if "New" in clean_parent:
                rating = "New"
            else:
                r_match = re.search(r"(\d\.\d{1,2})", clean_parent)
                if r_match: rating = r_match.group(1)

            # Try link first, then parent for reviews
            rev_match = re.search(r"(\d+)\s*review", clean_link, re.IGNORECASE)
            if not rev_match:
                rev_match = re.search(r"(\d+)\s*review", clean_parent, re.IGNORECASE)
            if rev_match: reviews = rev_match.group(1)

    except: pass
    return rating, reviews, is_fav

all_data1 = []
city_count = 0

for city in cities:
    city_count += 1

    # --- MAIN SETUP ---
    URL = f"https://www.airbnb.com/s/{city}/homes?refinement_paths%5B%5D=%2Fhomes&date_picker_type=calendar&search_type=filter_change&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2026-02-01&monthly_length=3&monthly_end_date=2026-05-01&price_filter_input_type=2&channel=EXPLORE&price_filter_num_nights=5&min_bedrooms=2&selected_filter_order%5B%5D=min_bedrooms%3A2&selected_filter_order%5B%5D=room_types%3AEntire%20home%2Fapt&update_selected_filters=true&query={city}&search_mode=regular_search&room_types%5B%5D=Entire%20home%2Fapt"

    chrome_options = Options()
    chrome_options.add_argument("--window-size=1920,1080")
    chrome_options.add_argument("--headless")
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument("--start-maximized")

    # In Selenium 4, leaving webdriver.Chrome() without a path automatically invokes
    # Selenium Manager to download and use the correct standalone Chrome binary.
    driver = webdriver.Chrome(options=chrome_options)

    target_count = 50  # Target number of items to scrape per city
    # Initialize a local counter
    items_scraped_this_city = 0
    try:
        driver.get(URL)
        wait = WebDriverWait(driver, 8)

        while items_scraped_this_city < target_count:
            print(f"\n=== SCRAPING CITY {city_count}/{len(cities)}: {city} ===\n")
            print(f"--- Scraping Page (Collected: {len(all_data1)}) ---")

            try:
                wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "div[data-testid='card-container']")))
            except: break

            listings = driver.find_elements(By.CSS_SELECTOR, "div[data-testid='card-container']")
            listing_urls = []
            for l in listings:
                try:
                    url = l.find_element(By.TAG_NAME, "a").get_attribute("href")
                    listing_urls.append(url)
                except: continue

            main_window = driver.current_window_handle

            for url in listing_urls:
                if items_scraped_this_city >= target_count: break

                try:
                    driver.execute_script(f"window.open('{url}', '_blank');")
                    driver.switch_to.window(driver.window_handles[-1])
                    wait.until(EC.presence_of_element_located((By.TAG_NAME, "h1")))

                    # A. Name
                    try: name = driver.find_element(By.TAG_NAME, "h1").text
                    except: name = "No Title"

                    # B. Superhost
                    is_superhost = "No"
                    try:
                        driver.execute_script("window.scrollBy(0, 500);")
                        time.sleep(0.5)
                        body_text = driver.find_element(By.TAG_NAME, "body").text
                        if "Superhost" in body_text: is_superhost = "Yes"
                    except: pass
                    # C. Price (Robust Fallback Strategy)
                    price = "N/A"
                    price_selectors = [
                        # 1. Target by the container test ID inside the sidebar (Most stable)
                        "//div[@data-testid='book-it-default-sidebar']//span[contains(text(), '$')]",
                        # 2. Target specific text content containing the price per night structure
                        "//span[contains(text(), 'per night')]/preceding-sibling::span",
                        # 3. Fallback to any element containing the primary price display structure
                        "//div[@data-plugin-in-point-id='BOOK_IT_SIDEBAR']//span[contains(text(), '$')]"
                    ]

                    for selector in price_selectors:
                        try:
                            # Wait up to 3 seconds for the specific price element to appear
                            el = WebDriverWait(driver, 3).until(
                                EC.presence_of_element_located((By.XPATH, selector))
                            )
                            price_text = el.text.strip()
                            if price_text:
                                price = price_text
                                break # Exit the loop if we found a valid price string
                        except:
                            continue

                    # 4. Ultimate safety net: If still N/A, extract it from the page title
                    # (Airbnb listing titles usually display as "$123 night · Listing Name...")
                    if price == "N/A":
                        try:
                            title_text = driver.title
                            price_match = re.search(r"(\$\d[\d,.]*)", title_text)
                            if price_match:
                                price = price_match.group(1)
                        except:
                            pass


                    # D. Rating/Fav (Robust)
                    rating, reviews, is_fav = get_details_and_fav(driver, wait)

                    all_data1.append({
                        "Name": name, "city": city, "Price": price, "Superhost": is_superhost,
                        "is_fav": is_fav, "Rating": rating, "Reviews": reviews, "URL": url
                    })

                    print(f"[{len(all_data1)}] {price} |{city}| ★{rating} ({reviews}) | Fav: {is_fav} | SH: {is_superhost}|")
                    time.sleep(random.uniform(1.0, 2.0))

                    driver.close()
                    driver.switch_to.window(main_window)

                    # Increment the counter for successfully scraped items
                    items_scraped_this_city += 1

                except Exception:
                    if len(driver.window_handles) > 1:
                        driver.close()
                        driver.switch_to.window(main_window)
                    continue

            if items_scraped_this_city < target_count:
                try:
                    next_btn = driver.find_element(By.CSS_SELECTOR, "a[aria-label='Next']")
                    driver.execute_script("arguments[0].click();", next_btn)
                    time.sleep(4)
                except: break

    finally:
        print(f"\nCompleted! Total scraped: {len(all_data1)}")
        driver.quit()

Requirement already satisfied: selenium in /usr/local/lib/python3.13/dist-packages (4.51.0)
Requirement already satisfied: certifi>=2026.2.25 in /usr/local/lib/python3.13/dist-packages (from selenium) (2026.7.22)
Requirement already satisfied: trio<1.0,>=0.31.0 in /usr/local/lib/python3.13/dist-packages (from selenium) (0.34.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in /usr/local/lib/python3.13/dist-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.13/dist-packages (from selenium) (4.16.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in /usr/local/lib/python3.13/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.8.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.13/dist-packages (from selenium) (1.9.2)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.13/dist-packages (from trio<1.0,>=0.31.0->selenium) (26.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.13/dist-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from trio<1.0,>=0.31.0->selenium) (3.20)
Requirement already satisfied: outcome in /usr/local/lib/python3.13/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.13/dist-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.13/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.13/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)

=== SCRAPING CITY 1/10: Amsterdam ===

--- Scraping Page (Collected: 0) ---
[1] $1,202 |Amsterdam| ★4.97 (97322) | Fav: 1 | SH: Yes|

=== SCRAPING CITY 1/10: Amsterdam ===

--- Scraping Page (Collected: 1) ---
[2] $1,350 |Amsterdam| ★4.74 (347) | Fav: 0 | SH: No|
[3] $2,065 |Amsterdam| ★4.86 (86242) | Fav: 1 | SH: Yes|
[4] $3,031 |Amsterdam| ★4.95 (95194) | Fav: 1 | SH: Yes|
[5] $1,877 |Amsterdam| ★4.67 (201) | Fav: 0 | SH: No|
[6] $2,207 |Amsterdam| ★4.91 (91626) | Fav: 1 | SH: Yes|
[7] $2,746 |Amsterdam| ★4.99 (99194) | Fav: 1 | SH: Yes|
[8] $2,230 |Amsterdam| ★4.99 (99242) | Fav: 1 | SH: Yes|
[9] $2,169 |Amsterdam| ★5.0 (024) | Fav: 1 | SH: Yes|
[10] $1,983 |Amsterdam| ★4.79 (7994) | Fav: 1 | SH: Yes|
[11] $1,706 |Amsterdam| ★4.86 (70) | Fav: 0 | SH: Yes|
[12] $1,079 |Amsterdam| ★4.98 (98403) | Fav: 1 | SH: Yes|
[13] $2,347 |Amsterdam| ★N/A (0) | Fav: 0 | SH: No|
[14] $1,600 |Amsterdam| ★4.56 (233) | Fav: 0 | SH: No|
[15] $2,105 |Amsterdam| ★4.95 (95327) | Fav: 1 | SH: Yes|
[16] $2,279 |Amsterdam| ★4.82 (348) | Fav: 0 | SH: Yes|
[17] $1,624 |Amsterdam| ★4.81 (81719) | Fav: 1 | SH: Yes|
[18] $2,193 |Amsterdam| ★4.95 (95148) | Fav: 1 | SH: Yes|
[19] $3,868 |Amsterdam| ★4.89 (89122) | Fav: 1 | SH: No|

=== SCRAPING CITY 1/10: Amsterdam ===

--- Scraping Page (Collected: 19) ---
[20] $3,868 |Amsterdam| ★4.89 (89122) | Fav: 1 | SH: No|
[21] $2,234 |Amsterdam| ★4.94 (94171) | Fav: 1 | SH: Yes|
[22] $1,140 |Amsterdam| ★4.74 (249) | Fav: 0 | SH: No|
[23] $2,133 |Amsterdam| ★5.0 (011) | Fav: 1 | SH: Yes|
[24] $1,683 |Amsterdam| ★4.94 (94175) | Fav: 1 | SH: Yes|
[25] $1,289 |Amsterdam| ★4.88 (88186) | Fav: 1 | SH: Yes|
[26] $1,819 |Amsterdam| ★4.75 (36) | Fav: 0 | SH: Yes|
[27] $3,421 |Amsterdam| ★4.96 (9684) | Fav: 1 | SH: Yes|
[28] $1,435 |Amsterdam| ★4.86 (86309) | Fav: 1 | SH: Yes|
[29] $2,492 |Amsterdam| ★4.91 (91151) | Fav: 1 | SH: Yes|
[30] $2,186 |Amsterdam| ★5.0 (067) | Fav: 1 | SH: No|
[31] $4,387 |Amsterdam| ★4.83 (103) | Fav: 0 | SH: Yes|
[32] $2,638 |Amsterdam| ★4.62 (101) | Fav: 0 | SH: No|
[33] $2,072 |Amsterdam| ★4.85 (223) | Fav: 0 | SH: Yes|
[34] $2,246 |Amsterdam| ★4.82 (82177) | Fav: 1 | SH: Yes|
[35] $1,834 |Amsterdam| ★4.92 (92452) | Fav: 1 | SH: Yes|
[36] $2,030 |Amsterdam| ★4.97 (97243) | Fav: 1 | SH: Yes|
[37] $1,791 |Amsterdam| ★4.85 (107) | Fav: 0 | SH: Yes|

=== SCRAPING CITY 1/10: Amsterdam ===

--- Scraping Page (Collected: 37) ---
[38] $1,125 |Amsterdam| ★4.95 (95372) | Fav: 1 | SH: No|
[39] $888 |Amsterdam| ★5.0 (017) | Fav: 1 | SH: Yes|
[40] $3,509 |Amsterdam| ★N/A (0) | Fav: 0 | SH: No|
[41] $1,408 |Amsterdam| ★4.35 (26) | Fav: 0 | SH: No|
[42] $2,782 |Amsterdam| ★5.0 (3) | Fav: 0 | SH: No|
[43] $1,681 |Amsterdam| ★4.29 (225) | Fav: 0 | SH: No|
[44] $3,198 |Amsterdam| ★4.99 (99160) | Fav: 1 | SH: Yes|
[45] $1,128 |Amsterdam| ★4.93 (93458) | Fav: 1 | SH: Yes|
[46] $2,605 |Amsterdam| ★N/A (0) | Fav: 0 | SH: No|
[47] $6,125 |Amsterdam| ★4.92 (13) | Fav: 0 | SH: No|
[48] $1,413 |Amsterdam| ★N/A (0) | Fav: 0 | SH: No|
[49] $2,563 |Amsterdam| ★4.83 (452) | Fav: 0 | SH: Yes|
[50] $2,526 |Amsterdam| ★5.0 (06) | Fav: 1 | SH: No|

Completed! Total scraped: 50

=== SCRAPING CITY 2/10: Athens ===

--- Scraping Page (Collected: 50) ---
[51] $906 |Athens| ★4.92 (92416) | Fav: 1 | SH: Yes|

=== SCRAPING CITY 2/10: Athens ===

--- Scraping Page (Collected: 51) ---
[52] $1,005 |Athens| ★4.98 (98232) | Fav: 1 | SH: No|
[53] $1,364 |Athens| ★4.92 (92370) | Fav: 1 | SH: Yes|
[54] $445 |Athens| ★5.0 (0267) | Fav: 1 | SH: Yes|
[55] $1,067 |Athens| ★4.99 (99189) | Fav: 1 | SH: Yes|
[56] $1,387 |Athens| ★5.0 (0379) | Fav: 1 | SH: Yes|
[57] $786 |Athens| ★4.95 (95393) | Fav: 1 | SH: Yes|
[58] $612 |Athens| ★4.87 (87112) | Fav: 1 | SH: Yes|
[59] $638 |Athens| ★4.99 (99348) | Fav: 1 | SH: Yes|
[60] $1,078 |Athens| ★4.93 (93157) | Fav: 1 | SH: Yes|
[61] $849 |Athens| ★4.84 (164) | Fav: 0 | SH: Yes|
[62] $1,265 |Athens| ★4.96 (96295) | Fav: 1 | SH: No|
[63] $1,128 |Athens| ★4.95 (257) | Fav: 0 | SH: Yes|
[64] $320 |Athens| ★4.93 (9314) | Fav: 1 | SH: No|
[65] $3,174 |Athens| ★4.97 (97106) | Fav: 1 | SH: Yes|
[66] $1,287 |Athens| ★4.94 (94505) | Fav: 1 | SH: Yes|
[67] $809 |Athens| ★4.97 (9760) | Fav: 1 | SH: No|
[68] $1,105 |Athens| ★4.95 (95459) | Fav: 1 | SH: Yes|
[69] $1,114 |Athens| ★4.95 (9578) | Fav: 1 | SH: Yes|

=== SCRAPING CITY 2/10: Athens ===

--- Scraping Page (Collected: 69) ---
[70] $701 |Athens| ★4.96 (96198) | Fav: 1 | SH: Yes|
[71] $1,247 |Athens| ★4.84 (84207) | Fav: 1 | SH: Yes|
[72] $528 |Athens| ★4.94 (9499) | Fav: 1 | SH: Yes|
[73] $948 |Athens| ★4.93 (9355) | Fav: 1 | SH: Yes|
[74] $754 |Athens| ★4.95 (95111) | Fav: 1 | SH: No|
[75] $523 |Athens| ★4.94 (94451) | Fav: 1 | SH: No|
[76] $595 |Athens| ★4.95 (95559) | Fav: 1 | SH: Yes|
[77] $1,071 |Athens| ★4.98 (98379) | Fav: 1 | SH: Yes|
[78] $783 |Athens| ★4.94 (94165) | Fav: 1 | SH: No|
[79] $1,129 |Athens| ★4.96 (96292) | Fav: 1 | SH: Yes|
[80] $467 |Athens| ★4.89 (89758) | Fav: 1 | SH: Yes|
[81] $3,031 |Athens| ★4.99 (9980) | Fav: 1 | SH: Yes|
[82] $2,286 |Athens| ★5.0 (041) | Fav: 1 | SH: Yes|
[83] $1,934 |Athens| ★4.98 (98350) | Fav: 1 | SH: Yes|
[84] $685 |Athens| ★4.94 (9465) | Fav: 1 | SH: No|
[85] $1,488 |Athens| ★4.91 (91312) | Fav: 1 | SH: Yes|
[86] $988 |Athens| ★4.87 (87318) | Fav: 1 | SH: Yes|
[87] $785 |Athens| ★4.99 (99212) | Fav: 1 | SH: Yes|

=== SCRAPING CITY 2/10: Athens ===

--- Scraping Page (Collected: 87) ---
[88] $2,970 |Athens| ★5.0 (016) | Fav: 1 | SH: Yes|
[89] $545 |Athens| ★4.91 (91326) | Fav: 1 | SH: No|
[90] $461 |Athens| ★4.81 (81188) | Fav: 1 | SH: Yes|
[91] $590 |Athens| ★5.0 (025) | Fav: 1 | SH: Yes|
[92] $1,346 |Athens| ★5.0 (030) | Fav: 1 | SH: Yes|
[93] $937 |Athens| ★5.0 (011) | Fav: 1 | SH: Yes|
[94] $470 |Athens| ★4.94 (94289) | Fav: 1 | SH: No|
[95] $982 |Athens| ★4.96 (96500) | Fav: 1 | SH: Yes|
[96] $360 |Athens| ★4.95 (9566) | Fav: 1 | SH: No|
[97] $1,303 |Athens| ★4.97 (9765) | Fav: 1 | SH: Yes|
[98] $3,394 |Athens| ★4.89 (89100) | Fav: 1 | SH: Yes|
[99] $855 |Athens| ★4.89 (89543) | Fav: 1 | SH: No|
[100] $1,073 |Athens| ★4.91 (217) | Fav: 0 | SH: Yes|

Completed! Total scraped: 100

=== SCRAPING CITY 3/10: Barcelona ===

--- Scraping Page (Collected: 100) ---
[101] $1,021 |Barcelona| ★4.84 (619) | Fav: 1 | SH: Yes|

=== SCRAPING CITY 3/10: Barcelona ===

--- Scraping Page (Collected: 101) ---
[102] $2,021 |Barcelona| ★4.87 (87418) | Fav: 1 | SH: Yes|
[103] $2,156 |Barcelona| ★4.87 (87380) | Fav: 1 | SH: Yes|
[104] $915 |Barcelona| ★4.9 (632) | Fav: 1 | SH: Yes|
[105] $2,251 |Barcelona| ★4.78 (78505) | Fav: 1 | SH: Yes|
[106] $1,903 |Barcelona| ★4.99 (99223) | Fav: 1 | SH: Yes|
[107] $943 |Barcelona| ★4.94 (94562) | Fav: 1 | SH: Yes|
[108] $1,936 |Barcelona| ★4.99 (99419) | Fav: 1 | SH: Yes|
[109] $1,459 |Barcelona| ★4.92 (92288) | Fav: 1 | SH: Yes|
[110] $1,247 |Barcelona| ★4.78 (78411) | Fav: 1 | SH: Yes|
[111] $1,410 |Barcelona| ★4.86 (86729) | Fav: 1 | SH: Yes|
[112] $2,878 |Barcelona| ★4.91 (91529) | Fav: 1 | SH: Yes|
[113] $1,511 |Barcelona| ★4.94 (94337) | Fav: 1 | SH: Yes|
[114] $1,801 |Barcelona| ★4.95 (95463) | Fav: 1 | SH: No|
[115] $1,102 |Barcelona| ★4.86 (86588) | Fav: 1 | SH: No|
[116] $1,297 |Barcelona| ★4.89 (89405) | Fav: 1 | SH: Yes|
[117] $2,551 |Barcelona| ★4.98 (98170) | Fav: 1 | SH: Yes|
[118] $3,064 |Barcelona| ★4.97 (97593) | Fav: 1 | SH: Yes|
[119] $1,197 |Barcelona| ★4.93 (93223) | Fav: 1 | SH: Yes|

=== SCRAPING CITY 3/10: Barcelona ===

--- Scraping Page (Collected: 119) ---
[120] $1,775 |Barcelona| ★4.96 (96116) | Fav: 1 | SH: Yes|
[121] $3,377 |Barcelona| ★4.98 (98214) | Fav: 1 | SH: Yes|
[122] $1,921 |Barcelona| ★4.96 (96182) | Fav: 1 | SH: Yes|
[123] $1,198 |Barcelona| ★5.0 (015) | Fav: 1 | SH: Yes|
[124] $1,050 |Barcelona| ★4.92 (92392) | Fav: 1 | SH: Yes|
[125] $1,996 |Barcelona| ★4.9 (9238) | Fav: 1 | SH: No|
[126] $1,620 |Barcelona| ★4.89 (89397) | Fav: 1 | SH: Yes|
[127] $1,696 |Barcelona| ★4.9 (9493) | Fav: 1 | SH: Yes|
[128] $1,472 |Barcelona| ★4.85 (85243) | Fav: 1 | SH: Yes|
[129] $1,101 |Barcelona| ★4.93 (93212) | Fav: 1 | SH: Yes|
[130] $1,431 |Barcelona| ★4.92 (92191) | Fav: 1 | SH: Yes|
[131] $1,376 |Barcelona| ★4.79 (344) | Fav: 0 | SH: No|
[132] $1,779 |Barcelona| ★4.99 (99218) | Fav: 1 | SH: Yes|
[133] $1,060 |Barcelona| ★4.75 (865) | Fav: 0 | SH: Yes|
[134] $1,262 |Barcelona| ★4.89 (8936) | Fav: 1 | SH: No|
[135] $674 |Barcelona| ★5.0 (05) | Fav: 1 | SH: Yes|
[136] $1,614 |Barcelona| ★4.97 (97302) | Fav: 1 | SH: Yes|
[137] $1,785 |Barcelona| ★4.96 (96253) | Fav: 1 | SH: Yes|

=== SCRAPING CITY 3/10: Barcelona ===

--- Scraping Page (Collected: 137) ---
[138] $1,965 |Barcelona| ★4.94 (94379) | Fav: 1 | SH: Yes|
[139] $1,224 |Barcelona| ★5.0 (042) | Fav: 1 | SH: Yes|
[140] $1,160 |Barcelona| ★4.96 (96164) | Fav: 1 | SH: Yes|
[141] $838 |Barcelona| ★4.85 (85611) | Fav: 1 | SH: No|
[142] $1,207 |Barcelona| ★4.93 (93518) | Fav: 1 | SH: Yes|
[143] $1,776 |Barcelona| ★4.92 (92296) | Fav: 1 | SH: Yes|
[144] $1,027 |Barcelona| ★4.86 (225) | Fav: 0 | SH: Yes|
[145] $718 |Barcelona| ★4.93 (42) | Fav: 0 | SH: No|
[146] $1,681 |Barcelona| ★4.84 (84608) | Fav: 1 | SH: No|
[147] $1,877 |Barcelona| ★4.98 (98217) | Fav: 1 | SH: No|
[148] $1,342 |Barcelona| ★4.78 (113) | Fav: 0 | SH: No|
[149] $1,061 |Barcelona| ★4.87 (87741) | Fav: 1 | SH: Yes|
[150] $1,476 |Barcelona| ★4.96 (96165) | Fav: 1 | SH: Yes|

Completed! Total scraped: 150

=== SCRAPING CITY 4/10: Berlin ===

--- Scraping Page (Collected: 150) ---
[151] $1,140 |Berlin| ★4.84 (125) | Fav: 0 | SH: Yes|

=== SCRAPING CITY 4/10: Berlin ===

--- Scraping Page (Collected: 151) ---
[152] $2,234 |Berlin| ★4.84 (84144) | Fav: 1 | SH: Yes|
[153] $1,655 |Berlin| ★4.44 (184) | Fav: 0 | SH: No|
[154] $1,144 |Berlin| ★4.75 (113) | Fav: 0 | SH: Yes|
[155] $1,132 |Berlin| ★4.91 (91375) | Fav: 1 | SH: Yes|
[156] $1,526 |Berlin| ★4.97 (97399) | Fav: 1 | SH: No|
[157] $1,131 |Berlin| ★4.85 (85265) | Fav: 1 | SH: No|
[158] $1,836 |Berlin| ★5.0 (095) | Fav: 1 | SH: Yes|
[159] $2,616 |Berlin| ★4.96 (96672) | Fav: 1 | SH: Yes|
[160] $1,404 |Berlin| ★4.98 (98258) | Fav: 1 | SH: Yes|
[161] $1,814 |Berlin| ★4.89 (89134) | Fav: 1 | SH: Yes|
[162] $1,112 |Berlin| ★5.0 (017) | Fav: 1 | SH: Yes|
[163] $1,275 |Berlin| ★5.0 (016) | Fav: 1 | SH: Yes|
[164] $2,358 |Berlin| ★4.89 (89332) | Fav: 1 | SH: No|
[165] $1,272 |Berlin| ★4.97 (9738) | Fav: 1 | SH: Yes|
[166] $1,404 |Berlin| ★4.94 (94114) | Fav: 1 | SH: Yes|
[167] $2,220 |Berlin| ★4.79 (343) | Fav: 0 | SH: Yes|
[168] $5,546 |Berlin| ★5.0 (12) | Fav: 0 | SH: Yes|
[169] $2,139 |Berlin| ★5.0 (029) | Fav: 1 | SH: Yes|

=== SCRAPING CITY 4/10: Berlin ===

--- Scraping Page (Collected: 169) ---
[170] $1,303 |Berlin| ★4.95 (95332) | Fav: 1 | SH: Yes|
[171] $1,087 |Berlin| ★4.83 (413) | Fav: 0 | SH: Yes|
[172] $1,409 |Berlin| ★4.89 (89449) | Fav: 1 | SH: Yes|
[173] $1,353 |Berlin| ★4.8 (8483) | Fav: 1 | SH: Yes|
[174] $2,820 |Berlin| ★4.9 (9107) | Fav: 1 | SH: Yes|
[175] $1,162 |Berlin| ★4.9 (9470) | Fav: 1 | SH: Yes|
[176] $1,387 |Berlin| ★4.9 (9482) | Fav: 1 | SH: No|
[177] $1,837 |Berlin| ★4.95 (95243) | Fav: 1 | SH: Yes|
[178] $2,556 |Berlin| ★4.95 (95105) | Fav: 1 | SH: Yes|
[179] $2,302 |Berlin| ★4.88 (57) | Fav: 0 | SH: Yes|
[180] $1,514 |Berlin| ★4.78 (289) | Fav: 0 | SH: No|
[181] $1,170 |Berlin| ★4.88 (88470) | Fav: 1 | SH: Yes|
[182] $969 |Berlin| ★N/A (0) | Fav: 0 | SH: Yes|
[183] $2,355 |Berlin| ★4.89 (8962) | Fav: 1 | SH: Yes|
[184] $969 |Berlin| ★4.9 (931) | Fav: 1 | SH: Yes|
[185] $1,467 |Berlin| ★4.85 (85231) | Fav: 1 | SH: No|
[186] $1,069 |Berlin| ★4.98 (9853) | Fav: 1 | SH: Yes|
[187] $1,492 |Berlin| ★5.0 (043) | Fav: 1 | SH: Yes|

=== SCRAPING CITY 4/10: Berlin ===

--- Scraping Page (Collected: 187) ---
[188] $1,116 |Berlin| ★4.84 (95) | Fav: 0 | SH: Yes|
[189] $1,251 |Berlin| ★4.97 (9773) | Fav: 1 | SH: Yes|
[190] $1,080 |Berlin| ★4.85 (143) | Fav: 0 | SH: Yes|
[191] $1,553 |Berlin| ★5.0 (3) | Fav: 0 | SH: No|
[192] $1,314 |Berlin| ★4.98 (98144) | Fav: 1 | SH: Yes|
[193] $1,636 |Berlin| ★4.92 (219) | Fav: 0 | SH: No|
[194] $879 |Berlin| ★4.8 (8380) | Fav: 1 | SH: Yes|
[195] $1,666 |Berlin| ★5.0 (015) | Fav: 1 | SH: Yes|
[196] $2,004 |Berlin| ★4.88 (88465) | Fav: 1 | SH: Yes|
[197] $1,460 |Berlin| ★4.69 (129) | Fav: 0 | SH: Yes|
[198] $1,368 |Berlin| ★4.96 (96367) | Fav: 1 | SH: Yes|
[199] $940 |Berlin| ★4.87 (87330) | Fav: 1 | SH: Yes|
[200] $847 |Berlin| ★4.87 (511) | Fav: 0 | SH: Yes|

Completed! Total scraped: 200

=== SCRAPING CITY 5/10: Budapest ===

--- Scraping Page (Collected: 200) ---
[201] $588 |Budapest| ★5.0 (0223) | Fav: 1 | SH: Yes|

=== SCRAPING CITY 5/10: Budapest ===

--- Scraping Page (Collected: 201) ---
[202] $622 |Budapest| ★4.91 (91927) | Fav: 1 | SH: Yes|
[203] $751 |Budapest| ★4.92 (92680) | Fav: 1 | SH: Yes|
[204] $1,475 |Budapest| ★4.98 (98145) | Fav: 1 | SH: Yes|
[205] $562 |Budapest| ★4.93 (93385) | Fav: 1 | SH: Yes|
[206] $928 |Budapest| ★4.97 (97513) | Fav: 1 | SH: No|
[207] $478 |Budapest| ★4.96 (96304) | Fav: 1 | SH: Yes|
[208] $423 |Budapest| ★4.98 (98325) | Fav: 1 | SH: Yes|
[209] $1,608 |Budapest| ★4.98 (98551) | Fav: 1 | SH: Yes|
[210] $536 |Budapest| ★4.93 (93167) | Fav: 1 | SH: Yes|
[211] $1,296 |Budapest| ★4.92 (92267) | Fav: 1 | SH: No|
[212] $1,216 |Budapest| ★4.97 (97225) | Fav: 1 | SH: Yes|
[213] $822 |Budapest| ★5.0 (056) | Fav: 1 | SH: No|
[214] $2,067 |Budapest| ★4.86 (86219) | Fav: 1 | SH: Yes|
[215] $1,544 |Budapest| ★4.92 (92253) | Fav: 1 | SH: Yes|
[216] $1,557 |Budapest| ★4.96 (9646) | Fav: 1 | SH: Yes|
[217] $1,349 |Budapest| ★4.86 (8658) | Fav: 1 | SH: No|
[218] $2,081 |Budapest| ★5.0 (055) | Fav: 1 | SH: Yes|
[219] $753 |Budapest| ★4.95 (95281) | Fav: 1 | SH: Yes|

=== SCRAPING CITY 5/10: Budapest ===

--- Scraping Page (Collected: 219) ---
[220] $1,502 |Budapest| ★5.0 (0273) | Fav: 1 | SH: Yes|
[221] $1,319 |Budapest| ★4.88 (88391) | Fav: 1 | SH: Yes|
[222] $1,130 |Budapest| ★4.97 (97426) | Fav: 1 | SH: Yes|
[223] $934 |Budapest| ★4.97 (97282) | Fav: 1 | SH: Yes|
[224] $1,057 |Budapest| ★4.96 (96475) | Fav: 1 | SH: Yes|
[225] $1,479 |Budapest| ★4.92 (92294) | Fav: 1 | SH: Yes|
[226] $780 |Budapest| ★4.85 (238) | Fav: 0 | SH: No|
[227] $706 |Budapest| ★4.91 (91794) | Fav: 1 | SH: Yes|
[228] $1,094 |Budapest| ★5.0 (0145) | Fav: 1 | SH: No|
[229] $851 |Budapest| ★4.83 (83630) | Fav: 1 | SH: No|
[230] $1,399 |Budapest| ★4.91 (258) | Fav: 0 | SH: Yes|
[231] $459 |Budapest| ★4.92 (92197) | Fav: 1 | SH: Yes|
[232] $2,395 |Budapest| ★4.73 (73617) | Fav: 1 | SH: Yes|
[233] $3,302 |Budapest| ★4.89 (9) | Fav: 0 | SH: Yes|
[234] $1,171 |Budapest| ★4.89 (89465) | Fav: 1 | SH: Yes|
[235] $1,103 |Budapest| ★4.94 (9484) | Fav: 1 | SH: Yes|
[236] $674 |Budapest| ★4.88 (8850) | Fav: 1 | SH: No|
[237] $1,328 |Budapest| ★4.94 (94158) | Fav: 1 | SH: Yes|

=== SCRAPING CITY 5/10: Budapest ===

--- Scraping Page (Collected: 237) ---
[238] $829 |Budapest| ★4.93 (93283) | Fav: 1 | SH: Yes|
[239] $354 |Budapest| ★4.9 (9263) | Fav: 1 | SH: Yes|
[240] $608 |Budapest| ★4.88 (8852) | Fav: 1 | SH: Yes|
[241] $457 |Budapest| ★4.85 (85488) | Fav: 1 | SH: Yes|
[242] $2,535 |Budapest| ★5.0 (028) | Fav: 1 | SH: No|
[243] $504 |Budapest| ★4.9 (9333) | Fav: 1 | SH: Yes|
[244] $1,077 |Budapest| ★4.93 (520) | Fav: 0 | SH: Yes|
[245] $763 |Budapest| ★4.9 (9241) | Fav: 1 | SH: Yes|
[246] $842 |Budapest| ★4.9 (9496) | Fav: 1 | SH: No|
[247] $852 |Budapest| ★4.92 (92388) | Fav: 1 | SH: Yes|
[248] $951 |Budapest| ★4.95 (95173) | Fav: 1 | SH: Yes|
[249] $487 |Budapest| ★New (1) | Fav: 0 | SH: No|
[250] $772 |Budapest| ★4.93 (93458) | Fav: 1 | SH: Yes|

Completed! Total scraped: 250

=== SCRAPING CITY 6/10: Lisbon ===

--- Scraping Page (Collected: 250) ---
[251] $1,426 |Lisbon| ★4.98 (9864) | Fav: 1 | SH: Yes|

=== SCRAPING CITY 6/10: Lisbon ===

--- Scraping Page (Collected: 251) ---
[252] $1,682 |Lisbon| ★4.91 (9179) | Fav: 1 | SH: Yes|
[253] $1,639 |Lisbon| ★4.93 (93346) | Fav: 1 | SH: Yes|
[254] $1,016 |Lisbon| ★5.0 (16) | Fav: 0 | SH: No|
[255] $878 |Lisbon| ★4.97 (97429) | Fav: 1 | SH: Yes|
[256] $2,347 |Lisbon| ★4.97 (97235) | Fav: 1 | SH: Yes|
[257] $1,128 |Lisbon| ★4.86 (86629) | Fav: 1 | SH: Yes|
[258] $788 |Lisbon| ★5.0 (07) | Fav: 1 | SH: No|
[259] $691 |Lisbon| ★4.98 (98450) | Fav: 1 | SH: Yes|
[260] $3,095 |Lisbon| ★4.98 (98341) | Fav: 1 | SH: Yes|
[261] $4,520 |Lisbon| ★4.98 (98373) | Fav: 1 | SH: Yes|
[262] $1,729 |Lisbon| ★4.92 (92437) | Fav: 1 | SH: Yes|
[263] $1,576 |Lisbon| ★5.0 (3) | Fav: 0 | SH: Yes|
[264] $461 |Lisbon| ★5.0 (2) | Fav: 0 | SH: No|
[265] $1,058 |Lisbon| ★5.0 (4) | Fav: 0 | SH: No|
[266] $1,681 |Lisbon| ★4.9 (9108) | Fav: 1 | SH: Yes|
[267] $1,932 |Lisbon| ★5.0 (0219) | Fav: 1 | SH: Yes|
[268] $1,225 |Lisbon| ★5.0 (0276) | Fav: 1 | SH: Yes|
[269] $759 |Lisbon| ★4.93 (9315) | Fav: 1 | SH: No|

=== SCRAPING CITY 6/10: Lisbon ===

--- Scraping Page (Collected: 269) ---
[270] $1,065 |Lisbon| ★4.95 (95419) | Fav: 1 | SH: Yes|
[271] $738 |Lisbon| ★4.88 (88480) | Fav: 1 | SH: Yes|
[272] $1,905 |Lisbon| ★5.0 (0123) | Fav: 1 | SH: No|
[273] $1,217 |Lisbon| ★4.91 (91544) | Fav: 1 | SH: Yes|
[274] $665 |Lisbon| ★5.0 (011) | Fav: 1 | SH: No|
[275] $2,857 |Lisbon| ★4.96 (9650) | Fav: 1 | SH: No|
[276] $691 |Lisbon| ★4.98 (98450) | Fav: 1 | SH: No|
[277] $923 |Lisbon| ★4.69 (55) | Fav: 0 | SH: Yes|
[278] $929 |Lisbon| ★4.85 (85587) | Fav: 1 | SH: Yes|
[279] $2,769 |Lisbon| ★4.93 (93260) | Fav: 1 | SH: Yes|
[280] $1,067 |Lisbon| ★4.9 (9508) | Fav: 1 | SH: No|
[281] $918 |Lisbon| ★4.81 (81236) | Fav: 1 | SH: No|
[282] $728 |Lisbon| ★4.86 (507) | Fav: 0 | SH: Yes|
[283] $1,572 |Lisbon| ★4.97 (97442) | Fav: 1 | SH: No|
[284] $1,074 |Lisbon| ★4.93 (93420) | Fav: 1 | SH: Yes|
[285] $1,177 |Lisbon| ★4.95 (9520) | Fav: 1 | SH: Yes|
[286] $1,689 |Lisbon| ★4.96 (96488) | Fav: 1 | SH: Yes|
[287] $1,256 |Lisbon| ★4.98 (98184) | Fav: 1 | SH: No|

=== SCRAPING CITY 6/10: Lisbon ===

--- Scraping Page (Collected: 287) ---
[288] $1,541 |Lisbon| ★4.91 (9111) | Fav: 1 | SH: Yes|
[289] $2,334 |Lisbon| ★4.96 (96340) | Fav: 1 | SH: Yes|
[290] $1,224 |Lisbon| ★4.89 (122) | Fav: 0 | SH: Yes|

In [ ]:
df_scraped1 = pd.DataFrame(all_data1)
df_scraped1

,Name,city,Price,Superhost,is_fav,Rating,Reviews,URL
0,Cozy houseboat with parking in the center of A...,Amsterdam,"$1,202",Yes,1,4.97,97322,https://www.airbnb.com/rooms/58087008775012407...
1,Classic houseboat in the city center of Amsterdam,Amsterdam,"$1,350",No,0,4.74,347,https://www.airbnb.com/rooms/22643412?search_m...
2,Beautiful stylish detached villa,Amsterdam,"$2,065",Yes,1,4.86,86242,https://www.airbnb.com/rooms/91064078589601919...
3,Spacious and comfortable cottage near Amsterdam,Amsterdam,"$3,031",Yes,1,4.95,95194,https://www.airbnb.com/rooms/51395892?search_m...
4,Numa | XL 2 Bedroom Apartment with Sofa Bed,Amsterdam,"$1,877",No,0,4.67,201,https://www.airbnb.com/rooms/11159175642092863...
...,...,...,...,...,...,...,...,...
495,Wonderful Augarten City-Apartment,Vienna,$965,No,1,4.97,97597,https://www.airbnb.com/rooms/4431063?search_mo...
496,"Urban Vienna Apartment, 6 people, 2 bathrooms",Vienna,$855,Yes,0,4.87,147,https://www.airbnb.com/rooms/10580977413369461...
497,"Naschmarkt apartment, newly refurbished, 6 people",Vienna,"$1,270",Yes,1,4.94,94242,https://www.airbnb.com/rooms/71344270011888680...
498,Fabulous City Center Apartment - Apt 18A,Vienna,"$2,020",Yes,1,4.78,78376,https://www.airbnb.com/rooms/13402481?search_m...
499,Good vibes in Ottakring *****Vienna,Vienna,"$3,284",No,1,4.99,99300,https://www.airbnb.com/rooms/9396589?search_mo...

In [ ]:
df_scraped1.to_csv("/content/drive/MyDrive/my.flutter.2025/Instant_ai_training/airbnb_scraped_ALL_DATA.csv", index=False)

In [ ]:
df_scraped1["city"].value_counts()

city
Amsterdam    50
Athens       50
Barcelona    50
Berlin       50
Budapest     50
Lisbon       50
London       50
Paris        50
Rome         50
Vienna       50
Name: count, dtype: int64

In [ ]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options

# Prepare target URLs
urls_to_scrape = df_scraped1['URL'].unique().tolist()
print(f"Total unique URLs to enrich: {len(urls_to_scrape)}")

chrome_options = Options()
chrome_options.add_argument("--window-size=1920,1080")
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--start-maximized")

driver = webdriver.Chrome(options=chrome_options)
wait = WebDriverWait(driver, 6)

enriched_details = []

try:
    for i, url in enumerate(urls_to_scrape, 1):
        print(f"Processing [{i}/{len(urls_to_scrape)}]: {url}")
        guests, bedrooms, beds, baths, host_name = "N/A", "N/A", "N/A", "N/A", "N/A"

        try:
            driver.get(url)
            # Wait for main container or body elements
            wait.until(EC.presence_of_element_located((By.TAG_NAME, "body")))
            time.sleep(1.5)

            page_text = driver.find_element(By.TAG_NAME, "body").text

            # Extract layout metrics (e.g. "4 guests · 2 bedrooms · 3 beds · 1 bath")
            # Let's search inside text
            metrics_match = re.search(r"(\d+)\s+guest[s]?.*?(\d+)\s+bedroom[s]?.*?(\d+)\s+bed[s]?.*?(\d+)\s+bath[s]?", page_text, re.IGNORECASE)
            if metrics_match:
                guests = metrics_match.group(1)
                bedrooms = metrics_match.group(2)
                beds = metrics_match.group(3)
                baths = metrics_match.group(4)
            else:
                # Individual fallbacks
                g_m = re.search(r"(\d+)\s+guest[s]?", page_text, re.IGNORECASE)
                br_m = re.search(r"(\d+)\s+bedroom[s]?", page_text, re.IGNORECASE)
                bd_m = re.search(r"(\d+)\s+bed[s]?", page_text, re.IGNORECASE)
                ba_m = re.search(r"(\d+)\s+bath[s]?", page_text, re.IGNORECASE)
                if g_m: guests = g_m.group(1)
                if br_m: bedrooms = br_m.group(1)
                if bd_m: beds = bd_m.group(1)
                if ba_m: baths = ba_m.group(1)

            # Extract Host Name
            # Typically structured as "Hosted by Name" or "Host: Name"
            host_match = re.search(r"Hosted by ([A-Z][a-z]+)", page_text)
            if host_match:
                host_name = host_match.group(1)
            else:
                host_match_alt = re.search(r"Host:\s*([A-Z][a-z]+)", page_text, re.IGNORECASE)
                if host_match_alt: host_name = host_match_alt.group(1)

        except Exception as e:
            print(f"Error processing {url}: {e}")

        enriched_details.append({
            "URL": url,
            "Guests": guests,
            "Bedrooms_Count": bedrooms,
            "Beds": beds,
            "Baths": baths,
            "Host_Name": host_name
        })

        # Output real-time feedback
        print(f"   -> G: {guests} | BR: {bedrooms} | BD: {beds} | BA: {baths} | Host: {host_name}")

        # Intermediate backup to check progress every 10 steps
        if i % 10 == 0:
            pd.DataFrame(enriched_details).to_csv("/content/enriched_backup.csv", index=False)

finally:
    driver.quit()

# Create DataFrame of scraped details
df_details = pd.DataFrame(enriched_details)
display(df_details.head())

Total unique URLs to enrich: 500
Processing [1/500]: https://www.airbnb.com/rooms/580870087750124077?search_mode=regular_search&adults=1&check_in=2027-02-08&check_out=2027-02-13&children=0&infants=0&pets=0&source_impression_id=p3_3fa66173-aeee-44e2-816e-c805a9f15f56_de9ab432-7214-4006-8b0a-c1b28bb4698b_0_580870087750124077_0&previous_page_section_name=1000&federated_search_id=3fa66173-aeee-44e2-816e-c805a9f15f56
   -> G: 4 | BR: 2 | BD: 3 | BA: 1 | Host: N/A
Processing [2/500]: https://www.airbnb.com/rooms/22643412?search_mode=regular_search&adults=1&check_in=2026-11-21&check_out=2026-11-26&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_22643412_0&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 4 | BR: 2 | BD: 2 | BA: 1 | Host: Manuel
Processing [3/500]: https://www.airbnb.com/rooms/910640785896019190?search_mode=regular_search&adults=1&check_in=2026-11-08&check_out=2026-11-13&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_910640785896019190_1&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 6 | BR: 4 | BD: 5 | BA: 5 | Host: Leontien
Processing [4/500]: https://www.airbnb.com/rooms/51395892?search_mode=regular_search&adults=1&check_in=2026-11-10&check_out=2026-11-15&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_51395892_2&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 6 | BR: 3 | BD: 3 | BA: 5 | Host: Mabel
Processing [5/500]: https://www.airbnb.com/rooms/1115917564209286383?search_mode=regular_search&adults=1&check_in=2026-10-31&check_out=2026-11-05&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_1115917564209286383_3&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 6 | BR: 2 | BD: 4 | BA: 1 | Host: N/A
Processing [6/500]: https://www.airbnb.com/rooms/18059130?search_mode=regular_search&adults=1&check_in=2026-11-08&check_out=2026-11-13&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_18059130_4&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 4 | BR: 2 | BD: 3 | BA: 5 | Host: N/A
Processing [7/500]: https://www.airbnb.com/rooms/28198817?search_mode=regular_search&adults=1&check_in=2026-11-09&check_out=2026-11-14&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_28198817_5&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 4 | BR: 2 | BD: 3 | BA: 5 | Host: N/A
Processing [8/500]: https://www.airbnb.com/rooms/703633681123945658?search_mode=regular_search&adults=1&check_in=2027-01-01&check_out=2027-01-06&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_703633681123945658_6&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 4 | BR: 3 | BD: 3 | BA: 2 | Host: N/A
Processing [9/500]: https://www.airbnb.com/rooms/1089729860290716610?search_mode=regular_search&adults=1&check_in=2026-12-06&check_out=2026-12-11&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_1089729860290716610_7&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 4 | BR: 2 | BD: 2 | BA: 1 | Host: N/A
Processing [10/500]: https://www.airbnb.com/rooms/1269518334512050670?search_mode=regular_search&adults=1&check_in=2026-11-10&check_out=2026-11-15&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_1269518334512050670_8&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 3 | BR: 2 | BD: 2 | BA: 1 | Host: Wouter
Processing [11/500]: https://www.airbnb.com/rooms/1468720735645197860?search_mode=regular_search&adults=1&check_in=2026-11-01&check_out=2026-11-06&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_1468720735645197860_9&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 4 | BR: 2 | BD: 2 | BA: 1 | Host: John
Processing [12/500]: https://www.airbnb.com/rooms/30464401?search_mode=regular_search&adults=1&check_in=2026-11-01&check_out=2026-11-06&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_30464401_10&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 4 | BR: 2 | BD: 3 | BA: 1 | Host: N/A
Processing [13/500]: https://www.airbnb.com/rooms/1765168923620900151?search_mode=regular_search&adults=1&check_in=2026-10-28&check_out=2026-11-02&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_1765168923620900151_11&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 4 | BR: 2 | BD: 2 | BA: 2 | Host: Fay
Processing [14/500]: https://www.airbnb.com/rooms/1113044804402014015?search_mode=regular_search&adults=1&check_in=2026-11-14&check_out=2026-11-19&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_1113044804402014015_12&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 4 | BR: 2 | BD: 3 | BA: 1 | Host: N/A
Processing [15/500]: https://www.airbnb.com/rooms/32464492?search_mode=regular_search&adults=1&check_in=2026-11-07&check_out=2026-11-12&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_32464492_13&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 4 | BR: 2 | BD: 4 | BA: 1 | Host: N/A
Processing [16/500]: https://www.airbnb.com/rooms/36669987?search_mode=regular_search&adults=1&check_in=2026-12-21&check_out=2026-12-26&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_36669987_14&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 4 | BR: 2 | BD: 3 | BA: 5 | Host: Lou
Processing [17/500]: https://www.airbnb.com/rooms/13952479?search_mode=regular_search&adults=1&check_in=2027-01-30&check_out=2027-02-04&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_13952479_15&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 4 | BR: 2 | BD: 3 | BA: 1 | Host: Lora
Processing [18/500]: https://www.airbnb.com/rooms/29116941?search_mode=regular_search&adults=1&check_in=2027-01-07&check_out=2027-01-12&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_29116941_16&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 4 | BR: 2 | BD: 6 | BA: 1 | Host: N/A
Processing [19/500]: https://www.airbnb.com/rooms/1356509629168385961?search_mode=regular_search&adults=1&check_in=2026-11-01&check_out=2026-11-06&children=0&infants=0&pets=0&source_impression_id=p3_1b97aaa1-8aa0-47b0-a371-8c819d74a4d7_b1c05df0-238c-4b25-8bbb-3cab46b99aae_0_1356509629168385961_17&previous_page_section_name=1000&federated_search_id=1b97aaa1-8aa0-47b0-a371-8c819d74a4d7
   -> G: 6 | BR: 2 | BD: 3 | BA: 5 | Host: Isabelle
Processing [20/500]: https://www.airbnb.com/rooms/1356509629168385961?search_mode=regular_search&adults=1&check_in=2026-11-01&check_out=2026-11-06&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_1356509629168385961_0&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 6 | BR: 2 | BD: 3 | BA: 5 | Host: Isabelle
Processing [21/500]: https://www.airbnb.com/rooms/30928188?search_mode=regular_search&adults=1&check_in=2027-01-10&check_out=2027-01-15&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_30928188_1&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 4 | BR: 2 | BD: 3 | BA: 2 | Host: N/A
Processing [22/500]: https://www.airbnb.com/rooms/851044?search_mode=regular_search&adults=1&check_in=2027-01-08&check_out=2027-01-13&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_851044_2&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 4 | BR: 2 | BD: 2 | BA: 5 | Host: Nova
Processing [23/500]: https://www.airbnb.com/rooms/1721158888142829660?search_mode=regular_search&adults=1&check_in=2026-11-08&check_out=2026-11-13&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_1721158888142829660_3&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 8 | BR: 4 | BD: 5 | BA: 5 | Host: N/A
Processing [24/500]: https://www.airbnb.com/rooms/905863938271552018?search_mode=regular_search&adults=1&check_in=2026-11-09&check_out=2026-11-14&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_905863938271552018_4&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 4 | BR: 2 | BD: 3 | BA: 2 | Host: Michelle
Processing [25/500]: https://www.airbnb.com/rooms/53248489?search_mode=regular_search&adults=1&check_in=2026-11-03&check_out=2026-11-08&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_53248489_5&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 4 | BR: 2 | BD: 2 | BA: 3 | Host: Minne
Processing [26/500]: https://www.airbnb.com/rooms/1638591218833431770?search_mode=regular_search&adults=1&check_in=2026-11-08&check_out=2026-11-13&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_1638591218833431770_6&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 4 | BR: 2 | BD: 2 | BA: 1 | Host: Marta
Processing [27/500]: https://www.airbnb.com/rooms/53805044?search_mode=regular_search&adults=1&check_in=2026-11-08&check_out=2026-11-13&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_53805044_7&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 4 | BR: 2 | BD: 2 | BA: 1 | Host: Valerio
Processing [28/500]: https://www.airbnb.com/rooms/928201214259691418?search_mode=regular_search&adults=1&check_in=2027-01-03&check_out=2027-01-08&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_928201214259691418_8&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 4 | BR: 2 | BD: 2 | BA: 1 | Host: Erik
Processing [29/500]: https://www.airbnb.com/rooms/646185276389800252?search_mode=regular_search&adults=1&check_in=2026-11-02&check_out=2026-11-07&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_646185276389800252_9&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 4 | BR: 2 | BD: 2 | BA: 1 | Host: Yeter
Processing [30/500]: https://www.airbnb.com/rooms/1452808380711221585?search_mode=regular_search&adults=1&check_in=2026-11-08&check_out=2026-11-13&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_1452808380711221585_10&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 4 | BR: 2 | BD: 4 | BA: 1 | Host: N/A
Processing [31/500]: https://www.airbnb.com/rooms/741043?search_mode=regular_search&adults=1&check_in=2026-10-31&check_out=2026-11-05&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_741043_11&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 4 | BR: 3 | BD: 3 | BA: 2 | Host: Nicole
Processing [32/500]: https://www.airbnb.com/rooms/39501874?search_mode=regular_search&adults=1&check_in=2026-11-27&check_out=2026-12-02&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_39501874_12&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 6 | BR: 2 | BD: 3 | BA: 5 | Host: Vacation
Processing [33/500]: https://www.airbnb.com/rooms/915084412579814458?search_mode=regular_search&adults=1&check_in=2026-12-13&check_out=2026-12-18&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_915084412579814458_13&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 4 | BR: 2 | BD: 2 | BA: 5 | Host: John
Processing [34/500]: https://www.airbnb.com/rooms/14816635?search_mode=regular_search&adults=1&check_in=2026-11-08&check_out=2026-11-13&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_14816635_14&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 4 | BR: 2 | BD: 2 | BA: 1 | Host: N/A
Processing [35/500]: https://www.airbnb.com/rooms/7925449?search_mode=regular_search&adults=1&check_in=2026-11-02&check_out=2026-11-07&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_7925449_15&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 4 | BR: 2 | BD: 2 | BA: 1 | Host: N/A
Processing [36/500]: https://www.airbnb.com/rooms/669234388249202231?search_mode=regular_search&adults=1&check_in=2026-11-08&check_out=2026-11-13&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_669234388249202231_16&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 4 | BR: 2 | BD: 2 | BA: 5 | Host: N/A
Processing [37/500]: https://www.airbnb.com/rooms/1241981153544142223?search_mode=regular_search&adults=1&check_in=2026-12-18&check_out=2026-12-23&children=0&infants=0&pets=0&source_impression_id=p3_24d213ec-4c24-48bc-968e-ddfae36f0e8a_13e8c620-d261-4435-8d46-6ce2fcdfa3b2_0_1241981153544142223_17&previous_page_section_name=1000&federated_search_id=24d213ec-4c24-48bc-968e-ddfae36f0e8a
   -> G: 4 | BR: 2 | BD: 3 | BA: 2 | Host: Santiago
Processing [38/500]: https://www.airbnb.com/rooms/39333210?search_mode=regular_search&adults=1&check_in=2026-11-23&check_out=2026-11-28&children=0&infants=0&pets=0&source_impression_id=p3_b3b4942a-0296-40f5-83ea-c11f8c0c28c1_31560f42-067b-452a-b3bd-853fe196e7a3_0_39333210_0&previous_page_section_name=1000&federated_search_id=b3b4942a-0296-40f5-83ea-c11f8c0c28c1
   -> G: 4 | BR: 2 | BD: 3 | BA: 1 | Host: N/A
Processing [39/500]: https://www.airbnb.com/rooms/1567205682497527695?search_mode=regular_search&adults=1&check_in=2026-11-08&check_out=2026-11-13&children=0&infants=0&pets=0&source_impression_id=p3_b3b4942a-0296-40f5-83ea-c11f8c0c28c1_31560f42-067b-452a-b3bd-853fe196e7a3_0_1567205682497527695_1&previous_page_section_name=1000&federated_search_id=b3b4942a-0296-40f5-83ea-c11f8c0c28c1
   -> G: 4 | BR: 2 | BD: 3 | BA: 5 | Host: Marcel
Processing [40/500]: https://www.airbnb.com/rooms/1794820625588668072?search_mode=regular_search&adults=1&check_in=2026-12-18&check_out=2026-12-23&children=0&infants=0&pets=0&source_impression_id=p3_b3b4942a-0296-40f5-83ea-c11f8c0c28c1_31560f42-067b-452a-b3bd-853fe196e7a3_0_1794820625588668072_2&previous_page_section_name=1000&federated_search_id=b3b4942a-0296-40f5-83ea-c11f8c0c28c1
   -> G: 4 | BR: 3 | BD: 3 | BA: 1 | Host: N/A
Processing [41/500]: https://www.airbnb.com/rooms/1127513525512170677?search_mode=regular_search&adults=1&check_in=2026-11-29&check_out=2026-12-04&children=0&infants=0&pets=0&source_impression_id=p3_b3b4942a-0296-40f5-83ea-c11f8c0c28c1_31560f42-067b-452a-b3bd-853fe196e7a3_0_1127513525512170677_3&previous_page_section_name=1000&federated_search_id=b3b4942a-0296-40f5-83ea-c11f8c0c28c1
   -> G: 6 | BR: 2 | BD: 3 | BA: 2 | Host: N/A
Processing [42/500]: https://www.airbnb.com/rooms/1709395876152548592?search_mode=regular_search&adults=1&check_in=2026-11-06&check_out=2026-11-11&children=0&infants=0&pets=0&source_impression_id=p3_b3b4942a-0296-40f5-83ea-c11f8c0c28c1_31560f42-067b-452a-b3bd-853fe196e7a3_0_1709395876152548592_4&previous_page_section_name=1000&federated_search_id=b3b4942a-0296-40f5-83ea-c11f8c0c28c1
   -> G: 8 | BR: 4 | BD: 8 | BA: 5 | Host: Cindy
Processing [43/500]: https://www.airbnb.com/rooms/1122467939556628115?search_mode=regular_search&adults=1&check_in=2026-11-08&check_out=2026-11-13&children=0&infants=0&pets=0&source_impression_id=p3_b3b4942a-0296-40f5-83ea-c11f8c0c28c1_31560f42-067b-452a-b3bd-853fe196e7a3_0_1122467939556628115_5&previous_page_section_name=1000&federated_search_id=b3b4942a-0296-40f5-83ea-c11f8c0c28c1
   -> G: 6 | BR: 2 | BD: 4 | BA: 1 | Host: Amsterdam
Processing [44/500]: https://www.airbnb.com/rooms/1093884393065505605?search_mode=regular_search&adults=1&check_in=2026-10-29&check_out=2026-11-03&children=0&infants=0&pets=0&source_impression_id=p3_b3b4942a-0296-40f5-83ea-c11f8c0c28c1_31560f42-067b-452a-b3bd-853fe196e7a3_0_1093884393065505605_6&previous_page_section_name=1000&federated_search_id=b3b4942a-0296-40f5-83ea-c11f8c0c28c1
   -> G: 9 | BR: 4 | BD: 9 | BA: 5 | Host: Antoinet
Processing [45/500]: https://www.airbnb.com/rooms/12282960?search_mode=regular_search&adults=1&check_in=2026-10-30&check_out=2026-11-04&children=0&infants=0&pets=0&source_impression_id=p3_b3b4942a-0296-40f5-83ea-c11f8c0c28c1_31560f42-067b-452a-b3bd-853fe196e7a3_0_12282960_7&previous_page_section_name=1000&federated_search_id=b3b4942a-0296-40f5-83ea-c11f8c0c28c1
   -> G: 4 | BR: 2 | BD: 3 | BA: 1 | Host: N/A
Processing [46/500]: https://www.airbnb.com/rooms/875252214813063443?search_mode=regular_search&adults=1&check_in=2026-11-16&check_out=2026-11-21&children=0&infants=0&pets=0&source_impression_id=p3_b3b4942a-0296-40f5-83ea-c11f8c0c28c1_31560f42-067b-452a-b3bd-853fe196e7a3_0_875252214813063443_8&previous_page_section_name=1000&federated_search_id=b3b4942a-0296-40f5-83ea-c11f8c0c28c1
   -> G: 4 | BR: 2 | BD: 2 | BA: 1 | Host: Fay
Processing [47/500]: https://www.airbnb.com/rooms/692289216733242743?search_mode=regular_search&adults=1&check_in=2026-11-16&check_out=2026-11-21&children=0&infants=0&pets=0&source_impression_id=p3_b3b4942a-0296-40f5-83ea-c11f8c0c28c1_31560f42-067b-452a-b3bd-853fe196e7a3_0_692289216733242743_9&previous_page_section_name=1000&federated_search_id=b3b4942a-0296-40f5-83ea-c11f8c0c28c1

,URL,Guests,Bedrooms_Count,Beds,Baths,Host_Name
0,https://www.airbnb.com/rooms/58087008775012407...,4,2,3,1,N/A
1,https://www.airbnb.com/rooms/22643412?search_m...,4,2,2,1,Manuel
2,https://www.airbnb.com/rooms/91064078589601919...,6,4,5,5,Leontien
3,https://www.airbnb.com/rooms/51395892?search_m...,6,3,3,5,Mabel
4,https://www.airbnb.com/rooms/11159175642092863...,6,2,4,1,N/A

In [ ]:
# Merge details back into our original scraped dataframe
df_final_scraped = df_scraped1.merge(df_details, on="URL", how="left")

# Save to our primary workspace on GDrive
output_path = "/content/drive/MyDrive/my.flutter.2025/Instant_ai_training/airbnb_scraped_ALL_DATA_ENRICHED.csv"
df_final_scraped.to_csv(output_path, index=False)
print(f"Enriched dataset successfully saved to: {output_path}")
display(df_final_scraped.head())

Enriched dataset successfully saved to: /content/drive/MyDrive/my.flutter.2025/Instant_ai_training/airbnb_scraped_ALL_DATA_ENRICHED.csv

,Name,city,Price,Superhost,is_fav,Rating,Reviews,URL,Guests,Bedrooms_Count,Beds,Baths,Host_Name
0,Cozy houseboat with parking in the center of A...,Amsterdam,"$1,202",Yes,1,4.97,97322,https://www.airbnb.com/rooms/58087008775012407...,4,2,3,1,N/A
1,Classic houseboat in the city center of Amsterdam,Amsterdam,"$1,350",No,0,4.74,347,https://www.airbnb.com/rooms/22643412?search_m...,4,2,2,1,Manuel
2,Beautiful stylish detached villa,Amsterdam,"$2,065",Yes,1,4.86,86242,https://www.airbnb.com/rooms/91064078589601919...,6,4,5,5,Leontien
3,Spacious and comfortable cottage near Amsterdam,Amsterdam,"$3,031",Yes,1,4.95,95194,https://www.airbnb.com/rooms/51395892?search_m...,6,3,3,5,Mabel
4,Numa | XL 2 Bedroom Apartment with Sofa Bed,Amsterdam,"$1,877",No,0,4.67,201,https://www.airbnb.com/rooms/11159175642092863...,6,2,4,1,N/A

In [ ]:
with open("/content/drive/MyDrive/my.flutter.2025/Instant_ai_training/airbnb_scraped_ALL_DATA_ENRICHED.csv","r") as f:
 df_scraped1=pd.read_csv(f)

In [ ]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options

# Prepare target URLs
urls_to_scrape = df_scraped1['URL'].unique().tolist()
print(f"Total unique URLs to scrape amenities for: {len(urls_to_scrape)}")

chrome_options = Options()
chrome_options.add_argument("--window-size=1920,1080")
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--start-maximized")

driver = webdriver.Chrome(options=chrome_options)
wait = WebDriverWait(driver, 8)

amenities_data = []

try:
    for i, url in enumerate(urls_to_scrape, 1):
        print(f"Processing [{i}/{len(urls_to_scrape)}]: {url}")
        listing_amenities = []

        try:
            driver.get(url)
            # Wait for main page to load
            wait.until(EC.presence_of_element_located((By.TAG_NAME, "body")))
            time.sleep(1.5)

            # Attempt to locate the 'Show all ... amenities' button
            # Typically contains 'Show all' and 'amenities'
            button_xpath = "//button[contains(., 'Show all') and contains(., 'amenities')]"

            try:
                # Scroll to ensure button is loaded and clickable
                btn = wait.until(EC.presence_of_element_located((By.XPATH, button_xpath)))
                driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", btn)
                time.sleep(0.5)
                driver.execute_script("arguments[0].click();", btn)

                # Wait for the modal dialog containing the amenities list
                # Airbnb uses role='dialog' for popup modals
                wait.until(EC.presence_of_element_located((By.XPATH, "//div[@role='dialog']")))
                time.sleep(1.0)

                # Extract text lines inside the dialog
                dialog_element = driver.find_element(By.XPATH, "//div[@role='dialog']")
                lines = dialog_element.text.split('\n')

                # Filter out titles, categories, or structural texts to keep actual amenities
                exclude_phrases = ["What this place offers", "Close", "amenities", "Unavailable:"]
                for line in lines:
                    line_strip = line.strip()
                    if line_strip and not any(phrase in line_strip for phrase in exclude_phrases) and len(line_strip) > 2:
                        listing_amenities.append(line_strip)

            except Exception as inner_e:
                # Fallback: if modal cannot open, scrape the basic amenities visible on main page
                print(f"   (Notice: Could not open modal. Scraping visible ones...)")
                visible_elements = driver.find_elements(By.XPATH, "//div[contains(@data-section-id, 'AMENITIES_DEFAULT')]//div")
                for elem in visible_elements:
                    t = elem.text.strip()
                    if t and '\n' not in t and len(t) > 2:
                        listing_amenities.append(t)

        except Exception as e:
            print(f"   (Error loading URL: {e})")

        # Deduplicate list
        unique_amenities = list(set(listing_amenities))
        amenities_str = ", ".join(unique_amenities) if unique_amenities else "N/A"

        print(f"   -> Found {len(unique_amenities)} amenities.")
        amenities_data.append({
            "URL": url,
            "Amenities": amenities_str
        })

        # Periodic progress backup
        if i % 10 == 0:
            pd.DataFrame(amenities_data).to_csv("/content/amenities_backup.csv", index=False)

finally:
    driver.quit()

# Create DataFrame
df_amenities = pd.DataFrame(amenities_data)
display(df_amenities.head())

Total unique URLs to scrape amenities for: 500

SessionNotCreatedException: Message: session not created: Chrome instance exited. Examine ChromeDriver verbose log to determine the cause.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception
Stacktrace:
#0 0x5a22577315ea <unknown>
#1 0x5a225704b869 <unknown>
#2 0x5a225708b21d <unknown>
#3 0x5a2257086c36 <unknown>
#4 0x5a22570d7117 <unknown>
#5 0x5a22570d67dc <unknown>
#6 0x5a225709529b <unknown>
#7 0x5a22570960a1 <unknown>
#8 0x5a22576f3fec <unknown>
#9 0x5a22576f27f5 <unknown>
#10 0x5a22576dd785 <unknown>
#11 0x5a22576f345a <unknown>
#12 0x5a22576c5d99 <unknown>
#13 0x5a225771bb18 <unknown>
#14 0x5a225771bcb5 <unknown>
#15 0x5a225772ff73 <unknown>
#16 0x78d5dd8fab84 <unknown>
#17 0x78d5dd987ecc <unknown>

In [ ]:
# Merge new amenities column to our enriched dataset
if 'df_final_scraped' in globals():
    df_final_complete = df_final_scraped.merge(df_amenities, on="URL", how="left")
else:
    # Fallback to df_scraped1
    df_final_complete = df_scraped1.merge(df_amenities, on="URL", how="left")

# Save the fully loaded and updated file to GDrive
final_output_path = "/content/drive/MyDrive/my.flutter.2025/Instant_ai_training/airbnb_scraped_ALL_DATA_ENRICHED.csv"
df_final_complete.to_csv(final_output_path, index=False)
print(f"Complete enriched dataset with Amenities saved successfully to: {final_output_path}")
display(df_final_complete.head())

Complete enriched dataset with Amenities saved successfully to: /content/drive/MyDrive/my.flutter.2025/Instant_ai_training/airbnb_scraped_ALL_DATA_ENRICHED.csv

,Name,city,Price,Superhost,is_fav,Rating,Reviews,URL,Guests,Bedrooms_Count,Beds,Baths,Host_Name,Amenities
0,Cozy houseboat with parking in the center of A...,Amsterdam,"$1,202",Yes,1,4.97,97322,https://www.airbnb.com/rooms/58087008775012407...,4,2,3,1,N/A,N/A
1,Classic houseboat in the city center of Amsterdam,Amsterdam,"$1,350",No,0,4.74,347,https://www.airbnb.com/rooms/22643412?search_m...,4,2,2,1,Manuel,Prices include all fees
2,Beautiful stylish detached villa,Amsterdam,"$2,065",Yes,1,4.86,86242,https://www.airbnb.com/rooms/91064078589601919...,6,4,5,5,Leontien,Rare find! This place is usually booked
3,Spacious and comfortable cottage near Amsterdam,Amsterdam,"$3,031",Yes,1,4.95,95194,https://www.airbnb.com/rooms/51395892?search_m...,6,3,3,5,Mabel,Rare find! This place is usually booked
4,Numa | XL 2 Bedroom Apartment with Sofa Bed,Amsterdam,"$1,877",No,0,4.67,201,https://www.airbnb.com/rooms/11159175642092863...,6,2,4,1,N/A,"Bathroom, Body soap, Coffee maker, Bedroom and..."

#trial2

In [ ]:
!pip install seleniumbase pandas openpyxl --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.6/93.6 kB 1.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 kB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 2.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.8/132.8 kB 4.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.2/171.2 kB 7.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 701.2/701.2 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.8/136.8 kB 14.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.7/40.7 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.5/386.5 kB 25.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.2/182.2 kB 18.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 53.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.9/109.9 kB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 254.7/254.7 kB 26.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.2/275.2 kB 27.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 97.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 kB 13.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.7/130.7 kB 14.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.7/310.7 kB 32.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.8/511.8 kB 47.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.7/135.7 kB 14.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.9/225.9 kB 23.8 MB/s eta 0:00:00
  Building wheel for PyAutoGUI (pyproject.toml) ... done
  Building wheel for pygetwindow (setup.py) ... done
  Building wheel for pyscreeze (pyproject.toml) ... done
  Building wheel for pytweening (setup.py) ... done
  Building wheel for mouseinfo (setup.py) ... done
  Building wheel for python3-Xlib (setup.py) ... done
  Building wheel for pyrect (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
google-adk 2.7.1 requires websockets<16,>=15.0.1, but you have websockets 17.3 which is incompatible.
bigframes 2.51.0 requires rich<14,>=12.4.4, but you have rich 15.0.0 which is incompatible.
google-genai 2.12.1 requires websockets<17.0,>=13.0.0, but you have websockets 17.3 which is incompatible.
langgraph-sdk 0.4.8 requires websockets<17,>=14, but you have websockets 17.3 which is incompatible.
torch 2.11.0+cpu requires setuptools<82, but you have setuptools 84.2.0 which is incompatible.

In [ ]:
!google-chrome --headless --no-sandbox --disable-gpu --dump-dom https://example.com 2>&1 | head -50

/bin/bash: line 1: google-chrome: command not found

In [ ]:
!pip install --upgrade seleniumbase --quiet
!apt-get update -qq
!wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
!dpkg -i google-chrome-stable_current_amd64.deb || apt-get -f install -y
!apt-get install -y libnss3 libxss1 libappindicator3-1 libindicator7 --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.6/93.6 kB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 kB 3.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 4.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.8/132.8 kB 9.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.2/171.2 kB 12.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 701.2/701.2 kB 25.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.8/136.8 kB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.7/40.7 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.5/386.5 kB 18.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.2/182.2 kB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 63.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.9/109.9 kB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 254.7/254.7 kB 18.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.2/275.2 kB 17.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 62.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 kB 8.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.7/130.7 kB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.7/310.7 kB 15.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.8/511.8 kB 24.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.7/135.7 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.9/225.9 kB 15.3 MB/s eta 0:00:00
  Building wheel for PyAutoGUI (pyproject.toml) ... done
  Building wheel for pygetwindow (setup.py) ... done
  Building wheel for pyscreeze (pyproject.toml) ... done
  Building wheel for pytweening (setup.py) ... done
  Building wheel for mouseinfo (setup.py) ... done
  Building wheel for python3-Xlib (setup.py) ... done
  Building wheel for pyrect (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
google-adk 2.7.1 requires websockets<16,>=15.0.1, but you have websockets 17.3 which is incompatible.
bigframes 2.51.0 requires rich<14,>=12.4.4, but you have rich 15.0.0 which is incompatible.
google-genai 2.12.1 requires websockets<17.0,>=13.0.0, but you have websockets 17.3 which is incompatible.
langgraph-sdk 0.4.8 requires websockets<17,>=14, but you have websockets 17.3 which is incompatible.
torch 2.11.0+cpu requires setuptools<82, but you have setuptools 84.2.1 which is incompatible.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
Selecting previously unselected package google-chrome-stable.
(Reading database ... 122807 files and directories currently installed.)
Preparing to unpack google-chrome-stable_current_amd64.deb ...
Unpacking google-chrome-stable (156.0.8078.47-1) ...
dpkg: dependency problems prevent configuration of google-chrome-stable:
 google-chrome-stable depends on libatk-bridge2.0-0 (>= 2.5.3); however:
  Package libatk-bridge2.0-0 is not installed.
 google-chrome-stable depends on libatk1.0-0 (>= 2.11.90); however:
  Package libatk1.0-0 is not installed.
 google-chrome-stable depends on libatspi2.0-0 (>= 2.9.90); however:
  Package libatspi2.0-0 is not installed.
 google-chrome-stable depends on libxcomposite1 (>= 1:0.4.4-1); however:
  Package libxcomposite1 is not installed.

dpkg: error processing package google-chrome-stable (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.12.0-4build2) ...
Errors were encountered while processing:
 google-chrome-stable
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  at-spi2-common at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0t64
  libatk1.0-0t64 libatspi2.0-0t64 libxcomposite1 libxtst6 session-migration
The following NEW packages will be installed:
  at-spi2-common at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0t64
  libatk1.0-0t64 libatspi2.0-0t64 libxcomposite1 libxtst6 session-migration
0 upgraded, 9 newly installed, 0 to remove and 27 not upgraded.
1 not fully installed or removed.
Need to get 331 kB of archives.
After this operation, 1,444 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble/main amd64 at-spi2-common all 2.52.0-1build1 [8,674 B]
Get:2 http://archive.ubuntu.com/ubuntu noble/main amd64 libatk1.0-0t64 amd64 2.52.0-1build1 [55.3 kB]
Get:3 http://archive.ubuntu.com/ubuntu noble/main amd64 libatspi2.0-0t64 amd64 2.52.0-1build1 [80.5 kB]
Get:4 http://archive.ubuntu.com/ubuntu noble/main amd64 libatk-bridge2.0-0t64 amd64 2.52.0-1build1 [66.0 kB]
Get:5 http://archive.ubuntu.com/ubuntu noble/main amd64 libxcomposite1 amd64 1:0.4.5-1build3 [6,320 B]
Get:6 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libxtst6 amd64 2:1.2.3-1.1ubuntu0.1 [12.6 kB]
Get:7 http://archive.ubuntu.com/ubuntu noble/main amd64 session-migration amd64 0.3.9build1 [9,034 B]
Get:8 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 gsettings-desktop-schemas all 46.1-0ubuntu1 [35.6 kB]
Get:9 http://archive.ubuntu.com/ubuntu noble/main amd64 at-spi2-core amd64 2.52.0-1build1 [56.6 kB]
Fetched 331 kB in 1s (456 kB/s)
Selecting previously unselected package at-spi2-common.
(Reading database ... 123083 files and directories currently installed.)
Preparing to unpack .../0-at-spi2-common_2.52.0-1build1_all.deb ...
Unpacking at-spi2-common (2.52.0-1build1) ...
Selecting previously unselected package libatk1.0-0t64:amd64.
Preparing to unpack .../1-libatk1.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatk1.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libatspi2.0-0t64:amd64.
Preparing to unpack .../2-libatspi2.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatspi2.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libatk-bridge2.0-0t64:amd64.
Preparing to unpack .../3-libatk-bridge2.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatk-bridge2.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../4-libxcomposite1_1%3a0.4.5-1build3_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../5-libxtst6_2%3a1.2.3-1.1ubuntu0.1_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1.1ubuntu0.1) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../6-session-migration_0.3.9build1_amd64.deb ...
Unpacking session-migration (0.3.9build1) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../7-gsettings-desktop-schemas_46.1-0ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (46.1-0ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../8-at-spi2-core_2.52.0-1build1_amd64.deb ...
Unpacking at-spi2-core (2.52.0-1build1) ...
Setting up session-migration (0.3.9build1) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1.1ubuntu0.1) ...
Setting up libatspi2.0-0t64:amd64 (2.52.0-1build1) ...
Setting up at-spi2-common (2.52.0-1build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build3) ...
Setting up gsettings-desktop-schemas (46.1-0ubuntu1) ...
Setting up libatk1.0-0t64:amd64 (2.52.0-1build1) ...
Setting up libatk-bridge2.0-0t64:amd64 (2.52.0-1build1) ...
Setting up google-chrome-stable (156.0.8078.47-1) ...
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/google-chrome (google-chrome) in auto mode
Processing triggers for libc-bin (2.39-0ubuntu8.9) ...
/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for libglib2.0-0t64:amd64 (2.80.0-6ubuntu3.9) ...
Setting up at-spi2-core (2.52.0-1build1) ...
Reading package lists...
Building dependency tree...
Reading state information...
libnss3 is already the newest version (2:3.98-1ubuntu0.2).
libnss3 set to manually installed.
libxss1 is already the newest version (1:1.2.3-1build3).
libxss1 set to manually installed.
The following additional packages will be installed:
  libdbusmenu-glib4 libdbusmenu-gtk3-4 libgail-common libgail18t64
  libgtk-3-0t64 libgtk-3-bin libgtk-3-common libgtk2.0-0t64 libgtk2.0-bin
  libgtk2.0-common librsvg2-common
Suggested packages:
  indicator-application gvfs
The following NEW packages will be installed:
  libappindicator3-1 libdbusmenu-glib4 libdbusmenu-gtk3-4 libgail-common
  libgail18t64 libgtk-3-0t64 libgtk-3-bin libgtk-3-common libgtk2.0-0t64
  libgtk2.0-bin libgtk2.0-common libindicator7 librsvg2-common
0 upgraded, 13 newly installed, 0 to remove and 27 not upgraded.
Need to get 6,823 kB of archives.
After this operation, 22.1 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble/main amd64 libdbusmenu-glib4 amd64 18.10.20180917~bzr492+repack1-3.1ubuntu5 [43.0 kB]
Get:2 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgtk-3-common all 3.24.41-4ubuntu1.3 [1,426 kB]
Get:3 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgtk-3-0t64 amd64 3.24.41-4ubuntu1.3 [2,913 kB]
Get:4 http://archive.ubuntu.com/ubuntu noble/main amd64 libdbusmenu-gtk3-4 amd64 18.10.20180917~bzr492+repack1-3.1ubuntu5 [27.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu noble/universe amd64 libappindicator3-1 amd64 12.10.1+20.10.20200706.1-0ubuntu5 [23.3 kB]
Get:6 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgtk2.0-common all 2.24.33-4ubuntu1.1 [127 kB]
Get:7 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgtk2.0-0t64 amd64 2.24.33-4ubuntu1.1 [2,006 kB]
Get:8 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgail18t64 amd64 2.24.33-4ubuntu1.1 [15.9 kB]
Get:9 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgail-common amd64 2.24.33-4ubuntu1.1 [126 kB]
Get:10 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgtk-3-bin amd64 3.24.41-4ubuntu1.3 [73.9 kB]
Get:11 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgtk2.0-bin amd64 2.24.33-4ubuntu1.1 [7,954 B]
Get:12 http://archive.ubuntu.com/ubuntu noble/universe amd64 libindicator7 amd64 16.10.0+18.04.20180321.1-0ubuntu8 [21.8 kB]
Get:13 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 librsvg2-common amd64 2.58.0+dfsg-1ubuntu0.1 [11.8 kB]
Fetched 6,823 kB in 2s (4,500 kB/s)
Selecting previously unselected package libdbusmenu-glib4:amd64.
(Reading database ... 123192 files and directories currently installed.)
Preparing to unpack .../00-libdbusmenu-glib4_18.10.20180917~bzr492+repack1-3.1ubuntu5_amd64.deb ...
Unpacking libdbusmenu-glib4:amd64 (18.10.20180917~bzr492+repack1-3.1ubuntu5) ...
Selecting previously unselected package libgtk-3-common.
Preparing to unpack .../01-libgtk-3-common_3.24.41-4ubuntu1.3_all.deb ...
Unpacking libgtk-3-common (3.24.41-4ubuntu1.3) ...
Selecting previously unselected package libgtk-3-0t64:amd64.
Preparing to unpack .../02-libgtk-3-0t64_3.24.41-4ubuntu1.3_amd64.deb ...
Unpacking libgtk-3-0t64:amd64 (3.24.41-4ubuntu1.3) ...
Selecting previously unselected package libdbusmenu-gtk3-4:amd64.
Preparing to unpack .../03-libdbusmenu-gtk3-4_18.10.20180917~bzr492+repack1-3.1ubuntu5_amd64.deb ...
Unpacking libdbusmenu-gtk3-4:amd64 (18.10.20180917~bzr492+repack1-3.1ubuntu5) ...
Selecting previously unselected package libappindicator3-1.
Preparing to unpack .../04-libappindicator3-1_12.10.1+20.10.20200706.1-0ubuntu5_amd64.deb ...
Unpacking libappindicator3-1 (12.10.1+20.10.20200706.1-0ubuntu5) ...
Selecting previously unselected package libgtk2.0-common.
Preparing to unpack .../05-libgtk2.0-common_2.24.33-4ubuntu1.1_all.deb ...
Unpacking libgtk2.0-common (2.24.33-4ubuntu1.1) ...
Selecting previously unselected package libgtk2.0-0t64:amd64.
Preparing to unpack .../06-libgtk2.0-0t64_2.24.33-4ubuntu1.1_amd64.deb ...
Unpacking libgtk2.0-0t64:amd64 (2.24.33-4ubuntu1.1) ...
Selecting previously unselected package libgail18t64:amd64.
Preparing to unpack .../07-libgail18t64_2.24.33-4ubuntu1.1_amd64.deb ...
Unpacking libgail18t64:amd64 (2.24.33-4ubuntu1.1) ...
Selecting previously unselected package libgail-common:amd64.
Preparing to unpack .../08-libgail-common_2.24.33-4ubuntu1.1_amd64.deb ...
Unpacking libgail-common:amd64 (2.24.33-4ubuntu1.1) ...
Selecting previously unselected package libgtk-3-bin.
Preparing to unpack .../09-libgtk-3-bin_3.24.41-4ubuntu1.3_amd64.deb ...
Unpacking libgtk-3-bin (3.24.41-4ubuntu1.3) ...
Selecting previously unselected package libgtk2.0-bin.
Preparing to unpack .../10-libgtk2.0-bin_2.24.33-4ubuntu1.1_amd64.deb ...
Unpacking libgtk2.0-bin (2.24.33-4ubuntu1.1) ...
Selecting previously unselected package libindicator7.
Preparing to unpack .../11-libindicator7_16.10.0+18.04.20180321.1-0ubuntu8_amd64.deb ...
Unpacking libindicator7 (16.10.0+18.04.20180321.1-0ubuntu8) ...
Selecting previously unselected package librsvg2-common:amd64.
Preparing to unpack .../12-librsvg2-common_2.58.0+dfsg-1ubuntu0.1_amd64.deb ...
Unpacking librsvg2-common:amd64 (2.58.0+dfsg-1ubuntu0.1) ...
Setting up libdbusmenu-glib4:amd64 (18.10.20180917~bzr492+repack1-3.1ubuntu5) ...
Setting up librsvg2-common:amd64 (2.58.0+dfsg-1ubuntu0.1) ...
Setting up libgtk2.0-common (2.24.33-4ubuntu1.1) ...
Setting up libgtk-3-common (3.24.41-4ubuntu1.3) ...
Setting up libgtk2.0-0t64:amd64 (2.24.33-4ubuntu1.1) ...
Setting up libgail18t64:amd64 (2.24.33-4ubuntu1.1) ...
Setting up libgtk2.0-bin (2.24.33-4ubuntu1.1) ...
Setting up libgail-common:amd64 (2.24.33-4ubuntu1.1) ...
Setting up libindicator7 (16.10.0+18.04.20180321.1-0ubuntu8) ...
Processing triggers for libc-bin (2.39-0ubuntu8.9) ...
/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for libglib2.0-0t64:amd64 (2.80.0-6ubuntu3.9) ...
Setting up libgtk-3-0t64:amd64 (3.24.41-4ubuntu1.3) ...
Processing triggers for libgdk-pixbuf-2.0-0:amd64 (2.42.10+dfsg-3ubuntu3.3) ...
Setting up libdbusmenu-gtk3-4:amd64 (18.10.20180917~bzr492+repack1-3.1ubuntu5) ...
Setting up libgtk-3-bin (3.24.41-4ubuntu1.3) ...
Setting up libappindicator3-1 (12.10.1+20.10.20200706.1-0ubuntu5) ...
Processing triggers for libc-bin (2.39-0ubuntu8.9) ...
/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

In [ ]:
# =====================================================
#  AIRBNB SCRAPER  —  one row per listing
#  ~50 listings × 10 cities  ⇒  ~500 rows × 30 cols
# =====================================================
import re, json, time, random, os
from datetime import datetime
from urllib.parse import urlparse, parse_qs
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from seleniumbase import Driver

# ---------------- CONFIG ----------------
cities          = ['Amsterdam','Athens','Barcelona','Berlin','Budapest',
                   'Lisbon','London','Paris','Rome','Vienna']
TARGET_PER_CITY = 50
OUTPUT_CSV      = "/content/airbnb_listings.csv"
OUTPUT_XLSX     = "/content/airbnb_listings.xlsx"

# ---------------- HELPERS ----------------
def safe_get(d, path, default=None):
    cur = d
    for p in path:
        if isinstance(cur, dict):
            cur = cur.get(p)
        elif isinstance(cur, list) and isinstance(p, int) and 0 <= p < len(cur):
            cur = cur[p]
        else:
            return default
        if cur is None:
            return default
    return cur

def get_deferred_state(driver):
    """Airbnb stores the full PDP JSON in <script id='data-deferred-state-0'>."""
    try:
        el  = driver.find_element(By.ID, "data-deferred-state-0")
        txt = el.get_attribute("textContent") or el.get_attribute("innerHTML")
        return json.loads(txt)
    except Exception:
        return None

def get_json_ld(driver):
    out = []
    try:
        for s in driver.find_elements(By.CSS_SELECTOR,
                                      'script[type="application/ld+json"]'):
            try:    out.append(json.loads(s.get_attribute("textContent")))
            except Exception: pass
    except Exception: pass
    return out

def parse_money(s):
    if s is None: return None
    s = re.sub(r"[^\d,\.]", "", str(s))
    if not s: return None
    s = s.replace(",", "")
    try:    return float(s)
    except ValueError: return None

def nights_from_url(url):
    q  = parse_qs(urlparse(url).query)
    ci, co = q.get("check_in",[None])[0], q.get("check_out",[None])[0]
    if ci and co:
        try:
            return (datetime.strptime(co, "%Y-%m-%d")
                  - datetime.strptime(ci, "%Y-%m-%d")).days
        except Exception: return None
    return None

# ---------------- CORE EXTRACTOR ----------------
def extract_listing(driver, wait, url, city):
    row = {k: None for k in [
        "Name","PropertyType","Price","Nights","PricePerNightEst",
        "Rating","Reviews","is_fav","Superhost","HostName","HostYears","HostReviews",
        "LocationName","LocationSubtitle","Latitude","Longitude",
        "Guests","Bedrooms","Beds","Baths",
        "Amenities","AmenitiesCount","Description",
        "CleaningFee","ServiceFee","Taxes",
        "AvailableDatesCount","AvailableDates","is_new"]}
    row["city"]      = city
    row["URL"]       = url
    row["is_fav"]    = 0
    row["Superhost"] = "No"
    row["is_new"]    = False

    # --- 1) JSON-LD (cheap fallback) ---
    for obj in get_json_ld(driver):
        if obj.get("@type") == "VacationRental":
            row["Name"]         = row["Name"]         or obj.get("name")
            row["Description"]  = row["Description"]  or obj.get("description")
            row["Latitude"]     = row["Latitude"]     or obj.get("latitude")
            row["Longitude"]    = row["Longitude"]    or obj.get("longitude")
            ar = obj.get("aggregateRating") or {}
            row["Rating"]       = row["Rating"]       or ar.get("ratingValue")
            row["Reviews"]      = row["Reviews"]      or ar.get("ratingCount")
            row["LocationName"] = row["LocationName"] or (obj.get("address") or {}).get("addressLocality")

    # --- 2) Deferred-state JSON (richest) ---
    state = get_deferred_state(driver)
    node  = None
    if state:
        for key, payload in (state.get("niobeClientData") or []):
            if isinstance(key, str) and key.startswith("StaysPdpSections"):
                node = safe_get(payload, ["data", "node"]); break
        if node is None:
            node = safe_get(state, ["niobeClientData", 0, 1, "data", "node"])

    if node:
        pdp = node.get("pdpPresentation") or {}

        desc = pdp.get("description") or {}
        row["Name"] = safe_get(desc, ["title","content","localizedString"]) or row["Name"]
        long_desc   = safe_get(desc, ["longDescriptionHtml","localizedString"])
        if long_desc:
            row["Description"] = re.sub(r"<[^>]+>", " ", long_desc).strip()

        ov = pdp.get("overview") or {}
        row["PropertyType"] = ov.get("title")
        for it in (ov.get("items") or []):
            itl = it.lower()
            m   = re.search(r"\d+", it)
            if not m: continue
            n = int(m.group())
            if   "guest"   in itl: row["Guests"]   = n
            elif "bedroom" in itl: row["Bedrooms"] = n
            elif "bath"    in itl: row["Baths"]    = n
            elif "bed"     in itl: row["Beds"]     = n

        loc = pdp.get("location") or {}
        row["LocationName"]     = loc.get("locationName") or row["LocationName"]
        row["LocationSubtitle"] = loc.get("subtitle")
        row["Latitude"]         = loc.get("latitude")  or row["Latitude"]
        row["Longitude"]        = loc.get("longitude") or row["Longitude"]

        amen = pdp.get("amenities") or {}
        groups = (amen.get("seeAllAmenitiesGroups")
                  or amen.get("previewAmenitiesGroups") or [])
        amens = []
        for g in groups:
            for a in (g.get("amenities") or []):
                if a.get("available") is False: continue
                t = a.get("title")
                if t and t not in amens: amens.append(t)
        if amens:
            row["Amenities"]      = " | ".join(amens)
            row["AmenitiesCount"] = len(amens)

        q  = pdp.get("quality") or {}
        rs = safe_get(q, ["listingRatingStats","overallRatingStats"]) or {}
        if rs.get("ratingAverage") is not None: row["Rating"]  = rs.get("ratingAverage")
        if rs.get("ratingCount")   is not None: row["Reviews"] = rs.get("ratingCount")
        row["is_new"] = bool(q.get("isNewListing"))
        gf = pdp.get("contextualizedGuestFavorites") or {}
        row["is_fav"] = 1 if (gf.get("isGuestFavorite")
                              or q.get("isGuestFavorite")) else 0

        host = pdp.get("hostInfo") or {}
        pd_  = host.get("passportData") or {}
        row["HostName"]  = pd_.get("name")
        row["Superhost"] = "Yes" if pd_.get("isSuperhost") else "No"
        for st in (pd_.get("stats") or []):
            if   st.get("type") == "YEARS_HOSTING": row["HostYears"]   = st.get("value")
            elif st.get("type") == "REVIEW_COUNT":  row["HostReviews"] = st.get("value")

    # --- 3) Price + nights ---
    row["Nights"] = nights_from_url(url)
    for sel in ['div[data-testid="book-it-default"]',
                'div[data-testid="book-it-default-sidebar"]',
                'div[data-testid="book-it-hover-target"]']:
        try:
            txt = driver.find_element(By.CSS_SELECTOR, sel).text
            m   = re.search(r"([\d,\.]+)\s*for\s*(\d+)\s*nights?", txt, re.IGNORECASE)
            if m:
                row["Price"]  = parse_money(m.group(1))
                row["Nights"] = int(m.group(2))
                if row["Nights"]:
                    row["PricePerNightEst"] = round(row["Price"] / row["Nights"], 2)
                break
        except Exception:
            continue

    if row["Price"] is None:
        for xp in ["//div[@data-testid='book-it-default']//span[contains(text(),'$')]",
                   "//div[@data-testid='book-it-default-sidebar']//span[contains(text(),'$')]"]:
            try:
                t  = WebDriverWait(driver, 2).until(
                        EC.presence_of_element_located((By.XPATH, xp))).text
                mm = re.search(r"[\$€£¥]\s*([\d,\.]+)", t)
                if mm:
                    row["Price"] = parse_money(mm.group(1)); break
            except Exception:
                continue

    # --- 4) Availability (inline calendar) ---
    try:
        avail = set()
        for c in driver.find_elements(By.CSS_SELECTOR,
                                      '[data-testid^="calendar-day-"]'):
            if c.get_attribute("data-is-day-blocked") == "false":
                m = re.match(r"calendar-day-(\d{2})/(\d{2})/(\d{4})",
                             c.get_attribute("data-testid") or "")
                if m:
                    mm, dd, yy = m.groups()
                    avail.add(f"{yy}-{mm}-{dd}")
        if avail:
            row["AvailableDates"]      = ",".join(sorted(avail))
            row["AvailableDatesCount"] = len(avail)
    except Exception:
        pass

    # --- 5) Cleaning / Service fee (best-effort) ---
    try:
        clicked = False
        for txt in ("Price details", "Price breakdown", "Show price details"):
            try:
                btn = driver.find_element(
                    By.XPATH,
                    f"//button[contains(., '{txt}')] | //a[contains(., '{txt}')]")
                driver.execute_script("arguments[0].click();", btn)
                clicked = True; time.sleep(1.5); break
            except Exception:
                continue
        if clicked:
            body = driver.find_element(By.TAG_NAME, "body").text
            for lbl in ("Cleaning fee","Service fee","Airbnb service fee","Taxes"):
                m = re.search(rf"{re.escape(lbl)}[^\d\n]{{0,20}}([\d,\.]+)",
                              body, re.IGNORECASE)
                if m:
                    key = lbl.replace(" ", "")
                    row[key] = parse_money(m.group(1))
            try:
                driver.find_element(By.CSS_SELECTOR,
                                    'button[aria-label="Close"]').click()
            except Exception:
                pass
    except Exception:
        pass

    if row["Rating"] is None and row["is_new"]:
        row["Rating"] = "New"
    return row

# ---------------- MAIN LOOP ----------------
all_data1 = []

for idx, city in enumerate(cities, 1):
    print(f"\n{'='*72}\n=== CITY {idx}/{len(cities)}: {city} ===\n{'='*72}")

    URL = (
        f"https://www.airbnb.com/s/{city}/homes"
        "?refinement_paths%5B%5D=%2Fhomes"
        "&date_picker_type=calendar&search_type=filter_change"
        "&flexible_trip_lengths%5B%5D=one_week"
        "&monthly_start_date=2026-02-01&monthly_length=3&monthly_end_date=2026-05-01"
        "&price_filter_input_type=2&channel=EXPLORE&price_filter_num_nights=5"
        "&min_bedrooms=2"
        "&selected_filter_order%5B%5D=min_bedrooms%3A2"
        "&selected_filter_order%5B%5D=room_types%3AEntire%20home%2Fapt"
        "&update_selected_filters=true"
        f"&query={city}&search_mode=regular_search"
        "&room_types%5B%5D=Entire%20home%2Fapt"
    )

    # SeleniumBase handles all Colab Chrome/driver pain automatically
    driver = Driver(browser="chrome", headless=True)
    driver.set_window_size(1920, 1080)
    items_scraped_this_city = 0

    try:
        driver.get(URL)
        wait = WebDriverWait(driver, 8)

        while items_scraped_this_city < TARGET_PER_CITY:
            try:
                wait.until(EC.presence_of_all_elements_located(
                    (By.CSS_SELECTOR, "div[data-testid='card-container']")))
            except Exception:
                print("  [warn] no cards found, ending this city")
                break

            listings = driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='card-container']")
            listing_urls = []
            for l in listings:
                try:
                    u = l.find_element(By.TAG_NAME, "a").get_attribute("href")
                    if u and "/rooms/" in u and u not in listing_urls:
                        listing_urls.append(u)
                except Exception:
                    continue

            print(f"  page has {len(listing_urls)} card URLs "
                  f"(city progress {items_scraped_this_city}/{TARGET_PER_CITY})")

            main_window = driver.current_window_handle

            for url in listing_urls:
                if items_scraped_this_city >= TARGET_PER_CITY:
                    break
                try:
                    driver.execute_script(f"window.open('{url}', '_blank');")
                    driver.switch_to.window(driver.window_handles[-1])
                    wait.until(EC.presence_of_element_located((By.TAG_NAME, "h1")))
                    time.sleep(1.5)     # let deferred-state JSON settle

                    row = extract_listing(driver, wait, url, city)
                    all_data1.append(row)
                    items_scraped_this_city += 1

                    print(f"  [{len(all_data1):>3}] {row['city']:<10} "
                          f"| {str(row['Price']):<10} {row['Nights']}n "
                          f"| ★{row['Rating']} ({row['Reviews']}) "
                          f"| Fav:{row['is_fav']} SH:{row['Superhost']:<3} "
                          f"| {row['AmenitiesCount']} amens "
                          f"| {row['PropertyType']}")

                    # checkpoint save every 25 rows
                    if len(all_data1) % 25 == 0:
                        pd.DataFrame(all_data1).to_csv(
                            OUTPUT_CSV, index=False, encoding="utf-8-sig")
                        print(f"        …checkpoint saved ({len(all_data1)} rows)")

                    time.sleep(random.uniform(1.0, 2.0))
                    driver.close()
                    driver.switch_to.window(main_window)

                except Exception as e:
                    print(f"  [skip] {type(e).__name__}: {str(e)[:80]}")
                    if len(driver.window_handles) > 1:
                        driver.close()
                        driver.switch_to.window(main_window)
                    continue

            # paginate to next result page
            if items_scraped_this_city < TARGET_PER_CITY:
                try:
                    next_btn = driver.find_element(
                        By.CSS_SELECTOR, "a[aria-label='Next']")
                    driver.execute_script("arguments[0].click();", next_btn)
                    time.sleep(4)
                except Exception:
                    print("  [warn] no next page — city done")
                    break

    finally:
        try:    driver.quit()
        except Exception: pass
        print(f"  → collected {items_scraped_this_city} listings in {city}")
        print(f"  → running total: {len(all_data1)}")

# ---------------- SAVE ----------------
print(f"\n{'='*72}\nDONE — {len(all_data1)} listings total\n{'='*72}")

df = pd.DataFrame(all_data1)
df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")
print(f"Saved: {OUTPUT_CSV}")

try:
    df.to_excel(OUTPUT_XLSX, index=False)
    print(f"Saved: {OUTPUT_XLSX}")
except Exception as e:
    print(f"(xlsx skipped: {e})")

print("\nListings per city:")
print(df.groupby("city").size().to_string())

print("\nColumns:", list(df.columns))
print("\nFirst 3 rows:")
print(df.head(3).to_string())

========================================================================
=== CITY 1/10: Amsterdam ===
========================================================================
  page has 1 card URLs (city progress 0/50)
  [  1] Amsterdam  | None       5n | ★4.97 (322) | Fav:1 SH:Yes | 54 amens | Houseboat in Amsterdam, Netherlands
  page has 18 card URLs (city progress 1/50)
  [  2] Amsterdam  | None       5n | ★4.74 (1249) | Fav:0 SH:No  | 51 amens | Entire rental unit in Amsterdam, Netherlands
  [  3] Amsterdam  | None       5n | ★5 (11) | Fav:1 SH:Yes | 43 amens | Houseboat in Kortenhoef, Netherlands
  [  4] Amsterdam  | None       5n | ★3.6 (5) | Fav:0 SH:No  | 21 amens | Entire rental unit in Amsterdam, Netherlands
  [  5] Amsterdam  | None       5n | ★5 (3) | Fav:0 SH:Yes | 45 amens | Entire chalet in Vijfhuizen, Netherlands
  [  6] Amsterdam  | None       5n | ★5 (10) | Fav:1 SH:Yes | 63 amens | Entire cottage in Zaandam, Netherlands
  [  7] Amsterdam  | None       5n | ★5 (4) | Fav:0 SH:Yes | 46 amens | Entire bungalow in Vijfhuizen, Netherlands
  [  8] Amsterdam  | None       5n | ★4.73 (180) | Fav:0 SH:No  | 68 amens | Entire home in Aalsmeer, Netherlands
  [  9] Amsterdam  | None       5n | ★4.99 (117) | Fav:1 SH:Yes | 84 amens | Houseboat in Vinkeveen, Netherlands
  [ 10] Amsterdam  | None       5n | ★4.87 (71) | Fav:1 SH:No  | 27 amens | Entire loft in Amsterdam, Netherlands
  [ 11] Amsterdam  | None       5n | ★4.35 (26) | Fav:0 SH:No  | 45 amens | Entire serviced apartment in Amsterdam, Netherlands
  [ 12] Amsterdam  | None       5n | ★0 (0) | Fav:0 SH:No  | 18 amens | Entire rental unit in Amsterdam, Netherlands
  [ 13] Amsterdam  | None       5n | ★4.92 (73) | Fav:0 SH:Yes | 47 amens | Entire cabin in Almere, Netherlands
  [ 14] Amsterdam  | None       5n | ★5 (1) | Fav:0 SH:No  | 36 amens | Entire rental unit in Amsterdam, Netherlands
  [ 15] Amsterdam  | None       5n | ★4.88 (42) | Fav:0 SH:Yes | 50 amens | Entire home in Vijfhuizen, Netherlands
  [ 16] Amsterdam  | None       5n | ★5 (3) | Fav:0 SH:No  | 16 amens | Entire home in Halfweg, Netherlands
  [ 17] Amsterdam  | None       5n | ★4.92 (24) | Fav:0 SH:Yes | 67 amens | Entire rental unit in Amsterdam, Netherlands
  [ 18] Amsterdam  | None       5n | ★4.24 (87) | Fav:0 SH:No  | 23 amens | Entire bungalow in Halfweg, Netherlands
  [ 19] Amsterdam  | None       5n | ★4.99 (242) | Fav:1 SH:Yes | 64 amens | Entire condo in Amsterdam, Netherlands
  page has 18 card URLs (city progress 19/50)
  [ 20] Amsterdam  | None       5n | ★4.94 (117) | Fav:1 SH:Yes | 63 amens | Houseboat in Amsterdam, Netherlands
  [ 21] Amsterdam  | None       5n | ★0 (0) | Fav:0 SH:Yes | 41 amens | Entire home in Amsterdam, Netherlands
  [ 22] Amsterdam  | None       5n | ★4.86 (138) | Fav:1 SH:Yes | 42 amens | Entire condo in Amsterdam, Netherlands
  [ 23] Amsterdam  | None       5n | ★4.76 (34) | Fav:0 SH:Yes | 31 amens | Entire rental unit in Amsterdam, Netherlands
  [ 24] Amsterdam  | None       5n | ★4.96 (312) | Fav:1 SH:Yes | 47 amens | Entire rental unit in Uitgeest, Netherlands
  [ 25] Amsterdam  | None       5n | ★5 (17) | Fav:1 SH:Yes | 39 amens | Holiday park in Uitgeest, Netherlands
        …checkpoint saved (25 rows)
  [ 26] Amsterdam  | None       5n | ★4.52 (67) | Fav:0 SH:No  | 43 amens | Entire serviced apartment in Amsterdam, Netherlands
  [ 27] Amsterdam  | None       5n | ★4.93 (272) | Fav:1 SH:Yes | 57 amens | Entire rental unit in Vinkeveen, Netherlands
  [ 28] Amsterdam  | None       5n | ★4.98 (104) | Fav:1 SH:Yes | 42 amens | Entire serviced apartment in Abcoude, Netherlands
  [ 29] Amsterdam  | None       5n | ★4.98 (326) | Fav:1 SH:Yes | 93 amens | Entire villa in Zwanenburg-Dijk, Netherlands
  [ 30] Amsterdam  | None       5n | ★4.94 (175) | Fav:1 SH:Yes | 54 amens | Entire home in Oostzaan, Netherlands
  [ 31] Amsterdam  | None       5n | ★4.97 (154) | Fav:1 SH:Yes | 78 amens | Entire rental unit in Nieuw-Vennep, Netherlands
  [ 32] Amsterdam  | None       5n | ★4.74 (347) | Fav:0 SH:No  | 38 amens | Houseboat in Amsterdam, Netherlands
  [ 33] Amsterdam  | None       5n | ★4.98 (459) | Fav:1 SH:Yes | 29 amens | Entire rental unit in Amsterdam, Netherlands
  [ 34] Amsterdam  | None       5n | ★4.93 (458) | Fav:1 SH:Yes | 44 amens | Entire cottage in Ilpendam, Netherlands
  [ 35] Amsterdam  | None       5n | ★4.91 (176) | Fav:1 SH:Yes | 37 amens | Entire cabin in Beverwijk, Netherlands
  [ 36] Amsterdam  | None       5n | ★4.87 (320) | Fav:1 SH:No  | 78 amens | Entire home in Landsmeer, Netherlands
  [ 37] Amsterdam  | None       5n | ★4.97 (67) | Fav:1 SH:Yes | 46 amens | Entire rental unit in Haarlem, Netherlands
  page has 18 card URLs (city progress 37/50)
  [ 38] Amsterdam  | None       5n | ★4.88 (186) | Fav:1 SH:Yes | 58 amens | Entire place in Amsterdam, Netherlands
  [ 39] Amsterdam  | None       5n | ★5 (2) | Fav:0 SH:Yes | 52 amens | Entire home in Amsterdam, Netherlands
  [ 40] Amsterdam  | None       5n | ★5 (1) | Fav:0 SH:No  | 41 amens | Entire rental unit in Amsterdam, Netherlands
  [ 41] Amsterdam  | None       5n | ★5 (41) | Fav:1 SH:Yes | 47 amens | Entire villa in IJmuiden, Netherlands
  [ 42] Amsterdam  | None       5n | ★4.97 (239) | Fav:1 SH:Yes | 50 amens | Entire condo in Amsterdam, Netherlands
  [ 43] Amsterdam  | None       5n | ★4.83 (12) | Fav:0 SH:No  | 37 amens | Entire home in Amsterdam, Netherlands
  [ 44] Amsterdam  | None       5n | ★5 (6) | Fav:1 SH:No  | 30 amens | Entire rental unit in Amsterdam, Netherlands
  [ 45] Amsterdam  | None       5n | ★4.98 (84) | Fav:1 SH:Yes | 50 amens | Houseboat in Aalsmeer, Netherlands
  [ 46] Amsterdam  | None       5n | ★5 (17) | Fav:1 SH:Yes | 51 amens | Entire loft in Monnickendam, Netherlands
  [ 47] Amsterdam  | None       5n | ★4.92 (624) | Fav:1 SH:No  | 76 amens | Entire villa in Loosdrecht, Netherlands
  [ 48] Amsterdam  | None       5n | ★4.91 (214) | Fav:1 SH:Yes | 62 amens | Entire villa in Vinkeveen, Netherlands
  [ 49] Amsterdam  | None       5n | ★4.92 (99) | Fav:1 SH:Yes | 20 amens | Entire condo in Haarlem, Netherlands
  [ 50] Amsterdam  | None       5n | ★4.98 (174) | Fav:1 SH:Yes | 64 amens | Entire home in Amsterdam, Netherlands
        …checkpoint saved (50 rows)
  → collected 50 listings in Amsterdam
  → running total: 50

========================================================================
=== CITY 2/10: Athens ===
========================================================================
  page has 1 card URLs (city progress 0/50)
  [ 51] Athens     | None       5n | ★4.92 (416) | Fav:1 SH:Yes | 36 amens | Entire condo in Athens, Greece
  page has 18 card URLs (city progress 1/50)
  [ 52] Athens     | None       5n | ★4.94 (451) | Fav:1 SH:No  | 46 amens | Entire condo in Piraeus, Greece
  [ 53] Athens     | None       5n | ★4.9 (61) | Fav:1 SH:Yes | 42 amens | Entire rental unit in Athens, Greece
  [ 54] Athens     | None       5n | ★4.97 (106) | Fav:1 SH:Yes | 42 amens | Entire home in Athens, Greece
  [ 55] Athens     | None       5n | ★4.99 (189) | Fav:1 SH:Yes | 50 amens | Entire condo in Athens, Greece
  [ 56] Athens     | None       5n | ★5 (267) | Fav:1 SH:Yes | 64 amens | Entire condo in Athens, Greece
  [ 57] Athens     | None       5n | ★4.8 (226) | Fav:0 SH:No  | 63 amens | Entire condo in Athens, Greece
  [ 58] Athens     | None       5n | ★5 (11) | Fav:1 SH:No  | 43 amens | Entire rental unit in Athens, Greece
  [ 59] Athens     | None       5n | ★4.95 (111) | Fav:1 SH:Yes | 48 amens | Entire rental unit in Athens, Greece
  [ 60] Athens     | None       5n | ★4.94 (603) | Fav:1 SH:No  | 26 amens | Entire rental unit in Athens, Greece
  [ 61] Athens     | None       5n | ★4.98 (155) | Fav:1 SH:Yes | 73 amens | Entire condo in Athens, Greece
  [ 62] Athens     | None       5n | ★4.92 (370) | Fav:1 SH:Yes | 53 amens | Entire rental unit in Athens, Greece
  [ 63] Athens     | None       5n | ★5 (173) | Fav:1 SH:Yes | 55 amens | Entire rental unit in Athens, Greece
  [ 64] Athens     | None       5n | ★4.86 (552) | Fav:1 SH:Yes | 30 amens | Entire rental unit in Athens, Greece
  [ 65] Athens     | None       5n | ★5 (6) | Fav:1 SH:Yes | 45 amens | Entire rental unit in Athens, Greece
  [ 66] Athens     | None       5n | ★4.95 (60) | Fav:1 SH:Yes | 48 amens | Entire rental unit in Athens, Greece
  [ 67] Athens     | None       5n | ★4.99 (212) | Fav:1 SH:Yes | 49 amens | Entire rental unit in Athens, Greece
  [ 68] Athens     | None       5n | ★5 (3) | Fav:0 SH:Yes | 46 amens | Entire condo in Athens, Greece
  [ 69] Athens     | None       5n | ★4.96 (418) | Fav:1 SH:Yes | 39 amens | Entire condo in Athens, Greece
  page has 18 card URLs (city progress 19/50)
  [ 70] Athens     | None       5n | ★4.92 (53) | Fav:1 SH:Yes | 49 amens | Entire condo in Athens, Greece
  [ 71] Athens     | None       5n | ★4.84 (164) | Fav:0 SH:Yes | 31 amens | Entire condo in Athens, Greece
  [ 72] Athens     | None       5n | ★4.93 (14) | Fav:1 SH:No  | 36 amens | Entire rental unit in Athens, Greece
  [ 73] Athens     | None       5n | ★4.84 (207) | Fav:1 SH:Yes | 35 amens | Entire rental unit in Athens, Greece
  [ 74] Athens     | None       5n | ★4.97 (235) | Fav:1 SH:Yes | 59 amens | Entire condo in Athens, Greece
  [ 75] Athens     | None       5n | ★4.92 (72) | Fav:1 SH:Yes | 59 amens | Entire rental unit in Athens, Greece
        …checkpoint saved (75 rows)
  [ 76] Athens     | None       5n | ★5 (379) | Fav:1 SH:Yes | 56 amens | Entire rental unit in Athens, Greece
  [ 77] Athens     | None       5n | ★4.87 (134) | Fav:1 SH:Yes | 39 amens | Entire rental unit in Athens, Greece
  [ 78] Athens     | None       5n | ★5 (150) | Fav:1 SH:Yes | 65 amens | Entire rental unit in Athens, Greece
  [ 79] Athens     | None       5n | ★5 (16) | Fav:1 SH:Yes | 37 amens | Entire rental unit in Athens, Greece
  [ 80] Athens     | None       5n | ★4.95 (459) | Fav:1 SH:Yes | 36 amens | Entire condo in Athens, Greece
  [ 81] Athens     | None       5n | ★5 (14) | Fav:1 SH:Yes | 78 amens | Entire serviced apartment in Athens, Greece
  [ 82] Athens     | None       5n | ★5 (13) | Fav:1 SH:Yes | 44 amens | Entire rental unit in Athens, Greece
  [ 83] Athens     | None       5n | ★4.98 (97) | Fav:1 SH:Yes | 45 amens | Entire rental unit in Athens, Greece
  [ 84] Athens     | None       5n | ★4.98 (232) | Fav:1 SH:Yes | 59 amens | Entire condo in Athens, Greece
  [ 85] Athens     | None       5n | ★4.91 (91) | Fav:1 SH:Yes | 57 amens | Entire rental unit in Athens, Greece
  [ 86] Athens     | None       5n | ★4.99 (89) | Fav:1 SH:Yes | 45 amens | Entire rental unit in Athens, Greece
  [ 87] Athens     | None       5n | ★4.91 (253) | Fav:0 SH:Yes | 52 amens | Entire condo in Athens, Greece
  page has 18 card URLs (city progress 37/50)
  [ 88] Athens     | None       5n | ★4.95 (66) | Fav:1 SH:No  | 36 amens | Entire rental unit in Piraeus, Greece
  [ 89] Athens     | None       5n | ★4.96 (547) | Fav:1 SH:Yes | 40 amens | Entire condo in Athens, Greece
  [ 90] Athens     | None       5n | ★4.99 (80) | Fav:1 SH:Yes | 52 amens | Entire home in Athens, Greece
  [ 91] Athens     | None       5n | ★4.94 (52) | Fav:1 SH:Yes | 49 amens | Entire rental unit in Athens, Greece
  [ 92] Athens     | None       5n | ★5 (25) | Fav:1 SH:Yes | 51 amens | Entire condo in Athens, Greece
  [ 93] Athens     | None       5n | ★4.89 (100) | Fav:1 SH:Yes | 29 amens | Entire rental unit in Athens, Greece
  [ 94] Athens     | None       5n | ★4.91 (326) | Fav:1 SH:Yes | 54 amens | Entire condo in Athens, Greece
  [ 95] Athens     | None       5n | ★4.89 (643) | Fav:1 SH:Yes | 31 amens | Entire rental unit in Athens, Greece
  [ 96] Athens     | None       5n | ★5 (11) | Fav:1 SH:Yes | 21 amens | Entire rental unit in Athens, Greece
  [ 97] Athens     | None       5n | ★4.91 (277) | Fav:1 SH:Yes | 42 amens | Entire rental unit in Athens, Greece
  [ 98] Athens     | None       5n | ★4.87 (567) | Fav:0 SH:No  | 42 amens | Entire rental unit in Athens, Greece
  [ 99] Athens     | None       5n | ★4.99 (145) | Fav:1 SH:Yes | 50 amens | Entire rental unit in Athens, Greece
  [100] Athens     | None       5n | ★5 (24) | Fav:1 SH:Yes | 50 amens | Entire rental unit in Athens, Greece
        …checkpoint saved (100 rows)
  → collected 50 listings in Athens
  → running total: 100

========================================================================
=== CITY 3/10: Barcelona ===
========================================================================
  page has 1 card URLs (city progress 0/50)
  [101] Barcelona  | None       5n | ★4.9 (1635) | Fav:1 SH:Yes | 6 amens | Rental unit in Barcelona, Spain
  page has 18 card URLs (city progress 1/50)
  [102] Barcelona  | None       5n | ★5 (3) | Fav:0 SH:Yes | 32 amens | Entire rental unit in Barcelona, Spain
  [103] Barcelona  | None       5n | ★4.98 (226) | Fav:1 SH:Yes | 39 amens | Entire rental unit in Barcelona, Spain
  [104] Barcelona  | None       5n | ★4.84 (559) | Fav:1 SH:Yes | 41 amens | Entire rental unit in Barcelona, Spain
  [105] Barcelona  | None       5n | ★4.58 (943) | Fav:0 SH:Yes | 41 amens | Entire serviced apartment in Barcelona, Spain
  [106] Barcelona  | None       5n | ★4.95 (105) | Fav:1 SH:Yes | 49 amens | Serviced apartment in Barcelona, Spain
  [107] Barcelona  | None       5n | ★4.87 (570) | Fav:1 SH:Yes | 36 amens | Entire rental unit in Barcelona, Spain
  [108] Barcelona  | None       5n | ★4.97 (174) | Fav:1 SH:Yes | 52 amens | Entire rental unit in Barcelona, Spain
  [109] Barcelona  | None       5n | ★4.93 (551) | Fav:1 SH:Yes | 36 amens | Entire serviced apartment in Barcelona, Spain
  [110] Barcelona  | None       5n | ★4.95 (990) | Fav:1 SH:Yes | 45 amens | Entire loft in Barcelona, Spain
  [111] Barcelona  | None       5n | ★4.92 (566) | Fav:1 SH:Yes | 61 amens | Entire home in Barcelona, Spain
  [112] Barcelona  | None       5n | ★4.91 (934) | Fav:1 SH:Yes | 40 amens | Entire serviced apartment in Barcelona, Spain
  [113] Barcelona  | None       5n | ★4.94 (562) | Fav:1 SH:Yes | 49 amens | Entire rental unit in Barcelona, Spain
  [114] Barcelona  | None       5n | ★4.86 (239) | Fav:0 SH:Yes | 30 amens | Entire rental unit in Barcelona, Spain
  [115] Barcelona  | None       5n | ★4.77 (273) | Fav:1 SH:Yes | 27 amens | Entire rental unit in Barcelona, Spain
  [116] Barcelona  | None       5n | ★4.96 (190) | Fav:1 SH:Yes | 60 amens | Entire rental unit in Barcelona, Spain
  [117] Barcelona  | None       5n | ★4.9 (238) | Fav:1 SH:Yes | 44 amens | Entire rental unit in Barcelona, Spain
  [118] Barcelona  | None       5n | ★5 (3) | Fav:0 SH:Yes | 34 amens | Entire rental unit in Barcelona, Spain
  [119] Barcelona  | None       5n | ★4.82 (211) | Fav:1 SH:Yes | 41 amens | Entire serviced apartment in Barcelona, Spain
  page has 18 card URLs (city progress 19/50)
  [120] Barcelona  | None       5n | ★4.76 (622) | Fav:0 SH:Yes | 27 amens | Entire rental unit in Barcelona, Spain
  [121] Barcelona  | None       5n | ★5 (5) | Fav:0 SH:Yes | 25 amens | Entire rental unit in Barcelona, Spain
  [122] Barcelona  | None       5n | ★4.8 (420) | Fav:1 SH:Yes | 32 amens | Entire condo in Barcelona, Spain
  [123] Barcelona  | None       5n | ★4.94 (337) | Fav:1 SH:Yes | 39 amens | Entire rental unit in Barcelona, Spain
  [124] Barcelona  | None       5n | ★4.93 (518) | Fav:1 SH:Yes | 49 amens | Entire rental unit in Barcelona, Spain
  [125] Barcelona  | None       5n | ★4.85 (611) | Fav:1 SH:No  | 41 amens | Entire rental unit in Barcelona, Spain
        …checkpoint saved (125 rows)
  [126] Barcelona  | None       5n | ★5 (5) | Fav:0 SH:Yes | 37 amens | Entire rental unit in Cornellà de Llobregat, Spain
  [127] Barcelona  | None       5n | ★4.67 (1178) | Fav:0 SH:Yes | 24 amens | Rental unit in Barcelona, Spain
  [128] Barcelona  | None       5n | ★2.5 (2) | Fav:0 SH:No  | 31 amens | Entire rental unit in Barcelona, Spain
  [129] Barcelona  | None       5n | ★5 (1) | Fav:0 SH:No  | 41 amens | Entire rental unit in Barcelona, Spain
  [130] Barcelona  | None       5n | ★4.88 (389) | Fav:1 SH:Yes | 45 amens | Entire rental unit in Barcelona, Spain
  [131] Barcelona  | None       5n | ★5 (3) | Fav:0 SH:Yes | 36 amens | Entire rental unit in Barcelona, Spain
  [132] Barcelona  | None       5n | ★4.84 (422) | Fav:1 SH:Yes | 38 amens | Entire rental unit in Barcelona, Spain
  [133] Barcelona  | None       5n | ★5 (1) | Fav:0 SH:Yes | 31 amens | Entire rental unit in Barcelona, Spain
  [134] Barcelona  | None       5n | ★4.45 (452) | Fav:0 SH:No  | 31 amens | Entire rental unit in Barcelona, Spain
  [135] Barcelona  | None       5n | ★4.96 (229) | Fav:1 SH:Yes | 39 amens | Entire rental unit in Barcelona, Spain
  [136] Barcelona  | None       5n | ★4.85 (469) | Fav:1 SH:Yes | 40 amens | Entire serviced apartment in Barcelona, Spain
  [137] Barcelona  | None       5n | ★4.63 (429) | Fav:0 SH:No  | 40 amens | Entire serviced apartment in Barcelona, Spain
  page has 18 card URLs (city progress 37/50)
  [138] Barcelona  | None       5n | ★4.95 (463) | Fav:1 SH:Yes | 39 amens | Entire rental unit in Barcelona, Spain
  [139] Barcelona  | None       5n | ★5 (25) | Fav:1 SH:No  | 13 amens | Entire rental unit in L'Hospitalet de Llobregat, Spain
  [140] Barcelona  | None       5n | ★4.93 (42) | Fav:0 SH:No  | 31 amens | Entire rental unit in Barcelona, Spain
  [141] Barcelona  | None       5n | ★4.49 (473) | Fav:0 SH:Yes | 51 amens | Entire rental unit in Barcelona, Spain
  [142] Barcelona  | None       5n | ★4.78 (487) | Fav:0 SH:No  | 31 amens | Rental unit in Barcelona, Spain
  [143] Barcelona  | None       5n | ★None (None) | Fav:0 SH:No  | None amens | None
  [144] Barcelona  | None       5n | ★4.86 (3226) | Fav:0 SH:Yes | 30 amens | Rental unit in Barcelona, Spain
  [145] Barcelona  | None       5n | ★4.9 (116) | Fav:1 SH:Yes | 45 amens | Entire rental unit in Barcelona, Spain
  [146] Barcelona  | None       5n | ★4.94 (97) | Fav:1 SH:Yes | 59 amens | Entire vacation home in Barcelona, Spain
  [147] Barcelona  | None       5n | ★4.84 (318) | Fav:1 SH:Yes | 35 amens | Entire rental unit in Barcelona, Spain
  [148] Barcelona  | None       5n | ★4.86 (543) | Fav:1 SH:Yes | 32 amens | Entire rental unit in Barcelona, Spain
  [149] Barcelona  | None       5n | ★4.87 (195) | Fav:1 SH:Yes | 45 amens | Entire rental unit in Barcelona, Spain
  [150] Barcelona  | None       5n | ★4.72 (1939) | Fav:0 SH:No  | 28 amens | Rental unit in Barcelona, Spain
        …checkpoint saved (150 rows)
  → collected 50 listings in Barcelona
  → running total: 150

========================================================================
=== CITY 4/10: Berlin ===
========================================================================
  page has 1 card URLs (city progress 0/50)
  [151] Berlin     | None       5n | ★4.84 (1125) | Fav:0 SH:Yes | 59 amens | Entire serviced apartment in Berlin, Germany
  page has 18 card URLs (city progress 1/50)
  [152] Berlin     | None       5n | ★5 (17) | Fav:1 SH:Yes | 56 amens | Entire rental unit in Berlin, Germany
  [153] Berlin     | None       5n | ★4.93 (182) | Fav:1 SH:Yes | 49 amens | Entire rental unit in Berlin, Germany
  [154] Berlin     | None       5n | ★4.79 (146) | Fav:0 SH:Yes | 35 amens | Entire rental unit in Berlin, Germany
  [155] Berlin     | None       5n | ★4.78 (289) | Fav:0 SH:No  | 65 amens | Entire rental unit in Berlin, Germany
  [156] Berlin     | None       5n | ★4.84 (95) | Fav:0 SH:Yes | 58 amens | Entire rental unit in Berlin, Germany
  [157] Berlin     | None       5n | ★4.87 (422) | Fav:1 SH:Yes | 29 amens | Entire rental unit in Berlin, Germany
  [158] Berlin     | None       5n | ★5 (8) | Fav:1 SH:No  | 46 amens | Entire rental unit in Berlin, Germany
  [159] Berlin     | None       5n | ★4.9 (107) | Fav:1 SH:Yes | 30 amens | Entire rental unit in Berlin, Germany
  [160] Berlin     | None       5n | ★4.97 (184) | Fav:1 SH:Yes | 58 amens | Entire condo in Berlin, Germany

In [ ]:
# =====================================================
#  FILL PRICES IN EXISTING CSV
#  Reads airbnb_listings.csv → visits every URL →
#  extracts Price / PricePerNightEst / CleaningFee /
#  ServiceFee / Taxes → writes airbnb_listings_priced.csv
# =====================================================
import re, json, time, random
from datetime import datetime
from urllib.parse import urlparse, parse_qs

import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from seleniumbase import Driver

# ---------------- CONFIG ----------------
INPUT_CSV        = "/content/airbnb_listings.csv"
OUTPUT_CSV       = "/content/airbnb_listings_priced.csv"
FORCE_REFETCH    = False          # True → re-scrape rows that already have a Price
CHECKPOINT_EVERY = 25
SLEEP_BETWEEN    = (1.5, 3.0)     # polite delay between page loads
HEADLESS         = True

# ---------------- HELPERS ----------------
def safe_get(d, path, default=None):
    cur = d
    for p in path:
        if isinstance(cur, dict):
            cur = cur.get(p)
        elif isinstance(cur, list) and isinstance(p, int) and 0 <= p < len(cur):
            cur = cur[p]
        else:
            return default
        if cur is None:
            return default
    return cur

def parse_money(s):
    if s is None: return None
    s = re.sub(r"[^\d,\.]", "", str(s))
    if not s: return None
    # If both . and , present → . is decimal, , is thousands
    if "." in s and "," in s:
        s = s.replace(",", "")
    else:
        s = s.replace(",", "")
    try:
        return float(s)
    except ValueError:
        return None

def nights_from_url(url):
    q = parse_qs(urlparse(url).query)
    ci, co = q.get("check_in", [None])[0], q.get("check_out", [None])[0]
    if ci and co:
        try:
            return (datetime.strptime(co, "%Y-%m-%d")
                    - datetime.strptime(ci, "%Y-%m-%d")).days
        except Exception:
            return None
    return None

def get_deferred_state(driver):
    try:
        el  = driver.find_element(By.ID, "data-deferred-state-0")
        txt = el.get_attribute("textContent") or el.get_attribute("innerHTML")
        return json.loads(txt)
    except Exception:
        return None

def get_json_ld(driver):
    out = []
    try:
        for s in driver.find_elements(By.CSS_SELECTOR,
                                      'script[type="application/ld+json"]'):
            try:    out.append(json.loads(s.get_attribute("textContent")))
            except Exception: pass
    except Exception: pass
    return out

# ---------------- PRICE EXTRACTORS ----------------
def price_from_ld(ld_list):
    """VacationRental JSON-LD usually carries offers[].price."""
    for obj in ld_list:
        if obj.get("@type") == "VacationRental":
            offers = obj.get("offers") or []
            if isinstance(offers, dict):
                offers = [offers]
            for o in offers:
                p = o.get("price")
                if p is not None:
                    try:
                        v = float(p)
                        if v > 0: return v
                    except Exception:
                        pass
    return None

def price_from_state(state):
    """
    Robust extraction from the data-deferred-state-0 JSON.
    Returns dict: Price, CleaningFee, ServiceFee, Taxes.
    """
    out = {"Price": None, "CleaningFee": None, "ServiceFee": None, "Taxes": None}
    if not state:
        return out

    node = None
    for key, payload in (state.get("niobeClientData") or []):
        if isinstance(key, str) and key.startswith("StaysPdpSections"):
            node = safe_get(payload, ["data", "node"]); break
    if node is None:
        node = safe_get(state, ["niobeClientData", 0, 1, "data", "node"])
    if not node:
        return out

    pdp = node.get("pdpPresentation") or {}

    # ---- 1. Structured paths (most common today) ----
    structured_paths = [
        ["structuredDisplayPrice", "primaryLine", "price"],
        ["structuredDisplayPrice", "primaryLine", "discountedPrice"],
        ["structuredDisplayPrice", "secondaryLine", "price"],
        ["bookIt", "priceBreakdown", "total"],
        ["booking", "priceBreakdown", "total"],
        ["pricing", "priceBreakdown", "total"],
        ["pricing", "primaryPrice"],
    ]
    for prefix in (node, pdp):
        for path in structured_paths:
            val = safe_get(prefix, path)
            if isinstance(val, dict):
                amt = (val.get("amount")
                       or val.get("unformattedValue")
                       or val.get("value"))
                if isinstance(amt, (int, float)) and amt > 0:
                    out["Price"] = float(amt); break
            elif isinstance(val, (int, float)) and val > 0:
                out["Price"] = float(val); break
        if out["Price"]:
            break

    # ---- 2. Recursive scan as fallback ----
    if out["Price"] is None:
        hits = []
        def walk(o, p=""):
            if isinstance(o, dict):
                for k, v in o.items():
                    kl = k.lower()
                    if kl in ("amount", "unformattedvalue", "value", "total") \
                       and isinstance(v, (int, float)) and v > 0:
                        pl = (p + "." + k).lower()
                        if any(w in pl for w in
                               ("price", "pricing", "total", "cost", "breakdown")):
                            # skip fee-like paths
                            if not any(f in pl for f in
                                       ("cleaning", "servicefee",
                                        "service_fee", "tax", "nightly",
                                        "pernight", "per_night", "monthly")):
                                hits.append((p + "." + k, v))
                    walk(v, p + "." + k)
            elif isinstance(o, list):
                for i, v in enumerate(o):
                    walk(v, f"{p}[{i}]")
        walk(node, "node")
        if hits:
            # Prefer the largest 'total' candidate
            totals = [h for h in hits if "total" in h[0].lower()]
            pool = totals or hits
            out["Price"] = max(pool, key=lambda x: x[1])[1]

    # ---- 3. Fee line items ----
    for path in (
        ["pricing", "priceBreakdown", "lineItems"],
        ["booking", "priceBreakdown", "lineItems"],
        ["bookIt", "priceBreakdown", "lineItems"],
    ):
        items = safe_get(node, path) or safe_get(pdp, path) or []
        for it in items:
            label = ((it.get("localizedTitle") or "") + " " +
                     (it.get("title") or "")).lower()
            amt = (safe_get(it, ["price", "amount"])
                   or safe_get(it, ["price", "unformattedValue"])
                   or it.get("amount"))
            if not isinstance(amt, (int, float)):
                continue
            if "clean" in label and out["CleaningFee"] is None:
                out["CleaningFee"] = float(amt)
            elif "service" in label and "fee" in label and out["ServiceFee"] is None:
                out["ServiceFee"] = float(amt)
            elif "tax" in label and out["Taxes"] is None:
                out["Taxes"] = float(amt)
        if any(out[k] is not None for k in ("CleaningFee","ServiceFee","Taxes")):
            break

    return out

def price_from_dom(driver, nights):
    """Currency-agnostic body-text fallback."""
    out = {"Price": None, "CleaningFee": None, "ServiceFee": None, "Taxes": None}
    try:
        body = driver.find_element(By.TAG_NAME, "body").text
    except Exception:
        return out

    # 1) total price
    for pat in (
        r"(?:total)\s*:?\s*([€$£¥]\s*[\d.,]+)",
        r"([€$£¥]\s*[\d.,]+)\s*(?:total|grand\s*total)",
        r"([€$£¥]\s*[\d.,]+)\s*for\s*\d+\s*nights?",
        r"for\s*\d+\s*nights?[^\n€$£¥]{0,30}([€$£¥]\s*[\d.,]+)",
    ):
        m = re.search(pat, body, re.IGNORECASE)
        if m:
            p = parse_money(m.group(1))
            if p and p > 0:
                out["Price"] = p
                break

    # 2) per-night × nights fallback
    if out["Price"] is None and nights:
        m = re.search(r"([€$£¥]\s*[\d.,]+)\s*(?:/|per\s+)night",
                      body, re.IGNORECASE)
        if m:
            pn = parse_money(m.group(1))
            if pn:
                out["Price"] = round(pn * nights, 2)

    # 3) fees
    for lbl, key in (
        ("cleaning fee",       "CleaningFee"),
        ("airbnb service fee", "ServiceFee"),
        ("service fee",        "ServiceFee"),
        ("taxes",              "Taxes"),
        ("tax",                "Taxes"),
    ):
        if out[key] is not None:
            continue
        m = re.search(rf"{re.escape(lbl)}[^\d\n€$£¥]{{0,25}}"
                      rf"([€$£¥]?\s*[\d.,]+)", body, re.IGNORECASE)
        if m:
            v = parse_money(m.group(1))
            if v: out[key] = v

    return out

# ---------------- MAIN ----------------
def has_price(row):
    p = row.get("Price")
    if p is None: return False
    try:
        if pd.isna(p): return False
        return float(p) > 0
    except Exception:
        return False

def main():
    df = pd.read_csv(INPUT_CSV, encoding="utf-8-sig")

    # Guarantee the columns exist
    for c in ("Price", "PricePerNightEst", "CleaningFee",
              "ServiceFee", "Taxes", "Nights"):
        if c not in df.columns:
            df[c] = None

    total = len(df)
    todo = [i for i, r in df.iterrows()
            if FORCE_REFETCH or not has_price(r)]
    print(f"Total rows: {total} | Rows to fetch: {len(todo)}\n")

    driver = Driver(browser="chrome", headless=HEADLESS)
    driver.set_window_size(1920, 1080)
    wait = WebDriverWait(driver, 10)

    try:
        for n, i in enumerate(todo, 1):
            url = df.at[i, "URL"]
            if not isinstance(url, str) or "airbnb" not in url:
                print(f"[{n}/{len(todo)}] row {i}: no URL, skip")
                continue

            nights = df.at[i, "Nights"]
            if pd.isna(nights) or not nights:
                nights = nights_from_url(url)
                df.at[i, "Nights"] = nights

            try:
                driver.get(url)
                wait.until(EC.presence_of_element_located((By.TAG_NAME, "h1")))
                # Let deferred-state settle
                try:
                    WebDriverWait(driver, 6).until(
                        EC.presence_of_element_located(
                            (By.ID, "data-deferred-state-0")))
                except Exception:
                    pass
                time.sleep(random.uniform(*SLEEP_BETWEEN))

                state = get_deferred_state(driver)
                ld    = get_json_ld(driver)

                data = price_from_state(state)

                # JSON-LD fallback
                if not data["Price"]:
                    p = price_from_ld(ld)
                    if p: data["Price"] = p

                # DOM fallback (also fills fees if state missed them)
                if (not data["Price"]) or any(
                    data[k] is None for k in
                    ("CleaningFee", "ServiceFee", "Taxes")):
                    dom = price_from_dom(driver, nights)
                    for k, v in dom.items():
                        if not data.get(k) and v:
                            data[k] = v

                # Write back
                df.at[i, "Price"] = data["Price"]
                df.at[i, "CleaningFee"] = data["CleaningFee"]
                df.at[i, "ServiceFee"]  = data["ServiceFee"]
                df.at[i, "Taxes"]       = data["Taxes"]
                if data["Price"] and nights:
                    df.at[i, "PricePerNightEst"] = round(
                        data["Price"] / nights, 2)

                city = df.at[i, "city"] if "city" in df.columns else "?"
                pn   = df.at[i, "PricePerNightEst"]
                print(f"[{n}/{len(todo)}] row {i:>3} | {city:<12} | "
                      f"Price={data['Price']} | {nights}n | PN={pn}")

                if n % CHECKPOINT_EVERY == 0:
                    df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")
                    print(f"   ↳ checkpoint saved ({n}/{len(todo)})")

            except Exception as e:
                print(f"[{n}/{len(todo)}] row {i}: "
                      f"{type(e).__name__}: {str(e)[:90]}")
                continue
    finally:
        try: driver.quit()
        except Exception: pass
        df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")
        filled = df["Price"].notna().sum()
        print(f"\nDONE → {OUTPUT_CSV}")
        print(f"Rows with Price: {filled}/{total} "
              f"({filled/total*100:.1f}%)")
        print(f"Rows with CleaningFee: {df['CleaningFee'].notna().sum()}")
        print(f"Rows with ServiceFee:  {df['ServiceFee'].notna().sum()}")
        print(f"Rows with Taxes:       {df['Taxes'].notna().sum()}")

if __name__ == "__main__":
    main()

Total rows: 500 | Rows to fetch: 500

[1/500] row   0 | Amsterdam    | Price=1204.0 | 5n | PN=240.8
[2/500] row   1 | Amsterdam    | Price=None | 5n | PN=nan
[3/500] row   2 | Amsterdam    | Price=1900.0 | 5n | PN=380.0
[4/500] row   3 | Amsterdam    | Price=1497.0 | 5n | PN=299.4
[5/500] row   4 | Amsterdam    | Price=1017.0 | 5n | PN=203.4
[6/500] row   5 | Amsterdam    | Price=1310.0 | 5n | PN=262.0
[7/500] row   6 | Amsterdam    | Price=1017.0 | 5n | PN=203.4
[8/500] row   7 | Amsterdam    | Price=1052.0 | 5n | PN=210.4
[9/500] row   8 | Amsterdam    | Price=1955.0 | 5n | PN=391.0
[10/500] row   9 | Amsterdam    | Price=1874.0 | 5n | PN=374.8
[11/500] row  10 | Amsterdam    | Price=1403.0 | 5n | PN=280.6
[12/500] row  11 | Amsterdam    | Price=1744.0 | 5n | PN=348.8
[13/500] row  12 | Amsterdam    | Price=1500.0 | 5n | PN=300.0
[14/500] row  13 | Amsterdam    | Price=2352.0 | 5n | PN=470.4
[15/500] row  14 | Amsterdam    | Price=None | 5n | PN=nan
[16/500] row  15 | Amsterdam    | Price=2478.0 | 5n | PN=495.6
[17/500] row  16 | Amsterdam    | Price=2408.0 | 5n | PN=481.6
[18/500] row  17 | Amsterdam    | Price=484.0 | 5n | PN=96.8
[19/500] row  18 | Amsterdam    | Price=2654.0 | 5n | PN=530.8
[20/500] row  19 | Amsterdam    | Price=1257.0 | 5n | PN=251.4
[21/500] row  20 | Amsterdam    | Price=None | 5n | PN=nan
[22/500] row  21 | Amsterdam    | Price=2208.0 | 5n | PN=441.6
[23/500] row  22 | Amsterdam    | Price=1182.0 | 5n | PN=236.4
[24/500] row  23 | Amsterdam    | Price=753.0 | 5n | PN=150.6
[25/500] row  24 | Amsterdam    | Price=979.0 | 5n | PN=195.8
   ↳ checkpoint saved (25/500)
[26/500] row  25 | Amsterdam    | Price=1165.0 | 5n | PN=233.0
[27/500] row  26 | Amsterdam    | Price=922.0 | 5n | PN=184.4
[28/500] row  27 | Amsterdam    | Price=1364.0 | 5n | PN=272.8
[29/500] row  28 | Amsterdam    | Price=4155.0 | 5n | PN=831.0
[30/500] row  29 | Amsterdam    | Price=1499.0 | 5n | PN=299.8
[31/500] row  30 | Amsterdam    | Price=750.0 | 5n | PN=150.0
[32/500] row  31 | Amsterdam    | Price=1349.0 | 5n | PN=269.8
[33/500] row  32 | Amsterdam    | Price=2626.0 | 5n | PN=525.2
[34/500] row  33 | Amsterdam    | Price=1023.0 | 5n | PN=204.6
[35/500] row  34 | Amsterdam    | Price=648.0 | 5n | PN=129.6
[36/500] row  35 | Amsterdam    | Price=2563.0 | 5n | PN=512.6
[37/500] row  36 | Amsterdam    | Price=1420.0 | 5n | PN=284.0
[38/500] row  37 | Amsterdam    | Price=1496.0 | 5n | PN=299.2
[39/500] row  38 | Amsterdam    | Price=None | 5n | PN=nan
[40/500] row  39 | Amsterdam    | Price=2610.0 | 5n | PN=522.0
[41/500] row  40 | Amsterdam    | Price=1100.0 | 5n | PN=220.0
[42/500] row  41 | Amsterdam    | Price=2232.0 | 5n | PN=446.4
[43/500] row  42 | Amsterdam    | Price=None | 5n | PN=nan
[44/500] row  43 | Amsterdam    | Price=2532.0 | 5n | PN=506.4
[45/500] row  44 | Amsterdam    | Price=1130.0 | 5n | PN=226.0
[46/500] row  45 | Amsterdam    | Price=976.0 | 5n | PN=195.2
[47/500] row  46 | Amsterdam    | Price=810.0 | 5n | PN=162.0
[48/500] row  47 | Amsterdam    | Price=1610.0 | 5n | PN=322.0
[49/500] row  48 | Amsterdam    | Price=1051.0 | 5n | PN=210.2
[50/500] row  49 | Amsterdam    | Price=4399.0 | 5n | PN=879.8
   ↳ checkpoint saved (50/500)
[51/500] row  50 | Athens       | Price=847.0 | 5n | PN=169.4
[52/500] row  51 | Athens       | Price=360.0 | 5n | PN=72.0
[53/500] row  52 | Athens       | Price=594.0 | 5n | PN=118.8
[54/500] row  53 | Athens       | Price=2555.0 | 5n | PN=511.0
[55/500] row  54 | Athens       | Price=855.0 | 5n | PN=171.0
[56/500] row  55 | Athens       | Price=488.0 | 5n | PN=97.6
[57/500] row  56 | Athens       | Price=382.0 | 5n | PN=76.4
[58/500] row  57 | Athens       | Price=1181.0 | 5n | PN=236.2
[59/500] row  58 | Athens       | Price=799.0 | 5n | PN=159.8
[60/500] row  59 | Athens       | Price=1092.0 | 5n | PN=218.4
[61/500] row  60 | Athens       | Price=1890.0 | 5n | PN=378.0
[62/500] row  61 | Athens       | Price=1215.0 | 5n | PN=243.0
[63/500] row  62 | Athens       | Price=1586.0 | 5n | PN=317.2
[64/500] row  63 | Athens       | Price=665.0 | 5n | PN=133.0
[65/500] row  64 | Athens       | Price=505.0 | 5n | PN=101.0
[66/500] row  65 | Athens       | Price=605.0 | 5n | PN=121.0
[67/500] row  66 | Athens       | Price=729.0 | 5n | PN=145.8
[68/500] row  67 | Athens       | Price=651.0 | 5n | PN=130.2
[69/500] row  68 | Athens       | Price=862.0 | 5n | PN=172.4
[70/500] row  69 | Athens       | Price=1078.0 | 5n | PN=215.6
[71/500] row  70 | Athens       | Price=756.0 | 5n | PN=151.2
[72/500] row  71 | Athens       | Price=359.0 | 5n | PN=71.8
[73/500] row  72 | Athens       | Price=1110.0 | 5n | PN=222.0
[74/500] row  73 | Athens       | Price=331.0 | 5n | PN=66.2
[75/500] row  74 | Athens       | Price=949.0 | 5n | PN=189.8
   ↳ checkpoint saved (75/500)
[76/500] row  75 | Athens       | Price=1415.0 | 5n | PN=283.0
[77/500] row  76 | Athens       | Price=492.0 | 5n | PN=98.4
[78/500] row  77 | Athens       | Price=1967.0 | 5n | PN=393.4
[79/500] row  78 | Athens       | Price=2645.0 | 5n | PN=529.0
[80/500] row  79 | Athens       | Price=1120.0 | 5n | PN=224.0
[81/500] row  80 | Athens       | Price=1878.0 | 5n | PN=375.6
[82/500] row  81 | Athens       | Price=2393.0 | 5n | PN=478.6
[83/500] row  82 | Athens       | Price=470.0 | 5n | PN=94.0
[84/500] row  83 | Athens       | Price=895.0 | 5n | PN=179.0
[85/500] row  84 | Athens       | Price=503.0 | 5n | PN=100.6
[86/500] row  85 | Athens       | Price=635.0 | 5n | PN=127.0
[87/500] row  86 | Athens       | Price=645.0 | 5n | PN=129.0
[88/500] row  87 | Athens       | Price=372.0 | 5n | PN=74.4
[89/500] row  88 | Athens       | Price=738.0 | 5n | PN=147.6
[90/500] row  89 | Athens       | Price=2461.0 | 5n | PN=492.2
[91/500] row  90 | Athens       | Price=862.0 | 5n | PN=172.4
[92/500] row  91 | Athens       | Price=565.0 | 5n | PN=113.0
[93/500] row  92 | Athens       | Price=2235.0 | 5n | PN=447.0
[94/500] row  93 | Athens       | Price=495.0 | 5n | PN=99.0
[95/500] row  94 | Athens       | Price=344.0 | 5n | PN=68.8
[96/500] row  95 | Athens       | Price=851.0 | 5n | PN=170.2
[97/500] row  96 | Athens       | Price=373.0 | 5n | PN=74.6
[98/500] row  97 | Athens       | Price=372.0 | 5n | PN=74.4
[99/500] row  98 | Athens       | Price=1120.0 | 5n | PN=224.0
[100/500] row  99 | Athens       | Price=831.0 | 5n | PN=166.2
   ↳ checkpoint saved (100/500)
[101/500] row 100 | Barcelona    | Price=715.0 | 5n | PN=143.0
[102/500] row 101 | Barcelona    | Price=1421.0 | 5n | PN=284.2
[103/500] row 102 | Barcelona    | Price=1715.0 | 5n | PN=343.0
[104/500] row 103 | Barcelona    | Price=2275.0 | 5n | PN=455.0
[105/500] row 104 | Barcelona    | Price=1087.0 | 5n | PN=217.4
[106/500] row 105 | Barcelona    | Price=1476.0 | 5n | PN=295.2
[107/500] row 106 | Barcelona    | Price=1075.0 | 5n | PN=215.0
[108/500] row 107 | Barcelona    | Price=1565.0 | 5n | PN=313.0
[109/500] row 108 | Barcelona    | Price=1699.0 | 5n | PN=339.8
[110/500] row 109 | Barcelona    | Price=1170.0 | 5n | PN=234.0
[111/500] row 110 | Barcelona    | Price=1210.0 | 5n | PN=242.0
[112/500] row 111 | Barcelona    | Price=1653.0 | 5n | PN=330.6
[113/500] row 112 | Barcelona    | Price=840.0 | 5n | PN=168.0
[114/500] row 113 | Barcelona    | Price=959.0 | 5n | PN=191.8
[115/500] row 114 | Barcelona    | Price=650.0 | 5n | PN=130.0
[116/500] row 115 | Barcelona    | Price=1123.0 | 5n | PN=224.6
[117/500] row 116 | Barcelona    | Price=1683.0 | 5n | PN=336.6
[118/500] row 117 | Barcelona    | Price=895.0 | 5n | PN=179.0
[119/500] row 118 | Barcelona    | Price=1369.0 | 5n | PN=273.8
[120/500] row 119 | Barcelona    | Price=763.0 | 5n | PN=152.6
[121/500] row 120 | Barcelona    | Price=1340.0 | 5n | PN=268.0
[122/500] row 121 | Barcelona    | Price=1500.0 | 5n | PN=300.0
[123/500] row 122 | Barcelona    | Price=1346.0 | 5n | PN=269.2
[124/500] row 123 | Barcelona    | Price=1075.0 | 5n | PN=215.0
[125/500] row 124 | Barcelona    | Price=640.0 | 5n | PN=128.0
   ↳ checkpoint saved (125/500)
[126/500] row 125 | Barcelona    | Price=716.0 | 5n | PN=143.2
[127/500] row 126 | Barcelona    | Price=616.0 | 5n | PN=123.2
[128/500] row 127 | Barcelona    | Price=1260.0 | 5n | PN=252.0
[129/500] row 128 | Barcelona    | Price=2245.0 | 5n | PN=449.0
[130/500] row 129 | Barcelona    | Price=1187.0 | 5n | PN=237.4
[131/500] row 130 | Barcelona    | Price=1480.0 | 5n | PN=296.0
[132/500] row 131 | Barcelona    | Price=737.0 | 5n | PN=147.4
[133/500] row 132 | Barcelona    | Price=1076.0 | 5n | PN=215.2
[134/500] row 133 | Barcelona    | Price=550.0 | 5n | PN=110.0
[135/500] row 134 | Barcelona    | Price=908.0 | 5n | PN=181.6
[136/500] row 135 | Barcelona    | Price=1265.0 | 5n | PN=253.0
[137/500] row 136 | Barcelona    | Price=1198.0 | 5n | PN=239.6
[138/500] row 137 | Barcelona    | Price=1140.0 | 5n | PN=228.0
[139/500] row 138 | Barcelona    | Price=916.0 | 5n | PN=183.2
[140/500] row 139 | Barcelona    | Price=640.0 | 5n | PN=128.0
[141/500] row 140 | Barcelona    | Price=749.0 | 5n | PN=149.8
[142/500] row 141 | Barcelona    | Price=751.0 | 5n | PN=150.2
[143/500] row 142 | Barcelona    | Price=851.0 | 5n | PN=170.2
[144/500] row 143 | Barcelona    | Price=685.0 | 5n | PN=137.0
[145/500] row 144 | Barcelona    | Price=1330.0 | 5n | PN=266.0
[146/500] row 145 | Barcelona    | Price=1253.0 | 5n | PN=250.6
[147/500] row 146 | Barcelona    | Price=829.0 | 5n | PN=165.8
[148/500] row 147 | Barcelona    | Price=1779.0 | 5n | PN=355.8
[149/500] row 148 | Barcelona    | Price=770.0 | 5n | PN=154.0
[150/500] row 149 | Barcelona    | Price=973.0 | 5n | PN=194.6
   ↳ checkpoint saved (150/500)
[151/500] row 150 | Berlin       | Price=1092.0 | 5n | PN=218.4
[152/500] row 151 | Berlin       | Price=907.0 | 5n | PN=181.4
[153/500] row 152 | Berlin       | Price=824.0 | 5n | PN=164.8
[154/500] row 153 | Berlin       | Price=648.0 | 5n | PN=129.6
[155/500] row 154 | Berlin       | Price=1205.0 | 5n | PN=241.0
[156/500] row 155 | Berlin       | Price=1123.0 | 5n | PN=224.6
[157/500] row 156 | Berlin       | Price=1114.0 | 5n | PN=222.8
[158/500] row 157 | Berlin       | Price=1973.0 | 5n | PN=394.6
[159/500] row 158 | Berlin       | Price=1308.0 | 5n | PN=261.6
[160/500] row 159 | Berlin       | Price=858.0 | 5n | PN=171.6
[161/500] row 160 | Berlin       | Price=835.0 | 5n | PN=167.0
[162/500] row 161 | Berlin       | Price=1063.0 | 5n | PN=212.6
[163/500] row 162 | Berlin       | Price=1019.0 | 5n | PN=203.8
[164/500] row 163 | Berlin       | Price=800.0 | 5n | PN=160.0
[165/500] row 164 | Berlin       | Price=617.0 | 5n | PN=123.4
[166/500] row 165 | Berlin       | Price=814.0 | 5n | PN=162.8
[167/500] row 166 | Berlin       | Price=510.0 | 5n | PN=102.0
[168/500] row 167 | Berlin       | Price=1159.0 | 5n | PN=231.8
[169/500] row 168 | Berlin       | Price=1073.0 | 5n | PN=214.6
[170/500] row 169 | Berlin       | Price=560.0 | 5n | PN=112.0
[171/500] row 170 | Berlin       | Price=770.0 | 5n | PN=154.0
[172/500] row 171 | Berlin       | Price=1528.0 | 5n | PN=305.6
[173/500] row 172 | Berlin       | Price=890.0 | 5n | PN=178.0
[174/500] row 173 | Berlin       | Price=739.0 | 5n | PN=147.8
[175/500] row 174 | Berlin       | Price=609.0 | 5n | PN=121.8
   ↳ checkpoint saved (175/500)
[176/500] row 175 | Berlin       | Price=932.0 | 5n | PN=186.4
[177/500] row 176 | Berlin       | Price=1230.0 | 5n | PN=246.0
[178/500] row 177 | Berlin       | Price=683.0 | 5n | PN=136.6
[179/500] row 178 | Berlin       | Price=424.0 | 5n | PN=84.8
[180/500] row 179 | Berlin       | Price=819.0 | 5n | PN=163.8
[181/500] row 180 | Berlin       | Price=None | 5n | PN=nan
[182/500] row 181 | Berlin       | Price=1043.0 | 5n | PN=208.6
[183/500] row 182 | Berlin       | Price=1138.0 | 5n | PN=227.6
[184/500] row 183 | Berlin       | Price=1047.0 | 5n | PN=209.4
[185/500] row 184 | Berlin       | Price=1386.0 | 5n | PN=277.2
[186/500] row 185 | Berlin       | Price=1796.0 | 5n | PN=359.2
[187/500] row 186 | Berlin       | Price=858.0 | 5n | PN=171.6
[188/500] row 187 | Berlin       | Price=732.0 | 5n | PN=146.4
[189/500] row 188 | Berlin       | Price=759.0 | 5n | PN=151.8
[190/500] row 189 | Berlin       | Price=1008.0 | 5n | PN=201.6
[191/500] row 190 | Berlin       | Price=656.0 | 5n | PN=131.2
[192/500] row 191 | Berlin       | Price=1470.0 | 5n | PN=294.0
[193/500] row 192 | Berlin       | Price=1616.0 | 5n | PN=323.2
[194/500] row 193 | Berlin       | Price=719.0 | 5n | PN=143.8
[195/500] row 194 | Berlin       | Price=852.0 | 5n | PN=170.4
[196/500] row 195 | Berlin       | Price=None | 5n | PN=nan
[197/500] row 196 | Berlin       | Price=1017.0 | 5n | PN=203.4
[198/500] row 197 | Berlin       | Price=500.0 | 5n | PN=100.0
[199/500] row 198 | Berlin       | Price=653.0 | 5n | PN=130.6
[200/500] row 199 | Berlin       | Price=967.0 | 5n | PN=193.4
   ↳ checkpoint saved (200/500)
[201/500] row 200 | Budapest     | Price=1246.0 | 5n | PN=249.2
[202/500] row 201 | Budapest     | Price=661.0 | 5n | PN=132.2
[203/500] row 202 | Budapest     | Price=621.0 | 5n | PN=124.2
[204/500] row 203 | Budapest     | Price=1315.0 | 5n | PN=263.0
[205/500] row 204 | Budapest     | Price=1004.0 | 5n | PN=200.8
[206/500] row 205 | Budapest     | Price=375.0 | 5n | PN=75.0
[207/500] row 206 | Budapest     | Price=669.0 | 5n | PN=133.8
[208/500] row 207 | Budapest     | Price=1012.0 | 5n | PN=202.4
[209/500] row 208 | Budapest     | Price=672.0 | 5n | PN=134.4
[210/500] row 209 | Budapest     | Price=522.0 | 5n | PN=104.4
[211/500] row 210 | Budapest     | Price=450.0 | 5n | PN=90.0
[212/500] row 211 | Budapest     | Price=700.0 | 5n | PN=140.0
[213/500] row 212 | Budapest     | Price=None | 5n | PN=nan
[214/500] row 213 | Budapest     | Price=877.0 | 5n | PN=175.4
[215/500] row 214 | Budapest     | Price=500.0 | 5n | PN=100.0
[216/500] row 215 | Budapest     | Price=495.0 | 5n | PN=99.0
[217/500] row 216 | Budapest     | Price=407.0 | 5n | PN=81.4
[218/500] row 217 | Budapest     | Price=347.0 | 5n | PN=69.4
[219/500] row 218 | Budapest     | Price=489.0 | 5n | PN=97.8
[220/500] row 219 | Budapest     | Price=671.0 | 5n | PN=134.2
[221/500] row 220 | Budapest     | Price=435.0 | 5n | PN=87.0
[222/500] row 221 | Budapest     | Price=1198.0 | 5n | PN=239.6
[223/500] row 222 | Budapest     | Price=750.0 | 5n | PN=150.0
[224/500] row 223 | Budapest     | Price=657.0 | 5n | PN=131.4
[225/500] row 224 | Budapest     | Price=935.0 | 5n | PN=187.0
   ↳ checkpoint saved (225/500)
[226/500] row 225 | Budapest     | Price=912.0 | 5n | PN=182.4
[227/500] row 226 | Budapest     | Price=690.0 | 5n | PN=138.0
[228/500] row 227 | Budapest     | Price=362.0 | 5n | PN=72.4
[229/500] row 228 | Budapest     | Price=749.0 | 5n | PN=149.8
[230/500] row 229 | Budapest     | Price=451.0 | 5n | PN=90.2
[231/500] row 230 | Budapest     | Price=749.0 | 5n | PN=149.8
[232/500] row 231 | Budapest     | Price=3299.0 | 5n | PN=659.8
[233/500] row 232 | Budapest     | Price=645.0 | 5n | PN=129.0
[234/500] row 233 | Budapest     | Price=1047.0 | 5n | PN=209.4
[235/500] row 234 | Budapest     | Price=552.0 | 5n | PN=110.4
[236/500] row 235 | Budapest     | Price=500.0 | 5n | PN=100.0
[237/500] row 236 | Budapest     | Price=380.0 | 5n | PN=76.0
[238/500] row 237 | Budapest     | Price=796.0 | 5n | PN=159.2
[239/500] row 238 | Budapest     | Price=549.0 | 5n | PN=109.8
[240/500] row 239 | Budapest     | Price=600.0 | 5n | PN=120.0
[241/500] row 240 | Budapest     | Price=505.0 | 5n | PN=101.0
[242/500] row 241 | Budapest     | Price=763.0 | 5n | PN=152.6
[243/500] row 242 | Budapest     | Price=762.0 | 5n | PN=152.4
[244/500] row 243 | Budapest     | Price=974.0 | 5n | PN=194.8
[245/500] row 244 | Budapest     | Price=708.0 | 5n | PN=141.6
[246/500] row 245 | Budapest     | Price=691.0 | 5n | PN=138.2
[247/500] row 246 | Budapest     | Price=None | 5n | PN=nan
[248/500] row 247 | Budapest     | Price=506.0 | 5n | PN=101.2
[249/500] row 248 | Budapest     | Price=583.0 | 5n | PN=116.6
[250/500] row 249 | Budapest     | Price=855.0 | 5n | PN=171.0
   ↳ checkpoint saved (250/500)
[251/500] row 250 | Lisbon       | Price=1163.0 | 5n | PN=232.6
[252/500] row 251 | Lisbon       | Price=780.0 | 5n | PN=156.0
[253/500] row 252 | Lisbon       | Price=674.0 | 5n | PN=134.8
[254/500] row 253 | Lisbon       | Price=1885.0 | 5n | PN=377.0
[255/500] row 254 | Lisbon       | Price=624.0 | 5n | PN=124.8
[256/500] row 255 | Lisbon       | Price=773.0 | 5n | PN=154.6
[257/500] row 256 | Lisbon       | Price=1832.0 | 5n | PN=366.4
[258/500] row 257 | Lisbon       | Price=2031.0 | 5n | PN=406.2
[259/500] row 258 | Lisbon       | Price=416.0 | 5n | PN=83.2
[260/500] row 259 | Lisbon       | Price=1672.0 | 5n | PN=334.4
[261/500] row 260 | Lisbon       | Price=612.0 | 5n | PN=122.4
[262/500] row 261 | Lisbon       | Price=1842.0 | 5n | PN=368.4
[263/500] row 262 | Lisbon       | Price=635.0 | 5n | PN=127.0
[264/500] row 263 | Lisbon       | Price=470.0 | 5n | PN=94.0
[265/500] row 264 | Lisbon       | Price=589.0 | 5n | PN=117.8
[266/500] row 265 | Lisbon       | Price=656.0 | 5n | PN=131.2
[267/500] row 266 | Lisbon       | Price=1446.0 | 5n | PN=289.2
[268/500] row 267 | Lisbon       | Price=550.0 | 5n | PN=110.0
[269/500] row 268 | Lisbon       | Price=1048.0 | 5n | PN=209.6
[270/500] row 269 | Lisbon       | Price=1106.0 | 5n | PN=221.2
[271/500] row 270 | Lisbon       | Price=739.0 | 5n | PN=147.8
[272/500] row 271 | Lisbon       | Price=785.0 | 5n | PN=157.0
[273/500] row 272 | Lisbon       | Price=807.0 | 5n | PN=161.4
[274/500] row 273 | Lisbon       | Price=616.0 | 5n | PN=123.2
[275/500] row 274 | Lisbon       | Price=746.0 | 5n | PN=149.2
   ↳ checkpoint saved (275/500)
[276/500] row 275 | Lisbon       | Price=925.0 | 5n | PN=185.0
[277/500] row 276 | Lisbon       | Price=670.0 | 5n | PN=134.0
[278/500] row 277 | Lisbon       | Price=722.0 | 5n | PN=144.4
[279/500] row 278 | Lisbon       | Price=1142.0 | 5n | PN=228.4
[280/500] row 279 | Lisbon       | Price=1075.0 | 5n | PN=215.0
[281/500] row 280 | Lisbon       | Price=430.0 | 5n | PN=86.0
[282/500] row 281 | Lisbon       | Price=2524.0 | 5n | PN=504.8
[283/500] row 282 | Lisbon       | Price=833.0 | 5n | PN=166.6
[284/500] row 283 | Lisbon       | Price=640.0 | 5n | PN=128.0
[285/500] row 284 | Lisbon       | Price=1770.0 | 5n | PN=354.0
[286/500] row 285 | Lisbon       | Price=647.0 | 5n | PN=129.4
[287/500] row 286 | Lisbon       | Price=1674.0 | 5n | PN=334.8
[288/500] row 287 | Lisbon       | Price=741.0 | 5n | PN=148.2
[289/500] row 288 | Lisbon       | Price=1097.0 | 5n | PN=219.4
[290/500] row 289 | Lisbon       | Price=650.0 | 5n | PN=130.0
[291/500] row 290 | Lisbon       | Price=440.0 | 5n | PN=88.0
[292/500] row 291 | Lisbon       | Price=901.0 | 5n | PN=180.2
[293/500] row 292 | Lisbon       | Price=720.0 | 5n | PN=144.0
[294/500] row 293 | Lisbon       | Price=1038.0 | 5n | PN=207.6
[295/500] row 294 | Lisbon       | Price=665.0 | 5n | PN=133.0
[296/500] row 295 | Lisbon       | Price=637.0 | 5n | PN=127.4
[297/500] row 296 | Lisbon       | Price=635.0 | 5n | PN=127.0
[298/500] row 297 | Lisbon       | Price=527.0 | 5n | PN=105.4
[299/500] row 298 | Lisbon       | Price=572.0 | 5n | PN=114.4
[300/500] row 299 | Lisbon       | Price=638.0 | 5n | PN=127.6
   ↳ checkpoint saved (300/500)
[301/500] row 300 | London       | Price=1597.0 | 5n | PN=319.4
[302/500] row 301 | London       | Price=1098.0 | 5n | PN=219.6
[303/500] row 302 | London       | Price=1486.0 | 5n | PN=297.2
[304/500] row 303 | London       | Price=1597.0 | 5n | PN=319.4
[305/500] row 304 | London       | Price=779.0 | 5n | PN=155.8
[306/500] row 305 | London       | Price=1089.0 | 5n | PN=217.8
[307/500] row 306 | London       | Price=810.0 | 5n | PN=162.0
[308/500] row 307 | London       | Price=1332.0 | 5n | PN=266.4
[309/500] row 308 | London       | Price=3775.0 | 5n | PN=755.0
[310/500] row 309 | London       | Price=1567.0 | 5n | PN=313.4
[311/500] row 310 | London       | Price=2265.0 | 5n | PN=453.0

In [ ]:
# =====================================================
#  AIRBNB SCRAPER  —  one row per listing
#  ~50 listings × 10 cities  ⇒  ~500 rows × 30 cols
# =====================================================
import re, json, time, random, os
from datetime import datetime
from urllib.parse import urlparse, parse_qs
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from seleniumbase import Driver

# ---------------- CONFIG ----------------
cities          = ['Amsterdam','Athens','Barcelona','Berlin','Budapest',
                   'Lisbon','London','Paris','Rome','Vienna']
TARGET_PER_CITY = 50
OUTPUT_CSV      = "/content/airbnb_listings_weekends.csv"
OUTPUT_XLSX     = "/content/airbnb_listings_weekends.xlsx"

# ---------------- HELPERS ----------------
def safe_get(d, path, default=None):
    cur = d
    for p in path:
        if isinstance(cur, dict):
            cur = cur.get(p)
        elif isinstance(cur, list) and isinstance(p, int) and 0 <= p < len(cur):
            cur = cur[p]
        else:
            return default
        if cur is None:
            return default
    return cur

def get_deferred_state(driver):
    """Airbnb stores the full PDP JSON in <script id='data-deferred-state-0'>."""
    try:
        el  = driver.find_element(By.ID, "data-deferred-state-0")
        txt = el.get_attribute("textContent") or el.get_attribute("innerHTML")
        return json.loads(txt)
    except Exception:
        return None

def get_json_ld(driver):
    out = []
    try:
        for s in driver.find_elements(By.CSS_SELECTOR,
                                      'script[type="application/ld+json"]'):
            try:    out.append(json.loads(s.get_attribute("textContent")))
            except Exception: pass
    except Exception: pass
    return out

def parse_money(s):
    if s is None: return None
    s = re.sub(r"[^\d,\.]", "", str(s))
    if not s: return None
    s = s.replace(",", "")
    try:    return float(s)
    except ValueError: return None

def nights_from_url(url):
    q  = parse_qs(urlparse(url).query)
    ci, co = q.get("check_in",[None])[0], q.get("check_out",[None])[0]
    if ci and co:
        try:
            return (datetime.strptime(co, "%Y-%m-%d")
                  - datetime.strptime(ci, "%Y-%m-%d")).days
        except Exception: return None
    return None

# ---------------- CORE EXTRACTOR ----------------
def extract_listing(driver, wait, url, city):
    row = {k: None for k in [
        "Name","PropertyType","Price","Nights","PricePerNightEst",
        "Rating","Reviews","is_fav","Superhost","HostName","HostYears","HostReviews",
        "LocationName","LocationSubtitle","Latitude","Longitude",
        "Guests","Bedrooms","Beds","Baths",
        "Amenities","AmenitiesCount","Description",
        "CleaningFee","ServiceFee","Taxes",
        "AvailableDatesCount","AvailableDates","is_new"]}
    row["city"]      = city
    row["URL"]       = url
    row["is_fav"]    = 0
    row["Superhost"] = "No"
    row["is_new"]    = False

    # --- 1) JSON-LD (cheap fallback) ---
    for obj in get_json_ld(driver):
        if obj.get("@type") == "VacationRental":
            row["Name"]         = row["Name"]         or obj.get("name")
            row["Description"]  = row["Description"]  or obj.get("description")
            row["Latitude"]     = row["Latitude"]     or obj.get("latitude")
            row["Longitude"]    = row["Longitude"]    or obj.get("longitude")
            ar = obj.get("aggregateRating") or {}
            row["Rating"]       = row["Rating"]       or ar.get("ratingValue")
            row["Reviews"]      = row["Reviews"]      or ar.get("ratingCount")
            row["LocationName"] = row["LocationName"] or (obj.get("address") or {}).get("addressLocality")

    # --- 2) Deferred-state JSON (richest) ---
    state = get_deferred_state(driver)
    node  = None
    if state:
        for key, payload in (state.get("niobeClientData") or []):
            if isinstance(key, str) and key.startswith("StaysPdpSections"):
                node = safe_get(payload, ["data", "node"]); break
        if node is None:
            node = safe_get(state, ["niobeClientData", 0, 1, "data", "node"])

    if node:
        pdp = node.get("pdpPresentation") or {}

        desc = pdp.get("description") or {}
        row["Name"] = safe_get(desc, ["title","content","localizedString"]) or row["Name"]
        long_desc   = safe_get(desc, ["longDescriptionHtml","localizedString"])
        if long_desc:
            row["Description"] = re.sub(r"<[^>]+>", " ", long_desc).strip()

        ov = pdp.get("overview") or {}
        row["PropertyType"] = ov.get("title")
        for it in (ov.get("items") or []):
            itl = it.lower()
            m   = re.search(r"\d+", it)
            if not m: continue
            n = int(m.group())
            if   "guest"   in itl: row["Guests"]   = n
            elif "bedroom" in itl: row["Bedrooms"] = n
            elif "bath"    in itl: row["Baths"]    = n
            elif "bed"     in itl: row["Beds"]     = n

        loc = pdp.get("location") or {}
        row["LocationName"]     = loc.get("locationName") or row["LocationName"]
        row["LocationSubtitle"] = loc.get("subtitle")
        row["Latitude"]         = loc.get("latitude")  or row["Latitude"]
        row["Longitude"]        = loc.get("longitude") or row["Longitude"]

        amen = pdp.get("amenities") or {}
        groups = (amen.get("seeAllAmenitiesGroups")
                  or amen.get("previewAmenitiesGroups") or [])
        amens = []
        for g in groups:
            for a in (g.get("amenities") or []):
                if a.get("available") is False: continue
                t = a.get("title")
                if t and t not in amens: amens.append(t)
        if amens:
            row["Amenities"]      = " | ".join(amens)
            row["AmenitiesCount"] = len(amens)

        q  = pdp.get("quality") or {}
        rs = safe_get(q, ["listingRatingStats","overallRatingStats"]) or {}
        if rs.get("ratingAverage") is not None: row["Rating"]  = rs.get("ratingAverage")
        if rs.get("ratingCount")   is not None: row["Reviews"] = rs.get("ratingCount")
        row["is_new"] = bool(q.get("isNewListing"))
        gf = pdp.get("contextualizedGuestFavorites") or {}
        row["is_fav"] = 1 if (gf.get("isGuestFavorite")
                              or q.get("isGuestFavorite")) else 0

        host = pdp.get("hostInfo") or {}
        pd_  = host.get("passportData") or {}
        row["HostName"]  = pd_.get("name")
        row["Superhost"] = "Yes" if pd_.get("isSuperhost") else "No"
        for st in (pd_.get("stats") or []):
            if   st.get("type") == "YEARS_HOSTING": row["HostYears"]   = st.get("value")
            elif st.get("type") == "REVIEW_COUNT":  row["HostReviews"] = st.get("value")

    # --- 3) Price + nights ---
    row["Nights"] = nights_from_url(url)
    for sel in ['div[data-testid="book-it-default"]',
                'div[data-testid="book-it-default-sidebar"]',
                'div[data-testid="book-it-hover-target"]']:
        try:
            txt = driver.find_element(By.CSS_SELECTOR, sel).text
            m   = re.search(r"([\d,\.]+)\s*for\s*(\d+)\s*nights?", txt, re.IGNORECASE)
            if m:
                row["Price"]  = parse_money(m.group(1))
                row["Nights"] = int(m.group(2))
                if row["Nights"]:
                    row["PricePerNightEst"] = round(row["Price"] / row["Nights"], 2)
                break
        except Exception:
            continue

    if row["Price"] is None:
        for xp in ["//div[@data-testid='book-it-default']//span[contains(text(),'$')]",
                   "//div[@data-testid='book-it-default-sidebar']//span[contains(text(),'$')]"]:
            try:
                t  = WebDriverWait(driver, 2).until(
                        EC.presence_of_element_located((By.XPATH, xp))).text
                mm = re.search(r"[\$€£¥]\s*([\d,\.]+)", t)
                if mm:
                    row["Price"] = parse_money(mm.group(1)); break
            except Exception:
                continue

    # --- 4) Availability (inline calendar) ---
    try:
        avail = set()
        for c in driver.find_elements(By.CSS_SELECTOR,
                                      '[data-testid^="calendar-day-"]'):
            if c.get_attribute("data-is-day-blocked") == "false":
                m = re.match(r"calendar-day-(\d{2})/(\d{2})/(\d{4})",
                             c.get_attribute("data-testid") or "")
                if m:
                    mm, dd, yy = m.groups()
                    avail.add(f"{yy}-{mm}-{dd}")
        if avail:
            row["AvailableDates"]      = ",".join(sorted(avail))
            row["AvailableDatesCount"] = len(avail)
    except Exception:
        pass

    # --- 5) Cleaning / Service fee (best-effort) ---
    try:
        clicked = False
        for txt in ("Price details", "Price breakdown", "Show price details"):
            try:
                btn = driver.find_element(
                    By.XPATH,
                    f"//button[contains(., '{txt}')] | //a[contains(., '{txt}')]")
                driver.execute_script("arguments[0].click();", btn)
                clicked = True; time.sleep(1.5); break
            except Exception:
                continue
        if clicked:
            body = driver.find_element(By.TAG_NAME, "body").text
            for lbl in ("Cleaning fee","Service fee","Airbnb service fee","Taxes"):
                m = re.search(rf"{re.escape(lbl)}[^\d\n]{{0,20}}([\d,\.]+)",
                              body, re.IGNORECASE)
                if m:
                    key = lbl.replace(" ", "")
                    row[key] = parse_money(m.group(1))
            try:
                driver.find_element(By.CSS_SELECTOR,
                                    'button[aria-label="Close"]').click()
            except Exception:
                pass
    except Exception:
        pass

    if row["Rating"] is None and row["is_new"]:
        row["Rating"] = "New"
    return row

# ---------------- MAIN LOOP ----------------
all_data1 = []

for idx, city in enumerate(cities, 1):
    print(f"\n{'='*72}\n=== CITY {idx}/{len(cities)}: {city} ===\n{'='*72}")

    URL = (
        f"https://www.airbnb.com/s/{city}/homes"
        "?refinement_paths%5B%5D=%2Fhomes"
        "&date_picker_type=calendar&search_type=filter_change"
        "&flexible_trip_lengths%5B%5D=weekend_trip"
        "&monthly_start_date=2026-02-01&monthly_length=3&monthly_end_date=2026-05-01"
        "&price_filter_input_type=2&channel=EXPLORE&price_filter_num_nights=5"
        "&min_bedrooms=2"
        "&selected_filter_order%5B%5D=min_bedrooms%3A2"
        "&selected_filter_order%5B%5D=room_types%3AEntire%20home%2Fapt"
        "&update_selected_filters=true"
        f"&query={city}&search_mode=regular_search"
        "&room_types%5B%5D=Entire%20home%2Fapt"
    )

    # SeleniumBase handles all Colab Chrome/driver pain automatically
    driver = Driver(browser="chrome", headless=True)
    driver.set_window_size(1920, 1080)
    items_scraped_this_city = 0

    try:
        driver.get(URL)
        wait = WebDriverWait(driver, 8)

        while items_scraped_this_city < TARGET_PER_CITY:
            try:
                wait.until(EC.presence_of_all_elements_located(
                    (By.CSS_SELECTOR, "div[data-testid='card-container']")))
            except Exception:
                print("  [warn] no cards found, ending this city")
                break

            listings = driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='card-container']")
            listing_urls = []
            for l in listings:
                try:
                    u = l.find_element(By.TAG_NAME, "a").get_attribute("href")
                    if u and "/rooms/" in u and u not in listing_urls:
                        listing_urls.append(u)
                except Exception:
                    continue

            print(f"  page has {len(listing_urls)} card URLs "
                  f"(city progress {items_scraped_this_city}/{TARGET_PER_CITY})")

            main_window = driver.current_window_handle

            for url in listing_urls:
                if items_scraped_this_city >= TARGET_PER_CITY:
                    break
                try:
                    driver.execute_script(f"window.open('{url}', '_blank');")
                    driver.switch_to.window(driver.window_handles[-1])
                    wait.until(EC.presence_of_element_located((By.TAG_NAME, "h1")))
                    time.sleep(1.5)     # let deferred-state JSON settle

                    row = extract_listing(driver, wait, url, city)
                    all_data1.append(row)
                    items_scraped_this_city += 1

                    print(f"  [{len(all_data1):>3}] {row['city']:<10} "
                          f"| {str(row['Price']):<10} {row['Nights']}n "
                          f"| ★{row['Rating']} ({row['Reviews']}) "
                          f"| Fav:{row['is_fav']} SH:{row['Superhost']:<3} "
                          f"| {row['AmenitiesCount']} amens "
                          f"| {row['PropertyType']}")

                    # checkpoint save every 25 rows
                    if len(all_data1) % 25 == 0:
                        pd.DataFrame(all_data1).to_csv(
                            OUTPUT_CSV, index=False, encoding="utf-8-sig")
                        print(f"        …checkpoint saved ({len(all_data1)} rows)")

                    time.sleep(random.uniform(1.0, 2.0))
                    driver.close()
                    driver.switch_to.window(main_window)

                except Exception as e:
                    print(f"  [skip] {type(e).__name__}: {str(e)[:80]}")
                    if len(driver.window_handles) > 1:
                        driver.close()
                        driver.switch_to.window(main_window)
                    continue

            # paginate to next result page
            if items_scraped_this_city < TARGET_PER_CITY:
                try:
                    next_btn = driver.find_element(
                        By.CSS_SELECTOR, "a[aria-label='Next']")
                    driver.execute_script("arguments[0].click();", next_btn)
                    time.sleep(4)
                except Exception:
                    print("  [warn] no next page — city done")
                    break

    finally:
        try:    driver.quit()
        except Exception: pass
        print(f"  → collected {items_scraped_this_city} listings in {city}")
        print(f"  → running total: {len(all_data1)}")

# ---------------- SAVE ----------------
print(f"\n{'='*72}\nDONE — {len(all_data1)} listings total\n{'='*72}")

df = pd.DataFrame(all_data1)
df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")
print(f"Saved: {OUTPUT_CSV}")

try:
    df.to_excel(OUTPUT_XLSX, index=False)
    print(f"Saved: {OUTPUT_XLSX}")
except Exception as e:
    print(f"(xlsx skipped: {e})")

print("\nListings per city:")
print(df.groupby("city").size().to_string())

print("\nColumns:", list(df.columns))
print("\nFirst 3 rows:")
print(df.head(3).to_string())

========================================================================
=== CITY 1/10: Amsterdam ===
========================================================================
  page has 1 card URLs (city progress 0/50)
  [  1] Amsterdam  | None       2n | ★4.67 (3) | Fav:0 SH:Yes | 45 amens | Entire bungalow in Vijfhuizen, Netherlands
  page has 18 card URLs (city progress 1/50)
  [  2] Amsterdam  | None       2n | ★4.85 (763) | Fav:1 SH:Yes | 47 amens | Entire serviced apartment in Amsterdam, Netherlands
  [  3] Amsterdam  | None       2n | ★4.35 (26) | Fav:0 SH:No  | 45 amens | Entire serviced apartment in Amsterdam, Netherlands
  [  4] Amsterdam  | None       2n | ★4.86 (310) | Fav:1 SH:Yes | 39 amens | Entire rental unit in Amsterdam, Netherlands
  [  5] Amsterdam  | None       2n | ★5 (3) | Fav:0 SH:Yes | 45 amens | Entire chalet in Vijfhuizen, Netherlands
  [  6] Amsterdam  | None       2n | ★4.7 (325) | Fav:0 SH:No  | 43 amens | Entire serviced apartment in Amsterdam, Netherlands
  [  7] Amsterdam  | None       2n | ★4.99 (90) | Fav:1 SH:Yes | 34 amens | Houseboat in Amsterdam, Netherlands
  [  8] Amsterdam  | None       2n | ★4.86 (242) | Fav:1 SH:Yes | 61 amens | Entire villa in Zwanenburg-Dijk, Netherlands
  [  9] Amsterdam  | None       2n | ★4.7 (269) | Fav:0 SH:Yes | 33 amens | Entire rental unit in Amsterdam, Netherlands
  [ 10] Amsterdam  | None       2n | ★4.97 (473) | Fav:1 SH:Yes | 58 amens | Entire condo in Amsterdam, Netherlands
  [ 11] Amsterdam  | None       2n | ★4.94 (160) | Fav:1 SH:Yes | 18 amens | Entire cabin in Amsterdam, Netherlands
  [ 12] Amsterdam  | None       2n | ★4.83 (52) | Fav:0 SH:Yes | 2 amens | Entire rental unit in Amsterdam, Netherlands
  [ 13] Amsterdam  | None       2n | ★4.97 (161) | Fav:1 SH:Yes | 31 amens | Entire rental unit in Amsterdam, Netherlands
  [ 14] Amsterdam  | None       2n | ★4.9 (875) | Fav:1 SH:Yes | 55 amens | Entire home in Zaandam, Netherlands
  [ 15] Amsterdam  | None       2n | ★5 (24) | Fav:1 SH:Yes | 41 amens | Entire loft in Amsterdam, Netherlands
  [ 16] Amsterdam  | None       2n | ★4.86 (380) | Fav:1 SH:Yes | 54 amens | Entire condo in Amsterdam, Netherlands
  [ 17] Amsterdam  | None       2n | ★4.78 (32) | Fav:0 SH:No  | 43 amens | Entire serviced apartment in Amsterdam, Netherlands
  [ 18] Amsterdam  | None       2n | ★4.89 (122) | Fav:1 SH:No  | 52 amens | Entire home in Amsterdam, Netherlands
  [ 19] Amsterdam  | None       2n | ★4.52 (67) | Fav:0 SH:No  | 43 amens | Entire serviced apartment in Amsterdam, Netherlands
  page has 18 card URLs (city progress 19/50)
  [ 20] Amsterdam  | None       2n | ★4.52 (687) | Fav:0 SH:No  | 25 amens | Entire rental unit in Amsterdam, Netherlands
  [ 21] Amsterdam  | None       2n | ★4.92 (24) | Fav:0 SH:Yes | 67 amens | Entire rental unit in Amsterdam, Netherlands
  [ 22] Amsterdam  | None       2n | ★4.98 (243) | Fav:1 SH:Yes | 58 amens | Entire condo in Amsterdam, Netherlands
  [ 23] Amsterdam  | None       2n | ★4.94 (117) | Fav:1 SH:Yes | 63 amens | Houseboat in Amsterdam, Netherlands
  [ 24] Amsterdam  | None       2n | ★4.98 (104) | Fav:1 SH:Yes | 42 amens | Entire serviced apartment in Abcoude, Netherlands
  [ 25] Amsterdam  | None       2n | ★5 (12) | Fav:1 SH:No  | 12 amens | Entire rental unit in Amsterdam, Netherlands
        …checkpoint saved (25 rows)
  [ 26] Amsterdam  | None       2n | ★4.84 (254) | Fav:1 SH:No  | 48 amens | Entire rental unit in Amsterdam, Netherlands
  [ 27] Amsterdam  | None       2n | ★4.88 (42) | Fav:0 SH:Yes | 50 amens | Entire home in Vijfhuizen, Netherlands
  [ 28] Amsterdam  | None       2n | ★4.9 (52) | Fav:1 SH:Yes | 47 amens | Entire serviced apartment in Abcoude, Netherlands
  [ 29] Amsterdam  | None       2n | ★4.74 (347) | Fav:0 SH:No  | 38 amens | Houseboat in Amsterdam, Netherlands
  [ 30] Amsterdam  | None       2n | ★4.67 (46) | Fav:0 SH:Yes | 22 amens | Entire guesthouse in Amsterdam, Netherlands
  [ 31] Amsterdam  | None       2n | ★4.97 (239) | Fav:1 SH:Yes | 50 amens | Entire condo in Amsterdam, Netherlands
  [ 32] Amsterdam  | None       2n | ★5 (2) | Fav:0 SH:Yes | 47 amens | Entire chalet in Vijfhuizen, Netherlands
  [ 33] Amsterdam  | None       2n | ★5 (5) | Fav:1 SH:No  | 16 amens | Entire rental unit in Amsterdam, Netherlands
  [ 34] Amsterdam  | None       2n | ★4.97 (243) | Fav:1 SH:Yes | 31 amens | Entire home in Amsterdam, Netherlands
  [ 35] Amsterdam  | None       2n | ★4.88 (186) | Fav:1 SH:Yes | 58 amens | Entire place in Amsterdam, Netherlands
  [ 36] Amsterdam  | None       2n | ★4.7 (766) | Fav:0 SH:No  | 66 amens | Entire rental unit in Badhoevedorp, Netherlands
  [ 37] Amsterdam  | None       2n | ★4.93 (458) | Fav:1 SH:Yes | 44 amens | Entire cottage in Ilpendam, Netherlands
  page has 18 card URLs (city progress 37/50)
  [ 38] Amsterdam  | None       2n | ★4.81 (197) | Fav:0 SH:Yes | 54 amens | Entire bungalow in Nieuwebrug, Netherlands
  [ 39] Amsterdam  | None       2n | ★4.76 (370) | Fav:0 SH:No  | 37 amens | Entire condo in Amsterdam, Netherlands
  [ 40] Amsterdam  | None       2n | ★4.56 (233) | Fav:0 SH:No  | 43 amens | Entire serviced apartment in Amsterdam, Netherlands
  [ 41] Amsterdam  | None       2n | ★4.94 (175) | Fav:1 SH:Yes | 54 amens | Entire home in Oostzaan, Netherlands
  [ 42] Amsterdam  | None       2n | ★5 (43) | Fav:1 SH:Yes | 43 amens | Entire rental unit in Amsterdam, Netherlands
  [ 43] Amsterdam  | None       2n | ★5 (1) | Fav:0 SH:No  | 15 amens | Entire rental unit in Amsterdam, Netherlands
  [ 44] Amsterdam  | None       2n | ★4.86 (138) | Fav:1 SH:Yes | 42 amens | Entire condo in Amsterdam, Netherlands
  [ 45] Amsterdam  | None       2n | ★5 (6) | Fav:1 SH:No  | 30 amens | Entire rental unit in Amsterdam, Netherlands
  [ 46] Amsterdam  | None       2n | ★4.97 (154) | Fav:1 SH:Yes | 78 amens | Entire rental unit in Nieuw-Vennep, Netherlands
  [ 47] Amsterdam  | None       2n | ★5 (2) | Fav:0 SH:No  | 14 amens | Houseboat in Amsterdam, Netherlands
  [ 48] Amsterdam  | None       2n | ★None (None) | Fav:0 SH:No  | None amens | None
  [ 49] Amsterdam  | None       2n | ★4.88 (40) | Fav:0 SH:Yes | 30 amens | Entire home in Amsterdam, Netherlands
  [ 50] Amsterdam  | None       2n | ★4.89 (35) | Fav:1 SH:Yes | 13 amens | Entire rental unit in Amsterdam, Netherlands
        …checkpoint saved (50 rows)
  → collected 50 listings in Amsterdam
  → running total: 50

========================================================================
=== CITY 2/10: Athens ===
========================================================================
  page has 1 card URLs (city progress 0/50)
  [ 51] Athens     | None       2n | ★4.99 (189) | Fav:1 SH:Yes | 50 amens | Entire condo in Athens, Greece
  page has 18 card URLs (city progress 1/50)
  [ 52] Athens     | None       2n | ★4.87 (134) | Fav:1 SH:Yes | 39 amens | Entire rental unit in Athens, Greece
  [ 53] Athens     | None       2n | ★4.99 (155) | Fav:1 SH:Yes | 58 amens | Entire rental unit in Athens, Greece
  [ 54] Athens     | None       2n | ★4.84 (207) | Fav:1 SH:Yes | 35 amens | Entire rental unit in Athens, Greece
  [ 55] Athens     | None       2n | ★4.86 (552) | Fav:1 SH:Yes | 30 amens | Entire rental unit in Athens, Greece
  [ 56] Athens     | None       2n | ★4.93 (121) | Fav:1 SH:Yes | 43 amens | Entire rental unit in Athens, Greece
  [ 57] Athens     | None       2n | ★4.95 (111) | Fav:1 SH:Yes | 48 amens | Entire rental unit in Athens, Greece
  [ 58] Athens     | None       2n | ★4.96 (418) | Fav:1 SH:Yes | 39 amens | Entire condo in Athens, Greece
  [ 59] Athens     | None       2n | ★4.99 (519) | Fav:1 SH:No  | 36 amens | Entire rental unit in Athens, Greece
  [ 60] Athens     | None       2n | ★4.92 (120) | Fav:1 SH:No  | 28 amens | Entire rental unit in Athens, Greece
  [ 61] Athens     | None       2n | ★4.91 (91) | Fav:1 SH:Yes | 57 amens | Entire rental unit in Athens, Greece
  [ 62] Athens     | None       2n | ★4.99 (70) | Fav:1 SH:Yes | 46 amens | Entire condo in Athens, Greece
  [ 63] Athens     | None       2n | ★4.85 (40) | Fav:0 SH:Yes | 45 amens | Entire rental unit in Athens, Greece
  [ 64] Athens     | None       2n | ★4.92 (371) | Fav:1 SH:Yes | 53 amens | Entire rental unit in Athens, Greece
  [ 65] Athens     | None       2n | ★4.91 (326) | Fav:1 SH:Yes | 54 amens | Entire condo in Athens, Greece
  [ 66] Athens     | None       2n | ★4.85 (81) | Fav:0 SH:Yes | 49 amens | Entire loft in Athens, Greece
  [ 67] Athens     | None       2n | ★4.99 (275) | Fav:1 SH:Yes | 45 amens | Entire condo in Athens, Greece
  [ 68] Athens     | None       2n | ★4.92 (214) | Fav:1 SH:Yes | 58 amens | Entire rental unit in Athens, Greece
  [ 69] Athens     | None       2n | ★4.97 (106) | Fav:1 SH:Yes | 42 amens | Entire home in Athens, Greece
  page has 18 card URLs (city progress 19/50)
  [ 70] Athens     | None       2n | ★4.89 (543) | Fav:1 SH:No  | 46 amens | Entire condo in Athens, Greece
  [ 71] Athens     | None       2n | ★4.91 (514) | Fav:1 SH:Yes | 33 amens | Entire rental unit in Athens, Greece
  [ 72] Athens     | None       2n | ★4.92 (72) | Fav:1 SH:Yes | 59 amens | Entire rental unit in Athens, Greece
  [ 73] Athens     | None       2n | ★4.94 (282) | Fav:1 SH:Yes | 55 amens | Entire condo in Athens
  [ 74] Athens     | None       2n | ★4.83 (1064) | Fav:1 SH:Yes | 18 amens | Entire rental unit in Athens, Greece
  [ 75] Athens     | None       2n | ★4.86 (205) | Fav:1 SH:Yes | 38 amens | Entire rental unit in Athens, Greece
        …checkpoint saved (75 rows)
  [ 76] Athens     | None       2n | ★4.96 (198) | Fav:1 SH:Yes | 52 amens | Entire rental unit in Athens, Greece
  [ 77] Athens     | None       2n | ★4.86 (438) | Fav:1 SH:Yes | 39 amens | Entire rental unit in Athens, Greece
  [ 78] Athens     | None       2n | ★4.74 (34) | Fav:1 SH:Yes | 44 amens | Entire rental unit in Athens, Greece
  [ 79] Athens     | None       2n | ★5 (3) | Fav:0 SH:Yes | 46 amens | Entire condo in Athens, Greece
  [ 80] Athens     | None       2n | ★4.93 (344) | Fav:1 SH:Yes | 51 amens | Entire rental unit in Athens, Greece
  [ 81] Athens     | None       2n | ★4.97 (235) | Fav:1 SH:Yes | 59 amens | Entire condo in Athens, Greece
  [ 82] Athens     | None       2n | ★4.85 (154) | Fav:1 SH:No  | 28 amens | Entire rental unit in Athens, Greece
  [ 83] Athens     | None       2n | ★4.74 (54) | Fav:0 SH:Yes | 48 amens | Entire condo in Athens, Greece
  [ 84] Athens     | None       2n | ★4.82 (156) | Fav:1 SH:Yes | 34 amens | Entire rental unit in Athens, Greece
  [ 85] Athens     | None       2n | ★4.97 (296) | Fav:1 SH:Yes | 40 amens | Entire condo in Athens, Greece
  [ 86] Athens     | None       2n | ★5 (11) | Fav:1 SH:Yes | 21 amens | Entire rental unit in Athens, Greece
  [ 87] Athens     | None       2n | ★5 (12) | Fav:1 SH:No  | 43 amens | Entire rental unit in Athens, Greece
  page has 18 card URLs (city progress 37/50)
  [ 88] Athens     | None       2n | ★4.95 (60) | Fav:1 SH:Yes | 48 amens | Entire rental unit in Athens, Greece
  [ 89] Athens     | None       2n | ★4.99 (114) | Fav:1 SH:Yes | 43 amens | Entire rental unit in Athens, Greece
  [ 90] Athens     | None       2n | ★4.94 (506) | Fav:1 SH:Yes | 56 amens | Entire home in Athens, Greece
  [ 91] Athens     | None       2n | ★4.99 (212) | Fav:1 SH:Yes | 60 amens | Entire condo in Athens, Greece
  [ 92] Athens     | None       2n | ★4.96 (295) | Fav:1 SH:Yes | 52 amens | Entire condo in Athens, Greece
  [ 93] Athens     | None       2n | ★5 (38) | Fav:1 SH:Yes | 38 amens | Entire condo in Athens, Greece
  [ 94] Athens     | None       2n | ★4.74 (207) | Fav:0 SH:Yes | 37 amens | Entire rental unit in Athens, Greece
  [ 95] Athens     | None       2n | ★4.91 (217) | Fav:0 SH:Yes | 67 amens | Entire condo in Athens, Greece
  [ 96] Athens     | None       2n | ★5 (174) | Fav:1 SH:Yes | 42 amens | Entire rental unit in Athens, Greece
  [ 97] Athens     | None       2n | ★4.8 (45) | Fav:0 SH:Yes | 44 amens | Entire rental unit in Athens, Greece
  [ 98] Athens     | None       2n | ★4.96 (27) | Fav:1 SH:Yes | 56 amens | Entire rental unit in Athens, Greece
  [ 99] Athens     | None       2n | ★4.82 (258) | Fav:1 SH:Yes | 44 amens | Entire rental unit in Athens, Greece
  [100] Athens     | None       2n | ★4.93 (82) | Fav:1 SH:Yes | 29 amens | Entire rental unit in Athens, Greece
        …checkpoint saved (100 rows)
  → collected 50 listings in Athens
  → running total: 100

========================================================================
=== CITY 3/10: Barcelona ===
========================================================================
  page has 1 card URLs (city progress 0/50)
  [101] Barcelona  | None       2n | ★4.86 (3227) | Fav:0 SH:Yes | 30 amens | Rental unit in Barcelona, Spain
  page has 18 card URLs (city progress 1/50)
  [102] Barcelona  | None       2n | ★4.76 (29) | Fav:0 SH:No  | 25 amens | Rental unit in Barcelona, Spain
  [103] Barcelona  | None       2n | ★4.62 (1418) | Fav:0 SH:No  | 43 amens | Rental unit in Barcelona, Spain
  [104] Barcelona  | None       2n | ★4.73 (380) | Fav:0 SH:No  | 31 amens | Rental unit in Barcelona, Spain
  [105] Barcelona  | None       2n | ★4.78 (411) | Fav:1 SH:Yes | 53 amens | Entire rental unit in Barcelona, Spain
  [106] Barcelona  | None       2n | ★4.63 (224) | Fav:0 SH:No  | 35 amens | Entire rental unit in Barcelona, Spain
  [107] Barcelona  | None       2n | ★4.45 (452) | Fav:0 SH:No  | 31 amens | Entire rental unit in Barcelona, Spain
  [108] Barcelona  | None       2n | ★4.98 (492) | Fav:1 SH:Yes | 40 amens | Entire rental unit in Barcelona, Spain
  [109] Barcelona  | None       2n | ★4.63 (16) | Fav:0 SH:No  | 26 amens | Entire rental unit in Barcelona, Spain
  [110] Barcelona  | None       2n | ★4.65 (629) | Fav:0 SH:No  | 36 amens | Entire rental unit in Barcelona, Spain
  [111] Barcelona  | None       2n | ★4.78 (79) | Fav:0 SH:Yes | 49 amens | Entire condo in Barcelona, Spain
  [112] Barcelona  | None       2n | ★4.85 (403) | Fav:1 SH:Yes | 31 amens | Entire rental unit in Barcelona, Spain
  [113] Barcelona  | None       2n | ★5 (11) | Fav:1 SH:Yes | 42 amens | Entire rental unit in Barcelona, Spain
  [114] Barcelona  | None       2n | ★4.91 (68) | Fav:1 SH:Yes | 48 amens | Entire condo in Barcelona, Spain
  [115] Barcelona  | None       2n | ★4.93 (73) | Fav:1 SH:Yes | 53 amens | Entire condo in Barcelona, Spain
  [116] Barcelona  | None       2n | ★4.96 (747) | Fav:1 SH:Yes | 50 amens | Entire rental unit in Barcelona, Spain
  [117] Barcelona  | None       2n | ★4.91 (887) | Fav:1 SH:Yes | 35 amens | Rental unit in L'Hospitalet de Llobregat, Spain
  [118] Barcelona  | None       2n | ★4.81 (614) | Fav:1 SH:Yes | 61 amens | Entire rental unit in Barcelona, Spain
  [119] Barcelona  | None       2n | ★4.38 (454) | Fav:0 SH:No  | 15 amens | Rental unit in Barcelona, Spain
  page has 18 card URLs (city progress 19/50)
  [120] Barcelona  | None       2n | ★4.69 (494) | Fav:0 SH:Yes | 43 amens | Entire rental unit in Barcelona, Spain
  [121] Barcelona  | None       2n | ★4.66 (289) | Fav:0 SH:No  | 30 amens | Entire rental unit in Barcelona, Spain
  [122] Barcelona  | None       2n | ★4.91 (409) | Fav:1 SH:Yes | 41 amens | Entire rental unit in Barcelona, Spain
  [123] Barcelona  | None       2n | ★5 (4) | Fav:0 SH:No  | 26 amens | Entire rental unit in Barcelona, Spain
  [124] Barcelona  | None       2n | ★4.58 (26) | Fav:0 SH:Yes | 18 amens | Rental unit in Barcelona, Spain
  [125] Barcelona  | None       2n | ★4.7 (954) | Fav:0 SH:No  | 17 amens | Rental unit in Barcelona, Spain
        …checkpoint saved (125 rows)
  [126] Barcelona  | None       2n | ★4.84 (371) | Fav:0 SH:Yes | 14 amens | Entire rental unit in Barcelona, Spain
  [127] Barcelona  | None       2n | ★4.9 (273) | Fav:1 SH:Yes | 42 amens | Entire rental unit in Barcelona, Spain
  [128] Barcelona  | None       2n | ★4.74 (959) | Fav:0 SH:Yes | 39 amens | Entire rental unit in Barcelona, Spain
  [129] Barcelona  | None       2n | ★4.86 (588) | Fav:1 SH:Yes | 44 amens | Entire rental unit in Barcelona, Spain
  [130] Barcelona  | None       2n | ★4.76 (169) | Fav:0 SH:Yes | 40 amens | Entire condo in L'Hospitalet de Llobregat, Spain
  [131] Barcelona  | None       2n | ★4.91 (288) | Fav:1 SH:Yes | 40 amens | Entire serviced apartment in Barcelona, Spain
  [132] Barcelona  | None       2n | ★4.87 (741) | Fav:1 SH:Yes | 43 amens | Entire rental unit in Barcelona, Spain
  [133] Barcelona  | None       2n | ★4.96 (25) | Fav:1 SH:Yes | 39 amens | Entire rental unit in Barcelona, Spain
  [134] Barcelona  | None       2n | ★4.77 (2972) | Fav:0 SH:Yes | 37 amens | Serviced apartment in Castelldefels, Spain
  [135] Barcelona  | None       2n | ★4.99 (419) | Fav:1 SH:Yes | 27 amens | Entire rental unit in Barcelona, Spain
  [136] Barcelona  | None       2n | ★4.77 (357) | Fav:1 SH:Yes | 36 amens | Entire rental unit in Barcelona, Spain
  [137] Barcelona  | None       2n | ★4.76 (45) | Fav:0 SH:Yes | 34 amens | Entire rental unit in Barcelona, Spain
  page has 18 card URLs (city progress 37/50)
  [138] Barcelona  | None       2n | ★4.78 (731) | Fav:1 SH:Yes | 44 amens | Entire rental unit in Barcelona, Spain
  [139] Barcelona  | None       2n | ★4.77 (357) | Fav:1 SH:Yes | 36 amens | Entire rental unit in Barcelona, Spain
  [140] Barcelona  | None       2n | ★4.55 (258) | Fav:0 SH:No  | 42 amens | Entire rental unit in Barcelona, Spain
  [141] Barcelona  | None       2n | ★4.89 (726) | Fav:1 SH:Yes | 31 amens | Entire rental unit in Barcelona, Spain
  [142] Barcelona  | None       2n | ★4.71 (370) | Fav:0 SH:Yes | 45 amens | Entire rental unit in Barcelona, Spain
  [143] Barcelona  | None       2n | ★4.73 (282) | Fav:1 SH:No  | 40 amens | Entire rental unit in Barcelona, Spain
  [144] Barcelona  | None       2n | ★4.87 (383) | Fav:1 SH:Yes | 29 amens | Entire rental unit in Barcelona, Spain
  [145] Barcelona  | None       2n | ★4.9 (49) | Fav:0 SH:Yes | 38 amens | Entire rental unit in Barcelona, Spain
  [146] Barcelona  | None       2n | ★4.81 (454) | Fav:1 SH:Yes | 32 amens | Entire rental unit in Barcelona, Spain
  [147] Barcelona  | None       2n | ★4.65 (622) | Fav:0 SH:Yes | 45 amens | Entire condo in Barcelona, Spain
  [148] Barcelona  | None       2n | ★4.41 (54) | Fav:0 SH:No  | 28 amens | Entire rental unit in Barcelona, Spain
  [149] Barcelona  | None       2n | ★4.83 (408) | Fav:0 SH:Yes | 51 amens | Entire rental unit in Barcelona, Spain
  [150] Barcelona  | None       2n | ★4.86 (147) | Fav:0 SH:Yes | 30 amens | Entire rental unit in Barcelona, Spain
        …checkpoint saved (150 rows)
  → collected 50 listings in Barcelona
  → running total: 150

========================================================================
=== CITY 4/10: Berlin ===
========================================================================
  page has 1 card URLs (city progress 0/50)
  [151] Berlin     | None       2n | ★4.84 (1125) | Fav:0 SH:Yes | 59 amens | Entire serviced apartment in Berlin, Germany
  page has 1 card URLs (city progress 1/50)
  [152] Berlin     | None       2n | ★4.7 (27) | Fav:0 SH:No  | 39 amens | Entire rental unit in Berlin, Germany
  page has 18 card URLs (city progress 2/50)
  [153] Berlin     | None       2n | ★4.86 (42) | Fav:0 SH:No  | 57 amens | Entire rental unit in Berlin, Germany
  [154] Berlin     | None       2n | ★4.35 (298) | Fav:0 SH:No  | 27 amens | Entire rental unit in Berlin, Germany
  [155] Berlin     | None       2n | ★4.91 (11) | Fav:1 SH:Yes | 51 amens | Entire rental unit in Berlin, Germany
  [156] Berlin     | None       2n | ★4.67 (501) | Fav:0 SH:Yes | 25 amens | Entire rental unit in Berlin, Germany
  [157] Berlin     | None       2n | ★0 (0) | Fav:0 SH:Yes | 56 amens | Entire rental unit in Berlin, Germany
  [158] Berlin     | None       2n | ★4.93 (119) | Fav:0 SH:Yes | 49 amens | Entire rental unit in Berlin, Germany

In [ ]:
# =====================================================
#  FILL PRICES IN EXISTING CSV
#  Reads airbnb_listings.csv → visits every URL →
#  extracts Price / PricePerNightEst / CleaningFee /
#  ServiceFee / Taxes → writes airbnb_listings_priced.csv
# =====================================================
import re, json, time, random
from datetime import datetime
from urllib.parse import urlparse, parse_qs

import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from seleniumbase import Driver

# ---------------- CONFIG ----------------
INPUT_CSV        = "/content/airbnb_listings_weekends.csv"
OUTPUT_CSV       = "/content/airbnb_listings_weekends_priced.csv"
FORCE_REFETCH    = False          # True → re-scrape rows that already have a Price
CHECKPOINT_EVERY = 25
SLEEP_BETWEEN    = (1.5, 3.0)     # polite delay between page loads
HEADLESS         = True

# ---------------- HELPERS ----------------
def safe_get(d, path, default=None):
    cur = d
    for p in path:
        if isinstance(cur, dict):
            cur = cur.get(p)
        elif isinstance(cur, list) and isinstance(p, int) and 0 <= p < len(cur):
            cur = cur[p]
        else:
            return default
        if cur is None:
            return default
    return cur

def parse_money(s):
    if s is None: return None
    s = re.sub(r"[^\d,\.]", "", str(s))
    if not s: return None
    # If both . and , present → . is decimal, , is thousands
    if "." in s and "," in s:
        s = s.replace(",", "")
    else:
        s = s.replace(",", "")
    try:
        return float(s)
    except ValueError:
        return None

def nights_from_url(url):
    q = parse_qs(urlparse(url).query)
    ci, co = q.get("check_in", [None])[0], q.get("check_out", [None])[0]
    if ci and co:
        try:
            return (datetime.strptime(co, "%Y-%m-%d")
                    - datetime.strptime(ci, "%Y-%m-%d")).days
        except Exception:
            return None
    return None

def get_deferred_state(driver):
    try:
        el  = driver.find_element(By.ID, "data-deferred-state-0")
        txt = el.get_attribute("textContent") or el.get_attribute("innerHTML")
        return json.loads(txt)
    except Exception:
        return None

def get_json_ld(driver):
    out = []
    try:
        for s in driver.find_elements(By.CSS_SELECTOR,
                                      'script[type="application/ld+json"]'):
            try:    out.append(json.loads(s.get_attribute("textContent")))
            except Exception: pass
    except Exception: pass
    return out

# ---------------- PRICE EXTRACTORS ----------------
def price_from_ld(ld_list):
    """VacationRental JSON-LD usually carries offers[].price."""
    for obj in ld_list:
        if obj.get("@type") == "VacationRental":
            offers = obj.get("offers") or []
            if isinstance(offers, dict):
                offers = [offers]
            for o in offers:
                p = o.get("price")
                if p is not None:
                    try:
                        v = float(p)
                        if v > 0: return v
                    except Exception:
                        pass
    return None

def price_from_state(state):
    """
    Robust extraction from the data-deferred-state-0 JSON.
    Returns dict: Price, CleaningFee, ServiceFee, Taxes.
    """
    out = {"Price": None, "CleaningFee": None, "ServiceFee": None, "Taxes": None}
    if not state:
        return out

    node = None
    for key, payload in (state.get("niobeClientData") or []):
        if isinstance(key, str) and key.startswith("StaysPdpSections"):
            node = safe_get(payload, ["data", "node"]); break
    if node is None:
        node = safe_get(state, ["niobeClientData", 0, 1, "data", "node"])
    if not node:
        return out

    pdp = node.get("pdpPresentation") or {}

    # ---- 1. Structured paths (most common today) ----
    structured_paths = [
        ["structuredDisplayPrice", "primaryLine", "price"],
        ["structuredDisplayPrice", "primaryLine", "discountedPrice"],
        ["structuredDisplayPrice", "secondaryLine", "price"],
        ["bookIt", "priceBreakdown", "total"],
        ["booking", "priceBreakdown", "total"],
        ["pricing", "priceBreakdown", "total"],
        ["pricing", "primaryPrice"],
    ]
    for prefix in (node, pdp):
        for path in structured_paths:
            val = safe_get(prefix, path)
            if isinstance(val, dict):
                amt = (val.get("amount")
                       or val.get("unformattedValue")
                       or val.get("value"))
                if isinstance(amt, (int, float)) and amt > 0:
                    out["Price"] = float(amt); break
            elif isinstance(val, (int, float)) and val > 0:
                out["Price"] = float(val); break
        if out["Price"]:
            break

    # ---- 2. Recursive scan as fallback ----
    if out["Price"] is None:
        hits = []
        def walk(o, p=""):
            if isinstance(o, dict):
                for k, v in o.items():
                    kl = k.lower()
                    if kl in ("amount", "unformattedvalue", "value", "total") \
                       and isinstance(v, (int, float)) and v > 0:
                        pl = (p + "." + k).lower()
                        if any(w in pl for w in
                               ("price", "pricing", "total", "cost", "breakdown")):
                            # skip fee-like paths
                            if not any(f in pl for f in
                                       ("cleaning", "servicefee",
                                        "service_fee", "tax", "nightly",
                                        "pernight", "per_night", "monthly")):
                                hits.append((p + "." + k, v))
                    walk(v, p + "." + k)
            elif isinstance(o, list):
                for i, v in enumerate(o):
                    walk(v, f"{p}[{i}]")
        walk(node, "node")
        if hits:
            # Prefer the largest 'total' candidate
            totals = [h for h in hits if "total" in h[0].lower()]
            pool = totals or hits
            out["Price"] = max(pool, key=lambda x: x[1])[1]

    # ---- 3. Fee line items ----
    for path in (
        ["pricing", "priceBreakdown", "lineItems"],
        ["booking", "priceBreakdown", "lineItems"],
        ["bookIt", "priceBreakdown", "lineItems"],
    ):
        items = safe_get(node, path) or safe_get(pdp, path) or []
        for it in items:
            label = ((it.get("localizedTitle") or "") + " " +
                     (it.get("title") or "")).lower()
            amt = (safe_get(it, ["price", "amount"])
                   or safe_get(it, ["price", "unformattedValue"])
                   or it.get("amount"))
            if not isinstance(amt, (int, float)):
                continue
            if "clean" in label and out["CleaningFee"] is None:
                out["CleaningFee"] = float(amt)
            elif "service" in label and "fee" in label and out["ServiceFee"] is None:
                out["ServiceFee"] = float(amt)
            elif "tax" in label and out["Taxes"] is None:
                out["Taxes"] = float(amt)
        if any(out[k] is not None for k in ("CleaningFee","ServiceFee","Taxes")):
            break

    return out

def price_from_dom(driver, nights):
    """Currency-agnostic body-text fallback."""
    out = {"Price": None, "CleaningFee": None, "ServiceFee": None, "Taxes": None}
    try:
        body = driver.find_element(By.TAG_NAME, "body").text
    except Exception:
        return out

    # 1) total price
    for pat in (
        r"(?:total)\s*:?\s*([€$£¥]\s*[\d.,]+)",
        r"([€$£¥]\s*[\d.,]+)\s*(?:total|grand\s*total)",
        r"([€$£¥]\s*[\d.,]+)\s*for\s*\d+\s*nights?",
        r"for\s*\d+\s*nights?[^\n€$£¥]{0,30}([€$£¥]\s*[\d.,]+)",
    ):
        m = re.search(pat, body, re.IGNORECASE)
        if m:
            p = parse_money(m.group(1))
            if p and p > 0:
                out["Price"] = p
                break

    # 2) per-night × nights fallback
    if out["Price"] is None and nights:
        m = re.search(r"([€$£¥]\s*[\d.,]+)\s*(?:/|per\s+)night",
                      body, re.IGNORECASE)
        if m:
            pn = parse_money(m.group(1))
            if pn:
                out["Price"] = round(pn * nights, 2)

    # 3) fees
    for lbl, key in (
        ("cleaning fee",       "CleaningFee"),
        ("airbnb service fee", "ServiceFee"),
        ("service fee",        "ServiceFee"),
        ("taxes",              "Taxes"),
        ("tax",                "Taxes"),
    ):
        if out[key] is not None:
            continue
        m = re.search(rf"{re.escape(lbl)}[^\d\n€$£¥]{{0,25}}"
                      rf"([€$£¥]?\s*[\d.,]+)", body, re.IGNORECASE)
        if m:
            v = parse_money(m.group(1))
            if v: out[key] = v

    return out

# ---------------- MAIN ----------------
def has_price(row):
    p = row.get("Price")
    if p is None: return False
    try:
        if pd.isna(p): return False
        return float(p) > 0
    except Exception:
        return False

def main():
    df = pd.read_csv(INPUT_CSV, encoding="utf-8-sig")

    # Guarantee the columns exist
    for c in ("Price", "PricePerNightEst", "CleaningFee",
              "ServiceFee", "Taxes", "Nights"):
        if c not in df.columns:
            df[c] = None

    total = len(df)
    todo = [i for i, r in df.iterrows()
            if FORCE_REFETCH or not has_price(r)]
    print(f"Total rows: {total} | Rows to fetch: {len(todo)}\n")

    driver = Driver(browser="chrome", headless=HEADLESS)
    driver.set_window_size(1920, 1080)
    wait = WebDriverWait(driver, 10)

    try:
        for n, i in enumerate(todo, 1):
            url = df.at[i, "URL"]
            if not isinstance(url, str) or "airbnb" not in url:
                print(f"[{n}/{len(todo)}] row {i}: no URL, skip")
                continue

            nights = df.at[i, "Nights"]
            if pd.isna(nights) or not nights:
                nights = nights_from_url(url)
                df.at[i, "Nights"] = nights

            try:
                driver.get(url)
                wait.until(EC.presence_of_element_located((By.TAG_NAME, "h1")))
                # Let deferred-state settle
                try:
                    WebDriverWait(driver, 6).until(
                        EC.presence_of_element_located(
                            (By.ID, "data-deferred-state-0")))
                except Exception:
                    pass
                time.sleep(random.uniform(*SLEEP_BETWEEN))

                state = get_deferred_state(driver)
                ld    = get_json_ld(driver)

                data = price_from_state(state)

                # JSON-LD fallback
                if not data["Price"]:
                    p = price_from_ld(ld)
                    if p: data["Price"] = p

                # DOM fallback (also fills fees if state missed them)
                if (not data["Price"]) or any(
                    data[k] is None for k in
                    ("CleaningFee", "ServiceFee", "Taxes")):
                    dom = price_from_dom(driver, nights)
                    for k, v in dom.items():
                        if not data.get(k) and v:
                            data[k] = v

                # Write back
                df.at[i, "Price"] = data["Price"]
                df.at[i, "CleaningFee"] = data["CleaningFee"]
                df.at[i, "ServiceFee"]  = data["ServiceFee"]
                df.at[i, "Taxes"]       = data["Taxes"]
                if data["Price"] and nights:
                    df.at[i, "PricePerNightEst"] = round(
                        data["Price"] / nights, 2)

                city = df.at[i, "city"] if "city" in df.columns else "?"
                pn   = df.at[i, "PricePerNightEst"]
                print(f"[{n}/{len(todo)}] row {i:>3} | {city:<12} | "
                      f"Price={data['Price']} | {nights}n | PN={pn}")

                if n % CHECKPOINT_EVERY == 0:
                    df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")
                    print(f"   ↳ checkpoint saved ({n}/{len(todo)})")

            except Exception as e:
                print(f"[{n}/{len(todo)}] row {i}: "
                      f"{type(e).__name__}: {str(e)[:90]}")
                continue
    finally:
        try: driver.quit()
        except Exception: pass
        df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")
        filled = df["Price"].notna().sum()
        print(f"\nDONE → {OUTPUT_CSV}")
        print(f"Rows with Price: {filled}/{total} "
              f"({filled/total*100:.1f}%)")
        print(f"Rows with CleaningFee: {df['CleaningFee'].notna().sum()}")
        print(f"Rows with ServiceFee:  {df['ServiceFee'].notna().sum()}")
        print(f"Rows with Taxes:       {df['Taxes'].notna().sum()}")

if __name__ == "__main__":
    main()

Total rows: 500 | Rows to fetch: 500

[1/500] row   0 | Amsterdam    | Price=548.0 | 2n | PN=274.0
[2/500] row   1 | Amsterdam    | Price=1902.0 | 2n | PN=951.0
[3/500] row   2 | Amsterdam    | Price=770.0 | 2n | PN=385.0
[4/500] row   3 | Amsterdam    | Price=669.0 | 2n | PN=334.5
[5/500] row   4 | Amsterdam    | Price=548.0 | 2n | PN=274.0
[6/500] row   5 | Amsterdam    | Price=None | 2n | PN=nan
[7/500] row   6 | Amsterdam    | Price=1241.0 | 2n | PN=620.5
[8/500] row   7 | Amsterdam    | Price=771.0 | 2n | PN=385.5
[9/500] row   8 | Amsterdam    | Price=923.0 | 2n | PN=461.5
[10/500] row   9 | Amsterdam    | Price=1109.0 | 2n | PN=554.5
[11/500] row  10 | Amsterdam    | Price=642.0 | 2n | PN=321.0
[12/500] row  11 | Amsterdam    | Price=315.0 | 2n | PN=157.5
[13/500] row  12 | Amsterdam    | Price=1335.0 | 2n | PN=667.5
[14/500] row  13 | Amsterdam    | Price=240.0 | 2n | PN=120.0
[15/500] row  14 | Amsterdam    | Price=967.0 | 2n | PN=483.5
[16/500] row  15 | Amsterdam    | Price=1566.0 | 2n | PN=783.0
[17/500] row  16 | Amsterdam    | Price=673.0 | 2n | PN=336.5
[18/500] row  17 | Amsterdam    | Price=1080.0 | 2n | PN=540.0
[19/500] row  18 | Amsterdam    | Price=782.0 | 2n | PN=391.0
[20/500] row  19 | Amsterdam    | Price=628.0 | 2n | PN=314.0
[21/500] row  20 | Amsterdam    | Price=1549.0 | 2n | PN=774.5
[22/500] row  21 | Amsterdam    | Price=1109.0 | 2n | PN=554.5
[23/500] row  22 | Amsterdam    | Price=920.0 | 2n | PN=460.0
[24/500] row  23 | Amsterdam    | Price=581.0 | 2n | PN=290.5
[25/500] row  24 | Amsterdam    | Price=951.0 | 2n | PN=475.5
   ↳ checkpoint saved (25/500)
[26/500] row  25 | Amsterdam    | Price=1105.0 | 2n | PN=552.5
[27/500] row  26 | Amsterdam    | Price=572.0 | 2n | PN=286.0
[28/500] row  27 | Amsterdam    | Price=529.0 | 2n | PN=264.5
[29/500] row  28 | Amsterdam    | Price=935.0 | 2n | PN=467.5
[30/500] row  29 | Amsterdam    | Price=619.0 | 2n | PN=309.5
[31/500] row  30 | Amsterdam    | Price=1256.0 | 2n | PN=628.0
[32/500] row  31 | Amsterdam    | Price=466.0 | 2n | PN=233.0
[33/500] row  32 | Amsterdam    | Price=741.0 | 2n | PN=370.5
[34/500] row  33 | Amsterdam    | Price=913.0 | 2n | PN=456.5
[35/500] row  34 | Amsterdam    | Price=742.0 | 2n | PN=371.0
[36/500] row  35 | Amsterdam    | Price=258.0 | 2n | PN=129.0
[37/500] row  36 | Amsterdam    | Price=445.0 | 2n | PN=222.5
[38/500] row  37 | Amsterdam    | Price=459.0 | 2n | PN=229.5
[39/500] row  38 | Amsterdam    | Price=1012.0 | 2n | PN=506.0
[40/500] row  39 | Amsterdam    | Price=None | 2n | PN=nan
[41/500] row  40 | Amsterdam    | Price=641.0 | 2n | PN=320.5
[42/500] row  41 | Amsterdam    | Price=1268.0 | 2n | PN=634.0
[43/500] row  42 | Amsterdam    | Price=642.0 | 2n | PN=321.0
[44/500] row  43 | Amsterdam    | Price=1734.0 | 2n | PN=867.0
[45/500] row  44 | Amsterdam    | Price=1250.0 | 2n | PN=625.0
[46/500] row  45 | Amsterdam    | Price=300.0 | 2n | PN=150.0
[47/500] row  46 | Amsterdam    | Price=816.0 | 2n | PN=408.0
[48/500] row  47 | Amsterdam    | Price=1067.0 | 2n | PN=533.5
[49/500] row  48 | Amsterdam    | Price=1432.0 | 2n | PN=716.0
[50/500] row  49 | Amsterdam    | Price=669.0 | 2n | PN=334.5
   ↳ checkpoint saved (50/500)
[51/500] row  50 | Athens       | Price=325.0 | 2n | PN=162.5
[52/500] row  51 | Athens       | Price=223.0 | 2n | PN=111.5
[53/500] row  52 | Athens       | Price=309.0 | 2n | PN=154.5
[54/500] row  53 | Athens       | Price=480.0 | 2n | PN=240.0
[55/500] row  54 | Athens       | Price=176.0 | 2n | PN=88.0
[56/500] row  55 | Athens       | Price=222.0 | 2n | PN=111.0
[57/500] row  56 | Athens       | Price=392.0 | 2n | PN=196.0
[58/500] row  57 | Athens       | Price=368.0 | 2n | PN=184.0
[59/500] row  58 | Athens       | Price=254.0 | 2n | PN=127.0
[60/500] row  59 | Athens       | Price=234.0 | 2n | PN=117.0
[61/500] row  60 | Athens       | Price=248.0 | 2n | PN=124.0
[62/500] row  61 | Athens       | Price=239.0 | 2n | PN=119.5
[63/500] row  62 | Athens       | Price=134.0 | 2n | PN=67.0
[64/500] row  63 | Athens       | Price=531.0 | 2n | PN=265.5
[65/500] row  64 | Athens       | Price=222.0 | 2n | PN=111.0
[66/500] row  65 | Athens       | Price=214.0 | 2n | PN=107.0
[67/500] row  66 | Athens       | Price=204.0 | 2n | PN=102.0
[68/500] row  67 | Athens       | Price=330.0 | 2n | PN=165.0
[69/500] row  68 | Athens       | Price=1054.0 | 2n | PN=527.0
[70/500] row  69 | Athens       | Price=256.0 | 2n | PN=128.0
[71/500] row  70 | Athens       | Price=242.0 | 2n | PN=121.0
[72/500] row  71 | Athens       | Price=404.0 | 2n | PN=202.0
[73/500] row  72 | Athens       | Price=300.0 | 2n | PN=150.0
[74/500] row  73 | Athens       | Price=198.0 | 2n | PN=99.0
[75/500] row  74 | Athens       | Price=156.0 | 2n | PN=78.0
   ↳ checkpoint saved (75/500)
[76/500] row  75 | Athens       | Price=288.0 | 2n | PN=144.0
[77/500] row  76 | Athens       | Price=289.0 | 2n | PN=144.5
[78/500] row  77 | Athens       | Price=217.0 | 2n | PN=108.5
[79/500] row  78 | Athens       | Price=303.0 | 2n | PN=151.5
[80/500] row  79 | Athens       | Price=495.0 | 2n | PN=247.5
[81/500] row  80 | Athens       | Price=163.0 | 2n | PN=81.5
[82/500] row  81 | Athens       | Price=206.0 | 2n | PN=103.0
[83/500] row  82 | Athens       | Price=341.0 | 2n | PN=170.5
[84/500] row  83 | Athens       | Price=393.0 | 2n | PN=196.5
[85/500] row  84 | Athens       | Price=176.0 | 2n | PN=88.0
[86/500] row  85 | Athens       | Price=367.0 | 2n | PN=183.5
[87/500] row  86 | Athens       | Price=527.0 | 2n | PN=263.5
[88/500] row  87 | Athens       | Price=290.0 | 2n | PN=145.0
[89/500] row  88 | Athens       | Price=851.0 | 2n | PN=425.5
[90/500] row  89 | Athens       | Price=413.0 | 2n | PN=206.5
[91/500] row  90 | Athens       | Price=288.0 | 2n | PN=144.0
[92/500] row  91 | Athens       | Price=296.0 | 2n | PN=148.0
[93/500] row  92 | Athens       | Price=313.0 | 2n | PN=156.5
[94/500] row  93 | Athens       | Price=170.0 | 2n | PN=85.0
[95/500] row  94 | Athens       | Price=260.0 | 2n | PN=130.0
[96/500] row  95 | Athens       | Price=206.0 | 2n | PN=103.0
[97/500] row  96 | Athens       | Price=217.0 | 2n | PN=108.5
[98/500] row  97 | Athens       | Price=381.0 | 2n | PN=190.5
[99/500] row  98 | Athens       | Price=253.0 | 2n | PN=126.5
[100/500] row  99 | Athens       | Price=479.0 | 2n | PN=239.5
   ↳ checkpoint saved (100/500)
[101/500] row 100 | Barcelona    | Price=304.0 | 2n | PN=152.0
[102/500] row 101 | Barcelona    | Price=278.0 | 2n | PN=139.0
[103/500] row 102 | Barcelona    | Price=439.0 | 2n | PN=219.5
[104/500] row 103 | Barcelona    | Price=405.0 | 2n | PN=202.5
[105/500] row 104 | Barcelona    | Price=510.0 | 2n | PN=255.0
[106/500] row 105 | Barcelona    | Price=510.0 | 2n | PN=255.0
[107/500] row 106 | Barcelona    | Price=None | 2n | PN=nan
[108/500] row 107 | Barcelona    | Price=517.0 | 2n | PN=258.5
[109/500] row 108 | Barcelona    | Price=260.0 | 2n | PN=130.0
[110/500] row 109 | Barcelona    | Price=301.0 | 2n | PN=150.5
[111/500] row 110 | Barcelona    | Price=334.0 | 2n | PN=167.0
[112/500] row 111 | Barcelona    | Price=371.0 | 2n | PN=185.5
[113/500] row 112 | Barcelona    | Price=406.0 | 2n | PN=203.0
[114/500] row 113 | Barcelona    | Price=321.0 | 2n | PN=160.5
[115/500] row 114 | Barcelona    | Price=370.0 | 2n | PN=185.0
[116/500] row 115 | Barcelona    | Price=614.0 | 2n | PN=307.0
[117/500] row 116 | Barcelona    | Price=374.0 | 2n | PN=187.0
[118/500] row 117 | Barcelona    | Price=496.0 | 2n | PN=248.0
[119/500] row 118 | Barcelona    | Price=344.0 | 2n | PN=172.0
[120/500] row 119 | Barcelona    | Price=318.0 | 2n | PN=159.0
[121/500] row 120 | Barcelona    | Price=377.0 | 2n | PN=188.5
[122/500] row 121 | Barcelona    | Price=392.0 | 2n | PN=196.0
[123/500] row 122 | Barcelona    | Price=244.0 | 2n | PN=122.0
[124/500] row 123 | Barcelona    | Price=384.0 | 2n | PN=192.0
[125/500] row 124 | Barcelona    | Price=420.0 | 2n | PN=210.0
   ↳ checkpoint saved (125/500)
[126/500] row 125 | Barcelona    | Price=371.0 | 2n | PN=185.5
[127/500] row 126 | Barcelona    | Price=399.0 | 2n | PN=199.5
[128/500] row 127 | Barcelona    | Price=308.0 | 2n | PN=154.0
[129/500] row 128 | Barcelona    | Price=571.0 | 2n | PN=285.5
[130/500] row 129 | Barcelona    | Price=276.0 | 2n | PN=138.0
[131/500] row 130 | Barcelona    | Price=546.0 | 2n | PN=273.0
[132/500] row 131 | Barcelona    | Price=378.0 | 2n | PN=189.0
[133/500] row 132 | Barcelona    | Price=365.0 | 2n | PN=182.5
[134/500] row 133 | Barcelona    | Price=157.0 | 2n | PN=78.5
[135/500] row 134 | Barcelona    | Price=693.0 | 2n | PN=346.5
[136/500] row 135 | Barcelona    | Price=395.0 | 2n | PN=197.5
[137/500] row 136 | Barcelona    | Price=352.0 | 2n | PN=176.0
[138/500] row 137 | Barcelona    | Price=310.0 | 2n | PN=155.0
[139/500] row 138 | Barcelona    | Price=395.0 | 2n | PN=197.5
[140/500] row 139 | Barcelona    | Price=289.0 | 2n | PN=144.5
[141/500] row 140 | Barcelona    | Price=451.0 | 2n | PN=225.5
[142/500] row 141 | Barcelona    | Price=355.0 | 2n | PN=177.5
[143/500] row 142 | Barcelona    | Price=395.0 | 2n | PN=197.5
[144/500] row 143 | Barcelona    | Price=385.0 | 2n | PN=192.5
[145/500] row 144 | Barcelona    | Price=373.0 | 2n | PN=186.5
[146/500] row 145 | Barcelona    | Price=290.0 | 2n | PN=145.0
[147/500] row 146 | Barcelona    | Price=279.0 | 2n | PN=139.5
[148/500] row 147 | Barcelona    | Price=411.0 | 2n | PN=205.5
[149/500] row 148 | Barcelona    | Price=319.0 | 2n | PN=159.5
[150/500] row 149 | Barcelona    | Price=397.0 | 2n | PN=198.5
   ↳ checkpoint saved (150/500)
[151/500] row 150 | Berlin       | Price=437.0 | 2n | PN=218.5
[152/500] row 151 | Berlin       | Price=377.0 | 2n | PN=188.5
[153/500] row 152 | Berlin       | Price=678.0 | 2n | PN=339.0
[154/500] row 153 | Berlin       | Price=None | 2n | PN=nan
[155/500] row 154 | Berlin       | Price=412.0 | 2n | PN=206.0
[156/500] row 155 | Berlin       | Price=398.0 | 2n | PN=199.0
[157/500] row 156 | Berlin       | Price=512.0 | 2n | PN=256.0
[158/500] row 157 | Berlin       | Price=None | 2n | PN=nan
[159/500] row 158 | Berlin       | Price=601.0 | 2n | PN=300.5
[160/500] row 159 | Berlin       | Price=334.0 | 2n | PN=167.0
[161/500] row 160 | Berlin       | Price=539.0 | 2n | PN=269.5
[162/500] row 161 | Berlin       | Price=746.0 | 2n | PN=373.0
[163/500] row 162 | Berlin       | Price=535.0 | 2n | PN=267.5
[164/500] row 163 | Berlin       | Price=536.0 | 2n | PN=268.0
[165/500] row 164 | Berlin       | Price=455.0 | 2n | PN=227.5
[166/500] row 165 | Berlin       | Price=357.0 | 2n | PN=178.5
[167/500] row 166 | Berlin       | Price=334.0 | 2n | PN=167.0
[168/500] row 167 | Berlin       | Price=356.0 | 2n | PN=178.0
[169/500] row 168 | Berlin       | Price=823.0 | 2n | PN=411.5
[170/500] row 169 | Berlin       | Price=482.0 | 2n | PN=241.0
[171/500] row 170 | Berlin       | Price=823.0 | 2n | PN=411.5
[172/500] row 171 | Berlin       | Price=323.0 | 2n | PN=161.5
[173/500] row 172 | Berlin       | Price=632.0 | 2n | PN=316.0
[174/500] row 173 | Berlin       | Price=204.0 | 2n | PN=102.0
[175/500] row 174 | Berlin       | Price=638.0 | 2n | PN=319.0
   ↳ checkpoint saved (175/500)
[176/500] row 175 | Berlin       | Price=279.0 | 2n | PN=139.5
[177/500] row 176 | Berlin       | Price=505.0 | 2n | PN=252.5
[178/500] row 177 | Berlin       | Price=213.0 | 2n | PN=106.5
[179/500] row 178 | Berlin       | Price=476.0 | 2n | PN=238.0
[180/500] row 179 | Berlin       | Price=631.0 | 2n | PN=315.5
[181/500] row 180 | Berlin       | Price=393.0 | 2n | PN=196.5
[182/500] row 181 | Berlin       | Price=853.0 | 2n | PN=426.5
[183/500] row 182 | Berlin       | Price=363.0 | 2n | PN=181.5
[184/500] row 183 | Berlin       | Price=None | 2n | PN=nan
[185/500] row 184 | Berlin       | Price=374.0 | 2n | PN=187.0
[186/500] row 185 | Berlin       | Price=261.0 | 2n | PN=130.5
[187/500] row 186 | Berlin       | Price=387.0 | 2n | PN=193.5
[188/500] row 187 | Berlin       | Price=368.0 | 2n | PN=184.0
[189/500] row 188 | Berlin       | Price=434.0 | 2n | PN=217.0
[190/500] row 189 | Berlin       | Price=417.0 | 2n | PN=208.5
[191/500] row 190 | Berlin       | Price=737.0 | 2n | PN=368.5
[192/500] row 191 | Berlin       | Price=435.0 | 2n | PN=217.5
[193/500] row 192 | Berlin       | Price=610.0 | 2n | PN=305.0
[194/500] row 193 | Berlin       | Price=429.0 | 2n | PN=214.5
[195/500] row 194 | Berlin       | Price=784.0 | 2n | PN=392.0
[196/500] row 195 | Berlin       | Price=481.0 | 2n | PN=240.5
[197/500] row 196 | Berlin       | Price=743.0 | 2n | PN=371.5
[198/500] row 197 | Berlin       | Price=384.0 | 2n | PN=192.0
[199/500] row 198 | Berlin       | Price=None | 2n | PN=nan
[200/500] row 199 | Berlin       | Price=533.0 | 2n | PN=266.5
   ↳ checkpoint saved (200/500)
[201/500] row 200 | Budapest     | Price=182.0 | 2n | PN=91.0
[202/500] row 201 | Budapest     | Price=419.0 | 2n | PN=209.5
[203/500] row 202 | Budapest     | Price=339.0 | 2n | PN=169.5
[204/500] row 203 | Budapest     | Price=192.0 | 2n | PN=96.0
[205/500] row 204 | Budapest     | Price=206.0 | 2n | PN=103.0
[206/500] row 205 | Budapest     | Price=241.0 | 2n | PN=120.5
[207/500] row 206 | Budapest     | Price=196.0 | 2n | PN=98.0
[208/500] row 207 | Budapest     | Price=717.0 | 2n | PN=358.5
[209/500] row 208 | Budapest     | Price=150.0 | 2n | PN=75.0
[210/500] row 209 | Budapest     | Price=184.0 | 2n | PN=92.0
[211/500] row 210 | Budapest     | Price=398.0 | 2n | PN=199.0
[212/500] row 211 | Budapest     | Price=196.0 | 2n | PN=98.0
[213/500] row 212 | Budapest     | Price=364.0 | 2n | PN=182.0
[214/500] row 213 | Budapest     | Price=237.0 | 2n | PN=118.5
[215/500] row 214 | Budapest     | Price=368.0 | 2n | PN=184.0
[216/500] row 215 | Budapest     | Price=295.0 | 2n | PN=147.5
[217/500] row 216 | Budapest     | Price=202.0 | 2n | PN=101.0
[218/500] row 217 | Budapest     | Price=497.0 | 2n | PN=248.5
[219/500] row 218 | Budapest     | Price=176.0 | 2n | PN=88.0
[220/500] row 219 | Budapest     | Price=165.0 | 2n | PN=82.5
[221/500] row 220 | Budapest     | Price=274.0 | 2n | PN=137.0
[222/500] row 221 | Budapest     | Price=215.0 | 2n | PN=107.5
[223/500] row 222 | Budapest     | Price=822.0 | 2n | PN=411.0
[224/500] row 223 | Budapest     | Price=342.0 | 2n | PN=171.0
[225/500] row 224 | Budapest     | Price=223.0 | 2n | PN=111.5
   ↳ checkpoint saved (225/500)
[226/500] row 225 | Budapest     | Price=307.0 | 2n | PN=153.5
[227/500] row 226 | Budapest     | Price=307.0 | 2n | PN=153.5
[228/500] row 227 | Budapest     | Price=215.0 | 2n | PN=107.5
[229/500] row 228 | Budapest     | Price=302.0 | 2n | PN=151.0
[230/500] row 229 | Budapest     | Price=156.0 | 2n | PN=78.0
[231/500] row 230 | Budapest     | Price=241.0 | 2n | PN=120.5
[232/500] row 231 | Budapest     | Price=250.0 | 2n | PN=125.0
[233/500] row 232 | Budapest     | Price=223.0 | 2n | PN=111.5
[234/500] row 233 | Budapest     | Price=437.0 | 2n | PN=218.5
[235/500] row 234 | Budapest     | Price=273.0 | 2n | PN=136.5
[236/500] row 235 | Budapest     | Price=318.0 | 2n | PN=159.0
[237/500] row 236 | Budapest     | Price=366.0 | 2n | PN=183.0
[238/500] row 237 | Budapest     | Price=361.0 | 2n | PN=180.5
[239/500] row 238 | Budapest     | Price=240.0 | 2n | PN=120.0
[240/500] row 239 | Budapest     | Price=538.0 | 2n | PN=269.0
[241/500] row 240 | Budapest     | Price=204.0 | 2n | PN=102.0
[242/500] row 241 | Budapest     | Price=358.0 | 2n | PN=179.0
[243/500] row 242 | Budapest     | Price=272.0 | 2n | PN=136.0
[244/500] row 243 | Budapest     | Price=419.0 | 2n | PN=209.5
[245/500] row 244 | Budapest     | Price=178.0 | 2n | PN=89.0
[246/500] row 245 | Budapest     | Price=380.0 | 2n | PN=190.0
[247/500] row 246 | Budapest     | Price=179.0 | 2n | PN=89.5
[248/500] row 247 | Budapest     | Price=162.0 | 2n | PN=81.0
[249/500] row 248 | Budapest     | Price=443.0 | 2n | PN=221.5
[250/500] row 249 | Budapest     | Price=649.0 | 2n | PN=324.5
   ↳ checkpoint saved (250/500)
[251/500] row 250 | Lisbon       | Price=333.0 | 2n | PN=166.5
[252/500] row 251 | Lisbon       | Price=232.0 | 2n | PN=116.0
[253/500] row 252 | Lisbon       | Price=240.0 | 2n | PN=120.0
[254/500] row 253 | Lisbon       | Price=359.0 | 2n | PN=179.5
[255/500] row 254 | Lisbon       | Price=308.0 | 2n | PN=154.0
[256/500] row 255 | Lisbon       | Price=323.0 | 2n | PN=161.5
[257/500] row 256 | Lisbon       | Price=333.0 | 2n | PN=166.5
[258/500] row 257 | Lisbon       | Price=284.0 | 2n | PN=142.0
[259/500] row 258 | Lisbon       | Price=310.0 | 2n | PN=155.0
[260/500] row 259 | Lisbon       | Price=271.0 | 2n | PN=135.5
[261/500] row 260 | Lisbon       | Price=311.0 | 2n | PN=155.5
[262/500] row 261 | Lisbon       | Price=308.0 | 2n | PN=154.0
[263/500] row 262 | Lisbon       | Price=334.0 | 2n | PN=167.0
[264/500] row 263 | Lisbon       | Price=230.0 | 2n | PN=115.0
[265/500] row 264 | Lisbon       | Price=222.0 | 2n | PN=111.0
[266/500] row 265 | Lisbon       | Price=352.0 | 2n | PN=176.0
[267/500] row 266 | Lisbon       | Price=326.0 | 2n | PN=163.0
[268/500] row 267 | Lisbon       | Price=485.0 | 2n | PN=242.5
[269/500] row 268 | Lisbon       | Price=382.0 | 2n | PN=191.0
[270/500] row 269 | Lisbon       | Price=268.0 | 2n | PN=134.0
[271/500] row 270 | Lisbon       | Price=441.0 | 2n | PN=220.5
[272/500] row 271 | Lisbon       | Price=227.0 | 2n | PN=113.5
[273/500] row 272 | Lisbon       | Price=311.0 | 2n | PN=155.5
[274/500] row 273 | Lisbon       | Price=333.0 | 2n | PN=166.5
[275/500] row 274 | Lisbon       | Price=321.0 | 2n | PN=160.5
   ↳ checkpoint saved (275/500)
[276/500] row 275 | Lisbon       | Price=266.0 | 2n | PN=133.0
[277/500] row 276 | Lisbon       | Price=368.0 | 2n | PN=184.0
[278/500] row 277 | Lisbon       | Price=269.0 | 2n | PN=134.5
[279/500] row 278 | Lisbon       | Price=297.0 | 2n | PN=148.5
[280/500] row 279 | Lisbon       | Price=308.0 | 2n | PN=154.0
[281/500] row 280 | Lisbon       | Price=286.0 | 2n | PN=143.0
[282/500] row 281 | Lisbon       | Price=283.0 | 2n | PN=141.5
[283/500] row 282 | Lisbon       | Price=420.0 | 2n | PN=210.0
[284/500] row 283 | Lisbon       | Price=389.0 | 2n | PN=194.5
[285/500] row 284 | Lisbon       | Price=235.0 | 2n | PN=117.5
[286/500] row 285 | Lisbon       | Price=304.0 | 2n | PN=152.0
[287/500] row 286 | Lisbon       | Price=308.0 | 2n | PN=154.0
[288/500] row 287 | Lisbon       | Price=420.0 | 2n | PN=210.0
[289/500] row 288 | Lisbon       | Price=297.0 | 2n | PN=148.5
[290/500] row 289 | Lisbon       | Price=346.0 | 2n | PN=173.0
[291/500] row 290 | Lisbon       | Price=328.0 | 2n | PN=164.0
[292/500] row 291 | Lisbon       | Price=512.0 | 2n | PN=256.0
[293/500] row 292 | Lisbon       | Price=292.0 | 2n | PN=146.0
[294/500] row 293 | Lisbon       | Price=326.0 | 2n | PN=163.0
[295/500] row 294 | Lisbon       | Price=335.0 | 2n | PN=167.5
[296/500] row 295 | Lisbon       | Price=426.0 | 2n | PN=213.0
[297/500] row 296 | Lisbon       | Price=269.0 | 2n | PN=134.5
[298/500] row 297 | Lisbon       | Price=276.0 | 2n | PN=138.0
[299/500] row 298 | Lisbon       | Price=493.0 | 2n | PN=246.5
[300/500] row 299 | Lisbon       | Price=280.0 | 2n | PN=140.0
   ↳ checkpoint saved (300/500)
[301/500] row 300 | London       | Price=930.0 | 2n | PN=465.0
[302/500] row 301 | London       | Price=1190.0 | 2n | PN=595.0
[303/500] row 302 | London       | Price=467.0 | 2n | PN=233.5
[304/500] row 303 | London       | Price=None | 2n | PN=nan
[305/500] row 304 | London       | Price=842.0 | 2n | PN=421.0
[306/500] row 305 | London       | Price=400.0 | 2n | PN=200.0
[307/500] row 306 | London       | Price=1676.0 | 2n | PN=838.0
[308/500] row 307 | London       | Price=493.0 | 2n | PN=246.5
[309/500] row 308 | London       | Price=552.0 | 2n | PN=276.0
[310/500] row 309 | London       | Price=806.0 | 2n | PN=403.0
[311/500] row 310 | London       | Price=879.0 | 2n | PN=439.5
[312/500] row 311 | London       | Price=675.0 | 2n | PN=337.5

In [ ]:
# =====================================================
#  MERGED PRICED CSV → ADD GEOPGRAPHIC + RATING FEATURES
#  Adds: biz, guest_satisfaction_overall, dist, metro_dist,
#        attr_index, attr_index_norm, rest_index, rest_index_norm
#  Reads priced CSV in place, writes back (or to _enriched)
# =====================================================
import re, json, time, math, random, os
from pathlib import Path
from urllib.parse import urlparse, parse_qs
from datetime import datetime

import pandas as pd
import requests
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from seleniumbase import Driver

# ---------------- CONFIG ----------------
INPUT_CSV         = "/content/drive/MyDrive/my.flutter.2025/Instant_ai_training/SPRINT_01/airbnb_listings_weekdays_priced.csv"     # priced, ready
OUTPUT_CSV        = "/content/drive/MyDrive/my.flutter.2025/Instant_ai_training/SPRINT_01/airbnb_listings_weekdays_priced_enriched.csv"
OVERPASS_CACHE    = "/content/overpass_cache.json"
POI_RADIUS_KM     = 1.5
SLEEP_BETWEEN     = (1.5, 3.0)     # between URL loads
OVERPASS_SLEEP    = 1.2            # between Overpass requests
CHECKPOINT_EVERY  = 25
HEADLESS          = True
FORCE_REFRESH     = False          # True → re-scrape even if column already has value

OVERPASS_ENDPOINTS = [
    "https://overpass-api.de/api/interpreter",
    "https://overpass.kumi.systems/api/interpreter",
    "https://overpass.openstreetmap.ru/api/interpreter",
]

CITY_CENTRES = {
    "Amsterdam": (52.3676, 4.9041),
    "Athens":    (37.9838, 23.7275),
    "Barcelona": (41.3874, 2.1686),
    "Berlin":    (52.5200, 13.4050),
    "Budapest":  (47.4979, 19.0402),
    "Lisbon":    (38.7223, -9.1393),
    "London":    (51.5074, -0.1278),
    "Paris":     (48.8566, 2.3522),
    "Rome":      (41.9028, 12.4964),
    "Vienna":    (48.2082, 16.3738),
}

TARGET_COLS = [
    "biz", "guest_satisfaction_overall",
    "dist", "metro_dist",
    "attr_index", "attr_index_norm",
    "rest_index", "rest_index_norm",
]

# ---------------- HELPERS ----------------
def safe_get(d, path, default=None):
    cur = d
    for p in path:
        if isinstance(cur, dict):
            cur = cur.get(p)
        elif isinstance(cur, list) and isinstance(p, int) and 0 <= p < len(cur):
            cur = cur[p]
        else:
            return default
        if cur is None:
            return default
    return cur

def get_json_ld(driver):
    out = []
    try:
        for s in driver.find_elements(By.CSS_SELECTOR, 'script[type="application/ld+json"]'):
            try:
                out.append(json.loads(s.get_attribute("textContent")))
            except Exception:
                pass
    except Exception:
        pass
    return out

def rating_from_ld(ld_list):
    """Extract ratingValue (0-5) from JSON-LD aggregateRating."""
    for obj in ld_list:
        if not isinstance(obj, dict):
            continue
        agg = obj.get("aggregateRating")
        if isinstance(agg, dict):
            rv = agg.get("ratingValue")
            if rv is not None:
                try:
                    v = float(rv)
                    if v > 0:
                        return v
                except Exception:
                    pass
    return None

def haversine_km(lat1, lon1, lat2, lon2):
    R = 6371.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp = math.radians(lat2 - lat1)
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp/2)**2 + math.cos(p1)*math.cos(p2)*math.sin(dl/2)**2
    return 2 * R * math.asin(math.sqrt(a))

# ---- Overpass with cache ----
def load_cache():
    if os.path.exists(OVERPASS_CACHE):
        try:
            with open(OVERPASS_CACHE) as f:
                return json.load(f)
        except Exception:
            return {}
    return {}

def save_cache(c):
    try:
        with open(OVERPASS_CACHE, "w") as f:
            json.dump(c, f)
    except Exception:
        pass

OVERPASS_CACHE_DATA = load_cache()

def _cache_key(lat, lon, kind):
    # round to ~11m precision to allow reuse
    return f"{round(lat, 4)}_{round(lon, 4)}_{kind}"

def _overpass(query, retries=3):
    for url in OVERPASS_ENDPOINTS:
        for attempt in range(retries):
            try:
                r = requests.post(url, data={"data": query}, timeout=60)
                if r.status_code == 200:
                    return r.json()
            except Exception:
                pass
            time.sleep(2 ** attempt)
    return None

def _count_pois(lat, lon, radius_km, tags_block):
    r = int(radius_km * 1000)
    q = f"""
    [out:json][timeout:25];
    (
      node{tags_block}(around:{r},{lat},{lon});
      way{tags_block}(around:{r},{lat},{lon});
    );
    out count;
    """
    data = _overpass(q)
    if not data:
        return None
    try:
        return int(data["elements"][0]["tags"]["total"])
    except Exception:
        return 0

def metro_dist_km(lat, lon, max_radius_km=5.0):
    r = int(max_radius_km * 1000)
    q = f"""
    [out:json][timeout:25];
    (
      node["railway"="station"]["station"="subway"](around:{r},{lat},{lon});
      node["railway"="subway_entrance"](around:{r},{lat},{lon});
      node["public_transport"="station"]["subway"="yes"](around:{r},{lat},{lon});
    );
    out body;
    """
    data = _overpass(q)
    if not data or not data.get("elements"):
        return None
    return round(min(haversine_km(lat, lon, el["lat"], el["lon"])
                     for el in data["elements"]), 3)

def get_geo_features(lat, lon):
    """Returns dict with metro_dist, attr_index, rest_index (with caching)."""
    out = {"metro_dist": None, "attr_index": None, "rest_index": None}
    for kind, fn in (
        ("metro", lambda: metro_dist_km(lat, lon)),
        ("attr",  lambda: _count_pois(lat, lon, POI_RADIUS_KM,
                     '["tourism"~"attraction|museum|viewpoint|artwork|gallery"]')),
        ("rest",  lambda: _count_pois(lat, lon, POI_RADIUS_KM,
                     '["amenity"~"restaurant|cafe|bar|fast_food|pub"]')),
    ):
        key = _cache_key(lat, lon, kind)
        if key in OVERPASS_CACHE_DATA:
            val = OVERPASS_CACHE_DATA[key]
        else:
            val = fn()
            OVERPASS_CACHE_DATA[key] = val
            time.sleep(OVERPASS_SLEEP)
        if kind == "metro":
            out["metro_dist"] = val
        elif kind == "attr":
            out["attr_index"] = val
        else:
            out["rest_index"] = val
    return out

def minmax(s):
    s = pd.to_numeric(s, errors="coerce")
    lo, hi = s.min(), s.max()
    if pd.isna(lo) or hi == lo:
        return s * 0
    return (s - lo) / (hi - lo) * 100

def already_has(row):
    """Row is done if all TARGET_COLS are filled."""
    for c in TARGET_COLS:
        v = row.get(c)
        if v is None or (isinstance(v, float) and pd.isna(v)):
            return False
    return True

# ---------------- MAIN ----------------
def main():
    df = pd.read_csv(INPUT_CSV, encoding="utf-8-sig")
    for c in TARGET_COLS:
        if c not in df.columns:
            df[c] = None

    total = len(df)
    print(f"Total rows: {total}")

    # ---- 1. biz: host listing count (from dataset itself; no scraping) ----
    print("\n[1/4] Computing 'biz' (host listing count)…")
    host_counts = df["HostName"].fillna("__unknown__").value_counts()
    df["biz"] = df["HostName"].map(host_counts).fillna(1).astype("Int64")
    df.loc[df["biz"] > 1, "biz"] = 1          # binary: 1 = commercial operator
    df.loc[df["HostName"].isna(), "biz"] = pd.NA
    print(f"  biz=1 count: {int((df['biz'] == 1).sum())}")
    print(f"  biz=0 count: {int((df['biz'] == 0).sum())}")

    # ---- 2. dist: to city centre (from dataset lat/lng) ----
    print("\n[2/4] Computing 'dist' (haversine to city centre)…")
    for i, row in df.iterrows():
        lat, lng = row.get("Latitude"), row.get("Longitude")
        if pd.isna(lat) or pd.isna(lng):
            continue
        city = str(row.get("city", "")).strip()
        centre = CITY_CENTRES.get(city)
        if centre is None:
            sub = df[df["city"] == city][["Latitude","Longitude"]].dropna()
            if len(sub):
                centre = (sub["Latitude"].median(), sub["Longitude"].median())
        if centre is None:
            continue
        df.at[i, "dist"] = round(haversine_km(lat, lng, *centre), 3)
    print(f"  filled: {int(df['dist'].notna().sum())}/{total}")

    # ---- 3. per-row: rating (URL) + Overpass features ----
    print("\n[3/4] Per-row scraping (rating from URL) + geo enrichment…")
    todo = [i for i in df.index if not already_has(df.loc[i])]
    if FORCE_REFRESH:
        todo = list(df.index)
    print(f"  rows to process: {len(todo)}")

    driver = Driver(browser="chrome", headless=HEADLESS)
    driver.set_window_size(1920, 1080)
    wait = WebDriverWait(driver, 10)

    try:
        for n, i in enumerate(todo, 1):
            url = df.at[i, "URL"]
            if not isinstance(url, str) or "airbnb" not in url:
                print(f"[{n}/{len(todo)}] row {i}: no URL, skip")
                continue

            lat = df.at[i, "Latitude"]
            lng = df.at[i, "Longitude"]

            # (a) rating from URL
            rating = None
            try:
                driver.get(url)
                wait.until(EC.presence_of_element_located((By.TAG_NAME, "h1")))
                time.sleep(random.uniform(*SLEEP_BETWEEN))
                ld = get_json_ld(driver)
                rating = rating_from_ld(ld)
            except Exception as e:
                print(f"[{n}/{len(todo)}] row {i}: rating scrape failed: {type(e).__name__}")

            # fallback: Rating from CSV
            if rating is None:
                r = df.at[i, "Rating"] if "Rating" in df.columns else None
                if pd.notna(r):
                    rating = float(r)
            if rating is not None:
                df.at[i, "guest_satisfaction_overall"] = round(rating * 20, 2)

            # (b) geo features from lat/lng
            if pd.notna(lat) and pd.notna(lng):
                try:
                    geo = get_geo_features(lat, lng)
                    df.at[i, "metro_dist"]  = geo["metro_dist"]
                    df.at[i, "attr_index"]  = geo["attr_index"]
                    df.at[i, "rest_index"]  = geo["rest_index"]
                except Exception as e:
                    print(f"[{n}/{len(todo)}] row {i}: overpass failed: {type(e).__name__}")

            print(f"[{n}/{len(todo)}] row {i:>3} | rating={df.at[i,'guest_satisfaction_overall']} "
                  f"| dist={df.at[i,'dist']} | metro={df.at[i,'metro_dist']} "
                  f"| attr={df.at[i,'attr_index']} | rest={df.at[i,'rest_index']}")

            if n % CHECKPOINT_EVERY == 0:
                save_cache(OVERPASS_CACHE_DATA)
                df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")
                print(f"   ↳ checkpoint saved ({n}/{len(todo)})")
    finally:
        try:
            driver.quit()
        except Exception:
            pass
        save_cache(OVERPASS_CACHE_DATA)

    # ---- 4. normalise ----
    print("\n[4/4] Normalising attr_index_norm / rest_index_norm…")
    df["attr_index_norm"] = minmax(df["attr_index"]).round(2)
    df["rest_index_norm"] = minmax(df["rest_index"]).round(2)

    df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")
    print(f"\nDONE → {OUTPUT_CSV}")
    for c in TARGET_COLS:
        print(f"  {c:<28} filled: {int(df[c].notna().sum())}/{total}")

if __name__ == "__main__":
    main()

Total rows: 500

[1/4] Computing 'biz' (host listing count)…
  biz=1 count: 499
  biz=0 count: 0

[2/4] Computing 'dist' (haversine to city centre)…
  filled: 499/500

[3/4] Per-row scraping (rating from URL) + geo enrichment…
  rows to process: 500

Warning: INFO: chromedriver not found. Getting it now:

*** Getting chromedriver 155.0.8059.84 (Latest Stable)

Downloading chromedriver-linux64.zip from:
https://storage.googleapis.com/chrome-for-testing-public/155.0.8059.84/linux64/chromedriver-linux64.zip ...
Download Complete!

Extracting ['chromedriver'] from chromedriver-linux64.zip:
Unzip Complete!

['chromedriver'] was saved to:
/usr/local/lib/python3.13/dist-packages/seleniumbase/drivers/
chromedriver

[chromedriver 155.0.8059.84] is ready for use!

[1/500] row   0 | rating=99.4 | dist=1.596 | metro=None | attr=None | rest=None
[2/500] row   1 | rating=94.8 | dist=4.954 | metro=None | attr=None | rest=None
[3/500] row   2 | rating=100.0 | dist=19.868 | metro=None | attr=None | rest=None
[4/500] row   3 | rating=72.0 | dist=2.725 | metro=None | attr=None | rest=None
[5/500] row   4 | rating=100.0 | dist=15.168 | metro=None | attr=None | rest=None
[6/500] row   5 | rating=100.0 | dist=9.313 | metro=None | attr=None | rest=None
[7/500] row   6 | rating=100.0 | dist=15.421 | metro=None | attr=None | rest=None
[8/500] row   7 | rating=94.6 | dist=14.361 | metro=None | attr=None | rest=None
[9/500] row   8 | rating=99.8 | dist=15.377 | metro=None | attr=None | rest=None
[10/500] row   9 | rating=97.4 | dist=1.374 | metro=None | attr=None | rest=None
[11/500] row  10 | rating=87.0 | dist=3.158 | metro=None | attr=None | rest=None
[12/500] row  11 | rating=0.0 | dist=3.216 | metro=1.457 | attr=None | rest=None
[13/500] row  12 | rating=98.4 | dist=16.928 | metro=None | attr=None | rest=None
[14/500] row  13 | rating=100.0 | dist=1.359 | metro=None | attr=None | rest=None
[15/500] row  14 | rating=97.6 | dist=15.193 | metro=None | attr=None | rest=None
[16/500] row  15 | rating=100.0 | dist=10.656 | metro=None | attr=None | rest=None
[17/500] row  16 | rating=98.4 | dist=2.574 | metro=None | attr=None | rest=None
[18/500] row  17 | rating=84.8 | dist=10.653 | metro=None | attr=None | rest=None
[19/500] row  18 | rating=99.8 | dist=3.112 | metro=None | attr=None | rest=None
[20/500] row  19 | rating=98.8 | dist=1.865 | metro=None | attr=None | rest=None
[21/500] row  20 | rating=0.0 | dist=1.098 | metro=None | attr=None | rest=None
[22/500] row  21 | rating=97.2 | dist=0.874 | metro=None | attr=None | rest=None
[23/500] row  22 | rating=95.2 | dist=5.607 | metro=None | attr=None | rest=None
[24/500] row  23 | rating=99.2 | dist=21.478 | metro=None | attr=None | rest=None
[25/500] row  24 | rating=100.0 | dist=21.332 | metro=None | attr=None | rest=None
   ↳ checkpoint saved (25/500)
[26/500] row  25 | rating=90.4 | dist=3.158 | metro=None | attr=None | rest=None
[27/500] row  26 | rating=98.6 | dist=13.802 | metro=None | attr=None | rest=None
[28/500] row  27 | rating=99.6 | dist=11.621 | metro=None | attr=None | rest=None

In [ ]:
# =====================================================
#  ENRICH PRICED CSV  (fixed: tiled Overpass, fast URL)
#  Columns added:
#    biz, guest_satisfaction_overall, dist, metro_dist,
#    attr_index, attr_index_norm, rest_index, rest_index_norm
# =====================================================
import os, json, time, math, random
from datetime import datetime

import numpy as np
import pandas as pd
import requests
from selenium.common.exceptions import TimeoutException, WebDriverException
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from seleniumbase import Driver

# ---------------- CONFIG ----------------
INPUT_CSV       = "/content/drive/MyDrive/my.flutter.2025/Instant_ai_training/SPRINT_01/airbnb_listings_weekdays_priced.csv"
OUTPUT_CSV      = "/content/drive/MyDrive/my.flutter.2025/Instant_ai_training/SPRINT_01/airbnb_listings_weekdays_priced_enriched.csv"
POI_CACHE       = "/content/poi_cache_v2.json"

USE_CSV_RATING  = False     # set True → skip URL entirely, use Rating×20 (finishes in ~2 min)
FORCE_REFRESH   = False     # True → ignore POI cache
HEADLESS        = True

SLEEP_BETWEEN   = (1.0, 2.5)
PAGE_LOAD_TIMEOUT = 20      # ⭐ hard cap per URL (was ~300 s!)
URL_WAIT_JSONLD   = 6       # seconds to wait for JSON-LD script tag
FAILSTREAK_LIMIT  = 10      # ⭐ after N consecutive URL failures, fall back to CSV

OVERPASS_ENDPOINTS = [
    "https://overpass.kumi.systems/api/interpreter",   # most reliable
    "https://overpass-api.de/api/interpreter",
    "https://overpass.private.coffee/api/interpreter",
]
OVERPASS_SLEEP   = 0.4
POI_RADIUS_KM    = 1.5
TILE_DEG         = 0.05    # ⭐ ~5.5 km tiles → keeps Overpass queries tiny
CITY_BUFFER_DEG  = 0.03

CITY_CENTRES = {
    "Amsterdam": (52.3676, 4.9041),  "Athens":    (37.9838, 23.7275),
    "Barcelona": (41.3874, 2.1686),  "Berlin":    (52.5200, 13.4050),
    "Budapest":  (47.4979, 19.0402), "Lisbon":    (38.7223, -9.1393),
    "London":    (51.5074, -0.1278), "Paris":     (48.8566, 2.3522),
    "Rome":      (41.9028, 12.4964), "Vienna":    (48.2082, 16.3738),
}

TARGET_COLS = ["biz","guest_satisfaction_overall","dist","metro_dist",
               "attr_index","attr_index_norm",
               "rest_index","rest_index_norm"]

# ---------------- UTIL ----------------
def haversine_km(lat1, lon1, lat2, lon2):
    R=6371.0
    p1,p2=math.radians(lat1),math.radians(lat2)
    dp=math.radians(lat2-lat1); dl=math.radians(lon2-lon1)
    a=math.sin(dp/2)**2+math.cos(p1)*math.cos(p2)*math.sin(dl/2)**2
    return 2*R*math.asin(math.sqrt(a))

def haversine_vec(lat1, lon1, lats, lons):
    if not len(lats): return np.array([])
    R=6371.0
    lat1r=math.radians(lat1); lon1r=math.radians(lon1)
    latr=np.radians(np.asarray(lats,float)); lonr=np.radians(np.asarray(lons,float))
    dlat=latr-lat1r; dlon=lonr-lon1r
    a=np.sin(dlat/2)**2+np.cos(lat1r)*np.cos(latr)*np.sin(dlon/2)**2
    return 2*R*np.arcsin(np.sqrt(a))

def minmax(s):
    s=pd.to_numeric(s,errors="coerce")
    lo,hi=s.min(),s.max()
    if pd.isna(lo) or hi==lo: return s*0
    return (s-lo)/(hi-lo)*100

# ---------------- OVERPASS ----------------
def _load_cache():
    if os.path.exists(POI_CACHE):
        try:
            with open(POI_CACHE) as f: return json.load(f)
        except Exception: return {}
    return {}

def _save_cache(c):
    try:
        with open(POI_CACHE,"w") as f: json.dump(c,f)
    except Exception: pass

CACHE = _load_cache()

def _overpass(query, timeout=30, retries=2):
    for url in OVERPASS_ENDPOINTS:
        for attempt in range(retries):
            try:
                r = requests.post(url, data={"data": query}, timeout=timeout)
                if r.status_code == 200:
                    return r.json()
                if r.status_code in (429, 504):
                    break           # move to next mirror
            except Exception:
                pass
            time.sleep(1.5 * (attempt + 1))
    return None

def _coords_from(data):
    out=[]
    if data:
        for el in data.get("elements", []):
            la=el.get("lat") or (el.get("center") or {}).get("lat")
            lo=el.get("lon") or (el.get("center") or {}).get("lon")
            if la is not None and lo is not None:
                out.append([la,lo])
    return out

def _tiles(lat_min, lat_max, lng_min, lng_max):
    tiles=[]; la=lat_min
    while la < lat_max:
        lo=lng_min
        while lo < lng_max:
            tiles.append((la, lo, min(la+TILE_DEG, lat_max), min(lo+TILE_DEG, lng_max)))
            lo += TILE_DEG
        la += TILE_DEG
    return tiles

def fetch_city_pois(city, sub):
    key=f"pois_v2::{city}"
    if key in CACHE and not FORCE_REFRESH:
        c = CACHE[key]
        print(f"   {city}: cached (attr={len(c['attr'])}, rest={len(c['rest'])}, metro={len(c['metro'])})")
        return c

    lats=sub["Latitude"].dropna(); lngs=sub["Longitude"].dropna()
    if len(lats)==0:
        return {"attr": [], "rest": [], "metro": []}

    tiles = _tiles(float(lats.min())-CITY_BUFFER_DEG, float(lats.max())+CITY_BUFFER_DEG,
                   float(lngs.min())-CITY_BUFFER_DEG, float(lngs.max())+CITY_BUFFER_DEG)
    print(f"   {city}: {len(tiles)} tiles")

    specs = {
        # ⭐ node-only + smaller tagset = 10–50× smaller Overpass payloads
        "attr":  '["tourism"~"attraction|museum|viewpoint|gallery"]',
        "rest":  '["amenity"~"restaurant|cafe|bar"]',
        "metro": '["railway"="station"]["station"="subway"]',
    }
    out = {k: [] for k in specs}

    for kind, tags in specs.items():
        for (la1,lo1,la2,lo2) in tiles:
            q = f'[out:json][timeout:20];node{tags}({la1},{lo1},{la2},{lo2});out body;'
            out[kind].extend(_coords_from(_overpass(q, timeout=25)))
            time.sleep(OVERPASS_SLEEP)
        # add subway entrances separately
        if kind == "metro":
            for (la1,lo1,la2,lo2) in tiles:
                q = f'[out:json][timeout:20];node["railway"="subway_entrance"]({la1},{lo1},{la2},{lo2});out body;'
                out[kind].extend(_coords_from(_overpass(q, timeout=25)))
                time.sleep(OVERPASS_SLEEP)
        print(f"   {city}: {kind} = {len(out[kind])} POIs")

    CACHE[key]=out; _save_cache(CACHE)
    return out

# ---------------- URL SCRAPER ----------------
def _json_ld(driver):
    out=[]
    try:
        for s in driver.find_elements(By.CSS_SELECTOR,'script[type="application/ld+json"]'):
            try: out.append(json.loads(s.get_attribute("textContent")))
            except Exception: pass
    except Exception: pass
    return out

def _rating_from_ld(ld):
    for obj in ld:
        if not isinstance(obj, dict): continue
        agg=obj.get("aggregateRating")
        if isinstance(agg, dict):
            rv=agg.get("ratingValue")
            if rv is not None:
                try:
                    v=float(rv)
                    if v>0: return v
                except Exception: pass
    return None

def make_driver():
    # ⭐ the three lines that fix the 6-min-per-row hang
    d = Driver(
        browser="chrome",
        headless=HEADLESS,
        page_load_strategy="eager",
        disable_images=True,
        ad_block_on=True,
    )
    d.set_window_size(1600, 1000)
    d.set_page_load_timeout(PAGE_LOAD_TIMEOUT)
    return d

def fetch_rating(driver, url):
    try:
        driver.get(url)
    except TimeoutException:
        # page didn't finish loading — but JSON-LD is usually in <head>, already there
        try: driver.execute_script("window.stop();")
        except Exception: pass
    except WebDriverException:
        return None

    # ⭐ wait for JSON-LD tag, not <h1> — the <h1> is client-rendered and slow
    try:
        WebDriverWait(driver, URL_WAIT_JSONLD).until(
            EC.presence_of_element_located((By.CSS_SELECTOR,'script[type="application/ld+json"]'))
        )
    except TimeoutException:
        pass
    return _rating_from_ld(_json_ld(driver))

# ---------------- MAIN ----------------
def main():
    df = pd.read_csv(INPUT_CSV, encoding="utf-8-sig")
    for c in TARGET_COLS:
        if c not in df.columns: df[c]=None
    total = len(df)
    print(f"Total rows: {total}\n")

    # --- 1. biz ---
    print("[1/5] biz (host has >1 listing)…")
    hc = df["HostName"].fillna("__unknown__").value_counts()
    df["biz"] = df["HostName"].map(hc).fillna(1).astype("Int64").clip(upper=1)
    df.loc[df["HostName"].isna(),"biz"]=pd.NA
    print(f"  biz=1: {int((df['biz']==1).sum())}   biz=0: {int((df['biz']==0).sum())}")

    # --- 2. dist ---
    print("\n[2/5] dist (km to city centre)…")
    for i,row in df.iterrows():
        lat,lng=row.get("Latitude"),row.get("Longitude")
        if pd.isna(lat) or pd.isna(lng): continue
        city=str(row.get("city","")).strip()
        centre=CITY_CENTRES.get(city)
        if centre is None:
            sub=df[df["city"]==city][["Latitude","Longitude"]].dropna()
            if len(sub): centre=(sub["Latitude"].median(),sub["Longitude"].median())
        if centre is None: continue
        df.at[i,"dist"]=round(haversine_km(lat,lng,*centre),3)
    print(f"  filled: {int(df['dist'].notna().sum())}/{total}")

    # --- 3. POIs per city (tiled Overpass) ---
    print("\n[3/5] Fetching POIs per city (tiled Overpass)…")
    city_pois={}
    for city in df["city"].dropna().unique():
        city_pois[city]=fetch_city_pois(city, df[df["city"]==city])

    # --- 4. Per-row: rating (URL or CSV) + geo ---
    print("\n[4/5] Per-row: rating + geo features…")
    need_url = (not USE_CSV_RATING)
    driver = make_driver() if need_url else None
    fail_streak = 0
    url_disabled = False

    try:
        for n,i in enumerate(df.index,1):
            lat=df.at[i,"Latitude"]; lng=df.at[i,"Longitude"]
            city=df.at[i,"city"]

            # (a) rating
            if (not url_disabled) and pd.isna(df.at[i,"guest_satisfaction_overall"]):
                url=df.at[i,"URL"]; rating=None
                if isinstance(url,str) and "airbnb" in url and driver:
                    rating=fetch_rating(driver,url)
                    time.sleep(random.uniform(*SLEEP_BETWEEN))

                if rating is None:
                    fail_streak+=1
                    if fail_streak>=FAILSTREAK_LIMIT and not url_disabled:
                        print(f"⚠️  {FAILSTREAK_LIMIT} URL failures in a row — "
                              f"switching to CSV Rating for the rest.")
                        url_disabled=True
                else:
                    fail_streak=0
                    df.at[i,"guest_satisfaction_overall"]=round(rating*20,2)

                if rating is None and "Rating" in df.columns and pd.notna(df.at[i,"Rating"]):
                    df.at[i,"guest_satisfaction_overall"]=round(float(df.at[i,"Rating"])*20,2)

            # (b) geo
            pois=city_pois.get(city) or {"attr":[],"rest":[],"metro":[]}
            if pd.notna(lat) and pd.notna(lng):
                if pois["metro"]:
                    d=haversine_vec(lat,lng,[p[0] for p in pois["metro"]],
                                         [p[1] for p in pois["metro"]])
                    df.at[i,"metro_dist"]=round(float(d.min()),3)
                else:
                    df.at[i,"metro_dist"]=np.nan

                if pois["attr"]:
                    d=haversine_vec(lat,lng,[p[0] for p in pois["attr"]],
                                         [p[1] for p in pois["attr"]])
                    df.at[i,"attr_index"]=int((d<=POI_RADIUS_KM).sum())
                else:
                    df.at[i,"attr_index"]=0

                if pois["rest"]:
                    d=haversine_vec(lat,lng,[p[0] for p in pois["rest"]],
                                         [p[1] for p in pois["rest"]])
                    df.at[i,"rest_index"]=int((d<=POI_RADIUS_KM).sum())
                else:
                    df.at[i,"rest_index"]=0

            if n%25==0 or n==total:
                print(f"[{n}/{total}] row {i:>3} | "
                      f"rating={df.at[i,'guest_satisfaction_overall']} | "
                      f"dist={df.at[i,'dist']} | metro={df.at[i,'metro_dist']} | "
                      f"attr={df.at[i,'attr_index']} | rest={df.at[i,'rest_index']}")

            if n%CHECKPOINT_EVERY==0 if 'CHECKPOINT_EVERY' in dir() else n%25==0:
                df.to_csv(OUTPUT_CSV,index=False,encoding="utf-8-sig")
                _save_cache(CACHE)
    finally:
        if driver:
            try: driver.quit()
            except Exception: pass
        _save_cache(CACHE)

    # --- 5. normalise ---
    print("\n[5/5] Normalising…")
    df["attr_index_norm"]=minmax(df["attr_index"]).round(2)
    df["rest_index_norm"]=minmax(df["rest_index"]).round(2)

    df.to_csv(OUTPUT_CSV,index=False,encoding="utf-8-sig")
    print(f"\nDONE → {OUTPUT_CSV}")
    for c in TARGET_COLS:
        print(f"  {c:<28} filled: {int(df[c].notna().sum())}/{total}")

if __name__=="__main__":
    main()

Total rows: 500

[1/5] biz (host has >1 listing)…
  biz=1: 499   biz=0: 0

[2/5] dist (km to city centre)…
  filled: 499/500

[3/5] Fetching POIs per city (tiled Overpass)…
   Amsterdam: 104 tiles
   Amsterdam: attr = 13 POIs
   Amsterdam: rest = 145 POIs
   Amsterdam: metro = 0 POIs
   Athens: 12 tiles
   Athens: attr = 0 POIs
   Athens: rest = 0 POIs
   Athens: metro = 0 POIs
   Barcelona: 12 tiles
   Barcelona: attr = 0 POIs
   Barcelona: rest = 0 POIs
   Barcelona: metro = 0 POIs
   Berlin: 56 tiles
   Berlin: attr = 0 POIs
   Berlin: rest = 0 POIs
   Berlin: metro = 0 POIs
   Budapest: 6 tiles
   Budapest: attr = 0 POIs
   Budapest: rest = 0 POIs
   Budapest: metro = 0 POIs
   Lisbon: 12 tiles
   Lisbon: attr = 0 POIs
   Lisbon: rest = 0 POIs
   Lisbon: metro = 3 POIs
   London: 45 tiles
   London: attr = 0 POIs
   London: rest = 0 POIs
   London: metro = 0 POIs
   Paris: 32 tiles
   Paris: attr = 0 POIs
   Paris: rest = 0 POIs
   Paris: metro = 0 POIs
   Rome: 8 tiles
   Rome: attr = 0 POIs
   Rome: rest = 0 POIs
   Rome: metro = 0 POIs
   Vienna: 12 tiles
   Vienna: attr = 0 POIs
   Vienna: rest = 0 POIs
   Vienna: metro = 0 POIs

[4/5] Per-row: rating + geo features…

TypeError: Driver() got an unexpected keyword argument 'disable_images'. Did you mean 'disable_cookies'?

In [ ]:
# =====================================================
#  ENRICH PRICED CSV (v3 — Overpass rate-limit-safe)
#  Adds:
#    biz, guest_satisfaction_overall, dist, metro_dist,
#    attr_index, attr_index_norm, rest_index, rest_index_norm
# =====================================================
import os, json, time, math, random, inspect

import numpy as np
import pandas as pd
import requests
from selenium.common.exceptions import TimeoutException, WebDriverException
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from seleniumbase import Driver

# ---------------- CONFIG ----------------
INPUT_CSV       = "/content/drive/MyDrive/my.flutter.2025/Instant_ai_training/SPRINT_01/airbnb_listings_weekdays_priced.csv"
OUTPUT_CSV      = "/content/drive/MyDrive/my.flutter.2025/Instant_ai_training/SPRINT_01/airbnb_listings_weekdays_priced_enriched.csv"
POI_CACHE       = "/content/drive/MyDrive/my.flutter.2025/Instant_ai_training/SPRINT_01/poi_cache_v3.json"

USE_CSV_RATING  = False          # True → skip URL, use Rating×20 (finishes in ~2 min)
FORCE_REFRESH   = True           # True → ignore POI cache (needed for first clean run)
HEADLESS        = True

SLEEP_BETWEEN      = (1.0, 2.5)
PAGE_LOAD_TIMEOUT  = 20
URL_WAIT_JSONLD    = 6
FAILSTREAK_LIMIT   = 10
CHECKPOINT_EVERY   = 25

OVERPASS_ENDPOINTS = [
    "https://overpass-api.de/api/interpreter",      # primary (largest quota)
    "https://overpass.kumi.systems/api/interpreter",
    "https://overpass.private.coffee/api/interpreter",
]
OVERPASS_SLEEP   = 1.0           # 1 s between requests (was 0.4 — too fast)
OVERPASS_RETRIES = 3             # per endpoint, exponential 2/4/8 s
POI_RADIUS_KM    = 1.5
TILE_DEG         = 0.06          # bigger tiles, fewer requests
CITY_BUFFER_DEG  = 0.02

CITY_CENTRES = {
    "Amsterdam": (52.3676, 4.9041),  "Athens":    (37.9838, 23.7275),
    "Barcelona": (41.3874, 2.1686),  "Berlin":    (52.5200, 13.4050),
    "Budapest":  (47.4979, 19.0402), "Lisbon":    (38.7223, -9.1393),
    "London":    (51.5074, -0.1278), "Paris":     (48.8566, 2.3522),
    "Rome":      (41.9028, 12.4964), "Vienna":    (48.2082, 16.3738),
}

TARGET_COLS = ["biz","guest_satisfaction_overall","dist","metro_dist",
               "attr_index","attr_index_norm",
               "rest_index","rest_index_norm"]

# ---------------- GEOMETRY ----------------
def haversine_km(lat1, lon1, lat2, lon2):
    R=6371.0
    p1,p2=math.radians(lat1),math.radians(lat2)
    dp=math.radians(lat2-lat1); dl=math.radians(lon2-lon1)
    a=math.sin(dp/2)**2+math.cos(p1)*math.cos(p2)*math.sin(dl/2)**2
    return 2*R*math.asin(math.sqrt(a))

def haversine_vec(lat1, lon1, lats, lons):
    if not len(lats): return np.array([])
    R=6371.0
    lat1r=math.radians(lat1); lon1r=math.radians(lon1)
    latr=np.radians(np.asarray(lats,float)); lonr=np.radians(np.asarray(lons,float))
    dlat=latr-lat1r; dlon=lonr-lon1r
    a=np.sin(dlat/2)**2+np.cos(lat1r)*np.cos(latr)*np.sin(dlon/2)**2
    return 2*R*np.arcsin(np.sqrt(a))

def minmax(s):
    s=pd.to_numeric(s,errors="coerce")
    lo,hi=s.min(),s.max()
    if pd.isna(lo) or hi==lo: return s*0
    return (s-lo)/(hi-lo)*100

# ---------------- OVERPASS ----------------
def _load_cache():
    if os.path.exists(POI_CACHE):
        try:
            with open(POI_CACHE) as f: return json.load(f)
        except Exception: return {}
    return {}

def _save_cache(c):
    try:
        with open(POI_CACHE,"w") as f: json.dump(c,f)
    except Exception: pass

CACHE = _load_cache()

def _overpass(query, timeout=30, retries=OVERPASS_RETRIES):
    """Rotate endpoints × exponential backoff. Returns dict or None."""
    last_err = None
    for url in OVERPASS_ENDPOINTS:
        for attempt in range(retries):
            try:
                r = requests.post(url, data={"data": query}, timeout=timeout)
                if r.status_code == 200:
                    return r.json()
                last_err = f"HTTP {r.status_code}"
                if r.status_code == 400:
                    return None   # malformed — retrying won't help
            except Exception as e:
                last_err = f"{type(e).__name__}"
            time.sleep(2 * (attempt + 1))    # 2, 4, 8 s
    return None

def _coords_from(data):
    if not data: return []
    out=[]
    for el in data.get("elements", []):
        la=el.get("lat") or (el.get("center") or {}).get("lat")
        lo=el.get("lon") or (el.get("center") or {}).get("lon")
        if la is not None and lo is not None:
            out.append([la,lo])
    return out

def _tiles_with_listings(pts, lat_min, lat_max, lng_min, lng_max):
    """Only tiles that actually contain ≥1 listing → 5–10× fewer requests."""
    tiles=[]
    la=lat_min
    while la < lat_max:
        lo=lng_min
        while lo < lng_max:
            la2=min(la+TILE_DEG, lat_max)
            lo2=min(lo+TILE_DEG, lng_max)
            if any(la <= p[0] < la2 and lo <= p[1] < lo2 for p in pts):
                tiles.append((la,lo,la2,lo2))
            lo += TILE_DEG
        la += TILE_DEG
    return tiles

def fetch_city_pois(city, sub):
    key=f"pois_v3::{city}"
    if not FORCE_REFRESH and key in CACHE:
        c=CACHE[key]
        print(f"   {city}: cached (attr={len(c['attr'])}, "
              f"rest={len(c['rest'])}, metro={len(c['metro'])})")
        return c

    pts = sub[["Latitude","Longitude"]].dropna().values.tolist()
    if not pts:
        return {"attr":[], "rest":[], "metro":[]}

    lats=[p[0] for p in pts]; lngs=[p[1] for p in pts]
    tiles = _tiles_with_listings(
        pts,
        min(lats)-CITY_BUFFER_DEG, max(lats)+CITY_BUFFER_DEG,
        min(lngs)-CITY_BUFFER_DEG, max(lngs)+CITY_BUFFER_DEG,
    )
    print(f"   {city}: {len(tiles)} tiles (filtered to listings)")

    specs = {
        # nwr = nodes + ways + relations → catches ways-mapped POIs too
        "attr":  '["tourism"~"attraction|museum|viewpoint|gallery"]',
        "rest":  '["amenity"~"restaurant|cafe|bar"]',
        "metro": '["railway"="station"]["station"="subway"]',
    }
    out = {k: [] for k in specs}
    errors = {k: 0 for k in specs}

    for kind, tags in specs.items():
        for (la1,lo1,la2,lo2) in tiles:
            q = f'[out:json][timeout:25];nwr{tags}({la1},{lo1},{la2},{lo2});out center;'
            data = _overpass(q, timeout=30)
            if data is None:
                errors[kind] += 1
            else:
                out[kind].extend(_coords_from(data))
            time.sleep(OVERPASS_SLEEP)
        # subway entrances separately (different tag)
        if kind == "metro":
            for (la1,lo1,la2,lo2) in tiles:
                q = (f'[out:json][timeout:20];'
                     f'nwr["railway"="subway_entrance"]({la1},{lo1},{la2},{lo2});out center;')
                data = _overpass(q, timeout=25)
                if data is None:
                    errors[kind] += 1
                else:
                    out[kind].extend(_coords_from(data))
                time.sleep(OVERPASS_SLEEP)

        fail_pct = errors[kind] / max(len(tiles), 1) * 100
        note = f"  ⚠️ {fail_pct:.0f}% tiles failed" if fail_pct > 20 else ""
        print(f"   {city}: {kind} = {len(out[kind])} POIs{note}")

    # only cache if we got SOME data — otherwise retry next run
    if any(len(v) for v in out.values()):
        CACHE[key] = out
        _save_cache(CACHE)
    else:
        print(f"   ⚠️ {city}: Overpass returned 0 everywhere — not cached, rerun to retry")
    return out

# ---------------- URL SCRAPER ----------------
def _json_ld(driver):
    out=[]
    try:
        for s in driver.find_elements(By.CSS_SELECTOR,'script[type="application/ld+json"]'):
            try: out.append(json.loads(s.get_attribute("textContent")))
            except Exception: pass
    except Exception: pass
    return out

def _rating_from_ld(ld):
    for obj in ld:
        if not isinstance(obj, dict): continue
        agg=obj.get("aggregateRating")
        if isinstance(agg, dict):
            rv=agg.get("ratingValue")
            if rv is not None:
                try:
                    v=float(rv)
                    if v >= 1.0:       # 0.0 means "no reviews" — ignore
                        return v
                except Exception: pass
    return None

def make_driver():
    """Pass only kwargs this seleniumbase version accepts."""
    sig = inspect.signature(Driver.__init__).parameters
    candidates = {
        "browser":            "chrome",
        "headless":           HEADLESS,
        "page_load_strategy": "eager",   # ⭐ 4× faster than normal
        "block_images":       True,      # ⭐ correct kwarg (was disable_images)
        "ad_block_on":        True,
    }
    kwargs = {k:v for k,v in candidates.items() if k in sig}
    print(f"[driver] using kwargs: {list(kwargs)}")
    d = Driver(**kwargs)
    d.set_window_size(1600, 1000)
    d.set_page_load_timeout(PAGE_LOAD_TIMEOUT)
    return d

def fetch_rating(driver, url):
    try:
        driver.get(url)
    except TimeoutException:
        try: driver.execute_script("window.stop();")
        except Exception: pass
    except WebDriverException:
        return None
    try:
        WebDriverWait(driver, URL_WAIT_JSONLD).until(
            EC.presence_of_element_located((By.CSS_SELECTOR,'script[type="application/ld+json"]'))
        )
    except TimeoutException:
        pass
    return _rating_from_ld(_json_ld(driver))

# ---------------- MAIN ----------------
def main():
    df = pd.read_csv(INPUT_CSV, encoding="utf-8-sig")
    for c in TARGET_COLS:
        if c not in df.columns: df[c]=None
    total=len(df)
    print(f"Total rows: {total}\n")

    # --- 1. biz ---
    print("[1/5] biz (host has >1 listing)…")
    hc = df["HostName"].fillna("__unknown__").value_counts()
    df["biz"] = df["HostName"].map(hc).fillna(1).astype("Int64").clip(upper=1)
    df.loc[df["HostName"].isna(),"biz"]=pd.NA
    print(f"  biz=1: {int((df['biz']==1).sum())}   biz=0: {int((df['biz']==0).sum())}")

    # --- 2. dist ---
    print("\n[2/5] dist (km to city centre)…")
    for i,row in df.iterrows():
        lat,lng=row.get("Latitude"),row.get("Longitude")
        if pd.isna(lat) or pd.isna(lng): continue
        city=str(row.get("city","")).strip()
        centre=CITY_CENTRES.get(city)
        if centre is None:
            sub=df[df["city"]==city][["Latitude","Longitude"]].dropna()
            if len(sub): centre=(sub["Latitude"].median(),sub["Longitude"].median())
        if centre is None: continue
        df.at[i,"dist"]=round(haversine_km(lat,lng,*centre),3)
    print(f"  filled: {int(df['dist'].notna().sum())}/{total}")

    # --- 3. POIs per city ---
    print("\n[3/5] Fetching POIs per city…")
    city_pois={}
    for city in df["city"].dropna().unique():
        city_pois[city]=fetch_city_pois(city, df[df["city"]==city])

    # --- 4. per-row: rating + geo ---
    print("\n[4/5] Per-row: rating + geo features…")
    need_url = not USE_CSV_RATING
    driver = make_driver() if need_url else None
    fail_streak = 0
    url_disabled = False

    try:
        for n,i in enumerate(df.index,1):
            lat=df.at[i,"Latitude"]; lng=df.at[i,"Longitude"]
            city=df.at[i,"city"]

            # (a) rating
            if (not url_disabled) and pd.isna(df.at[i,"guest_satisfaction_overall"]):
                url=df.at[i,"URL"]; rating=None
                if isinstance(url,str) and "airbnb" in url and driver:
                    rating=fetch_rating(driver,url)
                    time.sleep(random.uniform(*SLEEP_BETWEEN))

                if rating is None:
                    fail_streak+=1
                    if fail_streak>=FAILSTREAK_LIMIT and not url_disabled:
                        print(f"⚠️  {FAILSTREAK_LIMIT} URL failures in a row — "
                              f"switching to CSV Rating×20 for remaining rows.")
                        url_disabled=True
                else:
                    fail_streak=0
                    df.at[i,"guest_satisfaction_overall"]=round(rating*20,2)

                # fallback to CSV Rating
                if rating is None and "Rating" in df.columns and pd.notna(df.at[i,"Rating"]):
                    df.at[i,"guest_satisfaction_overall"]=round(float(df.at[i,"Rating"])*20,2)

            # (b) geo
            pois=city_pois.get(city) or {"attr":[],"rest":[],"metro":[]}
            if pd.notna(lat) and pd.notna(lng):
                if pois["metro"]:
                    d=haversine_vec(lat,lng,[p[0] for p in pois["metro"]],
                                         [p[1] for p in pois["metro"]])
                    df.at[i,"metro_dist"]=round(float(d.min()),3)
                else:
                    df.at[i,"metro_dist"]=np.nan

                if pois["attr"]:
                    d=haversine_vec(lat,lng,[p[0] for p in pois["attr"]],
                                         [p[1] for p in pois["attr"]])
                    df.at[i,"attr_index"]=int((d<=POI_RADIUS_KM).sum())
                else:
                    df.at[i,"attr_index"]=0

                if pois["rest"]:
                    d=haversine_vec(lat,lng,[p[0] for p in pois["rest"]],
                                         [p[1] for p in pois["rest"]])
                    df.at[i,"rest_index"]=int((d<=POI_RADIUS_KM).sum())
                else:
                    df.at[i,"rest_index"]=0

            if n%25==0 or n==total:
                print(f"[{n}/{total}] row {i:>3} | "
                      f"rating={df.at[i,'guest_satisfaction_overall']} | "
                      f"dist={df.at[i,'dist']} | metro={df.at[i,'metro_dist']} | "
                      f"attr={df.at[i,'attr_index']} | rest={df.at[i,'rest_index']}")

            if n%CHECKPOINT_EVERY==0:
                df.to_csv(OUTPUT_CSV,index=False,encoding="utf-8-sig")
                _save_cache(CACHE)
    finally:
        if driver:
            try: driver.quit()
            except Exception: pass
        _save_cache(CACHE)

    # --- 5. normalise ---
    print("\n[5/5] Normalising…")
    df["attr_index_norm"]=minmax(df["attr_index"]).round(2)
    df["rest_index_norm"]=minmax(df["rest_index"]).round(2)
    df.to_csv(OUTPUT_CSV,index=False,encoding="utf-8-sig")

    print(f"\nDONE → {OUTPUT_CSV}")
    for c in TARGET_COLS:
        print(f"  {c:<28} filled: {int(df[c].notna().sum())}/{total}")


if __name__=="__main__":
    main()

Total rows: 500

[1/5] biz (host has >1 listing)…
  biz=1: 499   biz=0: 0

[2/5] dist (km to city centre)…
  filled: 499/500

[3/5] Fetching POIs per city…
   Amsterdam: 23 tiles (filtered to listings)
   Amsterdam: attr = 0 POIs  ⚠️ 100% tiles failed
   Amsterdam: rest = 0 POIs  ⚠️ 100% tiles failed
   Amsterdam: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Amsterdam: Overpass returned 0 everywhere — not cached, rerun to retry
   Athens: 4 tiles (filtered to listings)
   Athens: attr = 0 POIs  ⚠️ 100% tiles failed
   Athens: rest = 0 POIs  ⚠️ 100% tiles failed
   Athens: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Athens: Overpass returned 0 everywhere — not cached, rerun to retry
   Barcelona: 5 tiles (filtered to listings)
   Barcelona: attr = 0 POIs  ⚠️ 100% tiles failed
   Barcelona: rest = 0 POIs  ⚠️ 100% tiles failed
   Barcelona: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Barcelona: Overpass returned 0 everywhere — not cached, rerun to retry
   Berlin: 10 tiles (filtered to listings)
   Berlin: attr = 0 POIs  ⚠️ 100% tiles failed
   Berlin: rest = 0 POIs  ⚠️ 100% tiles failed
   Berlin: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Berlin: Overpass returned 0 everywhere — not cached, rerun to retry
   Budapest: 2 tiles (filtered to listings)
   Budapest: attr = 0 POIs  ⚠️ 100% tiles failed
   Budapest: rest = 0 POIs  ⚠️ 100% tiles failed
   Budapest: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Budapest: Overpass returned 0 everywhere — not cached, rerun to retry
   Lisbon: 3 tiles (filtered to listings)
   Lisbon: attr = 0 POIs  ⚠️ 100% tiles failed
   Lisbon: rest = 0 POIs  ⚠️ 100% tiles failed
   Lisbon: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Lisbon: Overpass returned 0 everywhere — not cached, rerun to retry
   London: 13 tiles (filtered to listings)
   London: attr = 0 POIs  ⚠️ 100% tiles failed
   London: rest = 0 POIs  ⚠️ 100% tiles failed
   London: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ London: Overpass returned 0 everywhere — not cached, rerun to retry
   Paris: 8 tiles (filtered to listings)
   Paris: attr = 0 POIs  ⚠️ 100% tiles failed
   Paris: rest = 0 POIs  ⚠️ 100% tiles failed
   Paris: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Paris: Overpass returned 0 everywhere — not cached, rerun to retry
   Rome: 3 tiles (filtered to listings)
   Rome: attr = 0 POIs  ⚠️ 100% tiles failed
   Rome: rest = 0 POIs  ⚠️ 100% tiles failed
   Rome: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Rome: Overpass returned 0 everywhere — not cached, rerun to retry
   Vienna: 6 tiles (filtered to listings)
   Vienna: attr = 0 POIs  ⚠️ 100% tiles failed
   Vienna: rest = 0 POIs  ⚠️ 100% tiles failed
   Vienna: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Vienna: Overpass returned 0 everywhere — not cached, rerun to retry

[4/5] Per-row: rating + geo features…
[driver] using kwargs: []

Warning: INFO: chromedriver not found. Getting it now:

*** Getting chromedriver 156.0.8078.47 (Latest Stable)

Downloading chromedriver-linux64.zip from:
https://storage.googleapis.com/chrome-for-testing-public/156.0.8078.47/linux64/chromedriver-linux64.zip ...
Download Complete!

Extracting ['chromedriver'] from chromedriver-linux64.zip:
Unzip Complete!

['chromedriver'] was saved to:
/usr/local/lib/python3.13/dist-packages/seleniumbase/drivers/
chromedriver

[chromedriver 156.0.8078.47] is ready for use!

[25/500] row  24 | rating=100.0 | dist=21.332 | metro=nan | attr=0 | rest=0
[50/500] row  49 | rating=99.6 | dist=1.705 | metro=nan | attr=0 | rest=0
[75/500] row  74 | rating=98.4 | dist=0.74 | metro=nan | attr=0 | rest=0
[100/500] row  99 | rating=100.0 | dist=7.757 | metro=nan | attr=0 | rest=0
[125/500] row 124 | rating=97.0 | dist=1.57 | metro=nan | attr=0 | rest=0
[150/500] row 149 | rating=94.4 | dist=1.004 | metro=nan | attr=0 | rest=0
[175/500] row 174 | rating=93.8 | dist=0.341 | metro=nan | attr=0 | rest=0
[200/500] row 199 | rating=99.0 | dist=3.853 | metro=nan | attr=0 | rest=0
[225/500] row 224 | rating=99.6 | dist=0.814 | metro=nan | attr=0 | rest=0
[250/500] row 249 | rating=100.0 | dist=1.448 | metro=nan | attr=0 | rest=0
[275/500] row 274 | rating=97.0 | dist=0.94 | metro=nan | attr=0 | rest=0
[300/500] row 299 | rating=98.2 | dist=0.478 | metro=nan | attr=0 | rest=0
[325/500] row 324 | rating=100.0 | dist=10.685 | metro=nan | attr=0 | rest=0
[350/500] row 349 | rating=100.0 | dist=7.051 | metro=nan | attr=0 | rest=0
[375/500] row 374 | rating=99.0 | dist=4.641 | metro=nan | attr=0 | rest=0
[400/500] row 399 | rating=98.8 | dist=5.756 | metro=nan | attr=0 | rest=0
[425/500] row 424 | rating=98.8 | dist=2.026 | metro=nan | attr=0 | rest=0
[450/500] row 449 | rating=98.2 | dist=1.302 | metro=nan | attr=0 | rest=0
[475/500] row 474 | rating=95.4 | dist=2.569 | metro=nan | attr=0 | rest=0
[500/500] row 499 | rating=100.0 | dist=2.274 | metro=nan | attr=0 | rest=0

[5/5] Normalising…

DONE → /content/drive/MyDrive/my.flutter.2025/Instant_ai_training/SPRINT_01/airbnb_listings_weekdays_priced_enriched.csv
  biz                          filled: 499/500
  guest_satisfaction_overall   filled: 500/500
  dist                         filled: 499/500
  metro_dist                   filled: 0/500
  attr_index                   filled: 499/500
  attr_index_norm              filled: 499/500
  rest_index                   filled: 499/500
  rest_index_norm              filled: 499/500

In [3]:
# =====================================================
#  ENRICH PRICED CSV (v3 — Overpass rate-limit-safe)
#  Adds:
#    biz, guest_satisfaction_overall, dist, metro_dist,
#    attr_index, attr_index_norm, rest_index, rest_index_norm
# =====================================================
import os, json, time, math, random, inspect

import numpy as np
import pandas as pd
import requests
from selenium.common.exceptions import TimeoutException, WebDriverException
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from seleniumbase import Driver

# ---------------- CONFIG ----------------
INPUT_CSV       = "/content/drive/MyDrive/my.flutter.2025/Instant_ai_training/SPRINT_01/airbnb_listings_weekends_priced.csv"
OUTPUT_CSV      = "/content/drive/MyDrive/my.flutter.2025/Instant_ai_training/SPRINT_01/airbnb_listings_weekends_priced_enriched.csv"
POI_CACHE       = "/content/drive/MyDrive/my.flutter.2025/Instant_ai_training/SPRINT_01/poi_cache_v3.json"

USE_CSV_RATING  = False          # True → skip URL, use Rating×20 (finishes in ~2 min)
FORCE_REFRESH   = True           # True → ignore POI cache (needed for first clean run)
HEADLESS        = True

SLEEP_BETWEEN      = (1.0, 2.5)
PAGE_LOAD_TIMEOUT  = 20
URL_WAIT_JSONLD    = 6
FAILSTREAK_LIMIT   = 10
CHECKPOINT_EVERY   = 25

OVERPASS_ENDPOINTS = [
    "https://overpass-api.de/api/interpreter",      # primary (largest quota)
    "https://overpass.kumi.systems/api/interpreter",
    "https://overpass.private.coffee/api/interpreter",
]
OVERPASS_SLEEP   = 1.0           # 1 s between requests (was 0.4 — too fast)
OVERPASS_RETRIES = 3             # per endpoint, exponential 2/4/8 s
POI_RADIUS_KM    = 1.5
TILE_DEG         = 0.06          # bigger tiles, fewer requests
CITY_BUFFER_DEG  = 0.02

CITY_CENTRES = {
    "Amsterdam": (52.3676, 4.9041),  "Athens":    (37.9838, 23.7275),
    "Barcelona": (41.3874, 2.1686),  "Berlin":    (52.5200, 13.4050),
    "Budapest":  (47.4979, 19.0402), "Lisbon":    (38.7223, -9.1393),
    "London":    (51.5074, -0.1278), "Paris":     (48.8566, 2.3522),
    "Rome":      (41.9028, 12.4964), "Vienna":    (48.2082, 16.3738),
}

TARGET_COLS = ["biz","guest_satisfaction_overall","dist","metro_dist",
               "attr_index","attr_index_norm",
               "rest_index","rest_index_norm"]

# ---------------- GEOMETRY ----------------
def haversine_km(lat1, lon1, lat2, lon2):
    R=6371.0
    p1,p2=math.radians(lat1),math.radians(lat2)
    dp=math.radians(lat2-lat1); dl=math.radians(lon2-lon1)
    a=math.sin(dp/2)**2+math.cos(p1)*math.cos(p2)*math.sin(dl/2)**2
    return 2*R*math.asin(math.sqrt(a))

def haversine_vec(lat1, lon1, lats, lons):
    if not len(lats): return np.array([])
    R=6371.0
    lat1r=math.radians(lat1); lon1r=math.radians(lon1)
    latr=np.radians(np.asarray(lats,float)); lonr=np.radians(np.asarray(lons,float))
    dlat=latr-lat1r; dlon=lonr-lon1r
    a=np.sin(dlat/2)**2+np.cos(lat1r)*np.cos(latr)*np.sin(dlon/2)**2
    return 2*R*np.arcsin(np.sqrt(a))

def minmax(s):
    s=pd.to_numeric(s,errors="coerce")
    lo,hi=s.min(),s.max()
    if pd.isna(lo) or hi==lo: return s*0
    return (s-lo)/(hi-lo)*100

# ---------------- OVERPASS ----------------
def _load_cache():
    if os.path.exists(POI_CACHE):
        try:
            with open(POI_CACHE) as f: return json.load(f)
        except Exception: return {}
    return {}

def _save_cache(c):
    try:
        with open(POI_CACHE,"w") as f: json.dump(c,f)
    except Exception: pass

CACHE = _load_cache()

def _overpass(query, timeout=30, retries=OVERPASS_RETRIES):
    """Rotate endpoints × exponential backoff. Returns dict or None."""
    last_err = None
    for url in OVERPASS_ENDPOINTS:
        for attempt in range(retries):
            try:
                r = requests.post(url, data={"data": query}, timeout=timeout)
                if r.status_code == 200:
                    return r.json()
                last_err = f"HTTP {r.status_code}"
                if r.status_code == 400:
                    return None   # malformed — retrying won't help
            except Exception as e:
                last_err = f"{type(e).__name__}"
            time.sleep(2 * (attempt + 1))    # 2, 4, 8 s
    return None

def _coords_from(data):
    if not data: return []
    out=[]
    for el in data.get("elements", []):
        la=el.get("lat") or (el.get("center") or {}).get("lat")
        lo=el.get("lon") or (el.get("center") or {}).get("lon")
        if la is not None and lo is not None:
            out.append([la,lo])
    return out

def _tiles_with_listings(pts, lat_min, lat_max, lng_min, lng_max):
    """Only tiles that actually contain ≥1 listing → 5–10× fewer requests."""
    tiles=[]
    la=lat_min
    while la < lat_max:
        lo=lng_min
        while lo < lng_max:
            la2=min(la+TILE_DEG, lat_max)
            lo2=min(lo+TILE_DEG, lng_max)
            if any(la <= p[0] < la2 and lo <= p[1] < lo2 for p in pts):
                tiles.append((la,lo,la2,lo2))
            lo += TILE_DEG
        la += TILE_DEG
    return tiles

def fetch_city_pois(city, sub):
    key=f"pois_v3::{city}"
    if not FORCE_REFRESH and key in CACHE:
        c=CACHE[key]
        print(f"   {city}: cached (attr={len(c['attr'])}, "
              f"rest={len(c['rest'])}, metro={len(c['metro'])})")
        return c

    pts = sub[["Latitude","Longitude"]].dropna().values.tolist()
    if not pts:
        return {"attr":[], "rest":[], "metro":[]}

    lats=[p[0] for p in pts]; lngs=[p[1] for p in pts]
    tiles = _tiles_with_listings(
        pts,
        min(lats)-CITY_BUFFER_DEG, max(lats)+CITY_BUFFER_DEG,
        min(lngs)-CITY_BUFFER_DEG, max(lngs)+CITY_BUFFER_DEG,
    )
    print(f"   {city}: {len(tiles)} tiles (filtered to listings)")

    specs = {
        # nwr = nodes + ways + relations → catches ways-mapped POIs too
        "attr":  '["tourism"~"attraction|museum|viewpoint|gallery"]',
        "rest":  '["amenity"~"restaurant|cafe|bar"]',
        "metro": '["railway"="station"]["station"="subway"]',
    }
    out = {k: [] for k in specs}
    errors = {k: 0 for k in specs}

    for kind, tags in specs.items():
        for (la1,lo1,la2,lo2) in tiles:
            q = f'[out:json][timeout:25];nwr{tags}({la1},{lo1},{la2},{lo2});out center;'
            data = _overpass(q, timeout=30)
            if data is None:
                errors[kind] += 1
            else:
                out[kind].extend(_coords_from(data))
            time.sleep(OVERPASS_SLEEP)
        # subway entrances separately (different tag)
        if kind == "metro":
            for (la1,lo1,la2,lo2) in tiles:
                q = (f'[out:json][timeout:20];'
                     f'nwr["railway"="subway_entrance"]({la1},{lo1},{la2},{lo2});out center;')
                data = _overpass(q, timeout=25)
                if data is None:
                    errors[kind] += 1
                else:
                    out[kind].extend(_coords_from(data))
                time.sleep(OVERPASS_SLEEP)

        fail_pct = errors[kind] / max(len(tiles), 1) * 100
        note = f"  ⚠️ {fail_pct:.0f}% tiles failed" if fail_pct > 20 else ""
        print(f"   {city}: {kind} = {len(out[kind])} POIs{note}")

    # only cache if we got SOME data — otherwise retry next run
    if any(len(v) for v in out.values()):
        CACHE[key] = out
        _save_cache(CACHE)
    else:
        print(f"   ⚠️ {city}: Overpass returned 0 everywhere — not cached, rerun to retry")
    return out

# ---------------- URL SCRAPER ----------------
def _json_ld(driver):
    out=[]
    try:
        for s in driver.find_elements(By.CSS_SELECTOR,'script[type="application/ld+json"]'):
            try: out.append(json.loads(s.get_attribute("textContent")))
            except Exception: pass
    except Exception: pass
    return out

def _rating_from_ld(ld):
    for obj in ld:
        if not isinstance(obj, dict): continue
        agg=obj.get("aggregateRating")
        if isinstance(agg, dict):
            rv=agg.get("ratingValue")
            if rv is not None:
                try:
                    v=float(rv)
                    if v >= 1.0:       # 0.0 means "no reviews" — ignore
                        return v
                except Exception: pass
    return None

def make_driver():
    """Pass only kwargs this seleniumbase version accepts."""
    sig = inspect.signature(Driver.__init__).parameters
    candidates = {
        "browser":            "chrome",
        "headless":           HEADLESS,
        "page_load_strategy": "eager",   # ⭐ 4× faster than normal
        "block_images":       True,      # ⭐ correct kwarg (was disable_images)
        "ad_block_on":        True,
    }
    kwargs = {k:v for k,v in candidates.items() if k in sig}
    print(f"[driver] using kwargs: {list(kwargs)}")
    d = Driver(**kwargs)
    d.set_window_size(1600, 1000)
    d.set_page_load_timeout(PAGE_LOAD_TIMEOUT)
    return d

def fetch_rating(driver, url):
    try:
        driver.get(url)
    except TimeoutException:
        try: driver.execute_script("window.stop();")
        except Exception: pass
    except WebDriverException:
        return None
    try:
        WebDriverWait(driver, URL_WAIT_JSONLD).until(
            EC.presence_of_element_located((By.CSS_SELECTOR,'script[type="application/ld+json"]'))
        )
    except TimeoutException:
        pass
    return _rating_from_ld(_json_ld(driver))

# ---------------- MAIN ----------------
def main():
    df = pd.read_csv(INPUT_CSV, encoding="utf-8-sig")
    for c in TARGET_COLS:
        if c not in df.columns: df[c]=None
    total=len(df)
    print(f"Total rows: {total}\n")

    # --- 1. biz ---
    print("[1/5] biz (host has >1 listing)…")
    hc = df["HostName"].fillna("__unknown__").value_counts()
    df["biz"] = df["HostName"].map(hc).fillna(1).astype("Int64").clip(upper=1)
    df.loc[df["HostName"].isna(),"biz"]=pd.NA
    print(f"  biz=1: {int((df['biz']==1).sum())}   biz=0: {int((df['biz']==0).sum())}")

    # --- 2. dist ---
    print("\n[2/5] dist (km to city centre)…")
    for i,row in df.iterrows():
        lat,lng=row.get("Latitude"),row.get("Longitude")
        if pd.isna(lat) or pd.isna(lng): continue
        city=str(row.get("city","")).strip()
        centre=CITY_CENTRES.get(city)
        if centre is None:
            sub=df[df["city"]==city][["Latitude","Longitude"]].dropna()
            if len(sub): centre=(sub["Latitude"].median(),sub["Longitude"].median())
        if centre is None: continue
        df.at[i,"dist"]=round(haversine_km(lat,lng,*centre),3)
    print(f"  filled: {int(df['dist'].notna().sum())}/{total}")

    # --- 3. POIs per city ---
    print("\n[3/5] Fetching POIs per city…")
    city_pois={}
    for city in df["city"].dropna().unique():
        city_pois[city]=fetch_city_pois(city, df[df["city"]==city])

    # --- 4. per-row: rating + geo ---
    print("\n[4/5] Per-row: rating + geo features…")
    need_url = not USE_CSV_RATING
    driver = make_driver() if need_url else None
    fail_streak = 0
    url_disabled = False

    try:
        for n,i in enumerate(df.index,1):
            lat=df.at[i,"Latitude"]; lng=df.at[i,"Longitude"]
            city=df.at[i,"city"]

            # (a) rating
            if (not url_disabled) and pd.isna(df.at[i,"guest_satisfaction_overall"]):
                url=df.at[i,"URL"]; rating=None
                if isinstance(url,str) and "airbnb" in url and driver:
                    rating=fetch_rating(driver,url)
                    time.sleep(random.uniform(*SLEEP_BETWEEN))

                if rating is None:
                    fail_streak+=1
                    if fail_streak>=FAILSTREAK_LIMIT and not url_disabled:
                        print(f"⚠️  {FAILSTREAK_LIMIT} URL failures in a row — "
                              f"switching to CSV Rating×20 for remaining rows.")
                        url_disabled=True
                else:
                    fail_streak=0
                    df.at[i,"guest_satisfaction_overall"]=round(rating*20,2)

                # fallback to CSV Rating
                if rating is None and "Rating" in df.columns and pd.notna(df.at[i,"Rating"]):
                    df.at[i,"guest_satisfaction_overall"]=round(float(df.at[i,"Rating"])*20,2)

            # (b) geo
            pois=city_pois.get(city) or {"attr":[],"rest":[],"metro":[]}
            if pd.notna(lat) and pd.notna(lng):
                if pois["metro"]:
                    d=haversine_vec(lat,lng,[p[0] for p in pois["metro"]],
                                         [p[1] for p in pois["metro"]])
                    df.at[i,"metro_dist"]=round(float(d.min()),3)
                else:
                    df.at[i,"metro_dist"]=np.nan

                if pois["attr"]:
                    d=haversine_vec(lat,lng,[p[0] for p in pois["attr"]],
                                         [p[1] for p in pois["attr"]])
                    df.at[i,"attr_index"]=int((d<=POI_RADIUS_KM).sum())
                else:
                    df.at[i,"attr_index"]=0

                if pois["rest"]:
                    d=haversine_vec(lat,lng,[p[0] for p in pois["rest"]],
                                         [p[1] for p in pois["rest"]])
                    df.at[i,"rest_index"]=int((d<=POI_RADIUS_KM).sum())
                else:
                    df.at[i,"rest_index"]=0

            if n%25==0 or n==total:
                print(f"[{n}/{total}] row {i:>3} | "
                      f"rating={df.at[i,'guest_satisfaction_overall']} | "
                      f"dist={df.at[i,'dist']} | metro={df.at[i,'metro_dist']} | "
                      f"attr={df.at[i,'attr_index']} | rest={df.at[i,'rest_index']}")

            if n%CHECKPOINT_EVERY==0:
                df.to_csv(OUTPUT_CSV,index=False,encoding="utf-8-sig")
                _save_cache(CACHE)
    finally:
        if driver:
            try: driver.quit()
            except Exception: pass
        _save_cache(CACHE)

    # --- 5. normalise ---
    print("\n[5/5] Normalising…")
    df["attr_index_norm"]=minmax(df["attr_index"]).round(2)
    df["rest_index_norm"]=minmax(df["rest_index"]).round(2)
    df.to_csv(OUTPUT_CSV,index=False,encoding="utf-8-sig")

    print(f"\nDONE → {OUTPUT_CSV}")
    for c in TARGET_COLS:
        print(f"  {c:<28} filled: {int(df[c].notna().sum())}/{total}")


if __name__=="__main__":
    main()

Total rows: 500

[1/5] biz (host has >1 listing)…
  biz=1: 499   biz=0: 0

[2/5] dist (km to city centre)…
  filled: 499/500

[3/5] Fetching POIs per city…
   Amsterdam: 12 tiles (filtered to listings)
   Amsterdam: attr = 0 POIs  ⚠️ 100% tiles failed
   Amsterdam: rest = 0 POIs  ⚠️ 100% tiles failed
   Amsterdam: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Amsterdam: Overpass returned 0 everywhere — not cached, rerun to retry
   Athens: 1 tiles (filtered to listings)
   Athens: attr = 0 POIs  ⚠️ 100% tiles failed
   Athens: rest = 0 POIs  ⚠️ 100% tiles failed
   Athens: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Athens: Overpass returned 0 everywhere — not cached, rerun to retry
   Barcelona: 3 tiles (filtered to listings)
   Barcelona: attr = 0 POIs  ⚠️ 100% tiles failed
   Barcelona: rest = 0 POIs  ⚠️ 100% tiles failed
   Barcelona: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Barcelona: Overpass returned 0 everywhere — not cached, rerun to retry
   Berlin: 10 tiles (filtered to listings)
   Berlin: attr = 0 POIs  ⚠️ 100% tiles failed
   Berlin: rest = 0 POIs  ⚠️ 100% tiles failed
   Berlin: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Berlin: Overpass returned 0 everywhere — not cached, rerun to retry
   Budapest: 2 tiles (filtered to listings)
   Budapest: attr = 0 POIs  ⚠️ 100% tiles failed
   Budapest: rest = 0 POIs  ⚠️ 100% tiles failed
   Budapest: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Budapest: Overpass returned 0 everywhere — not cached, rerun to retry
   Lisbon: 1 tiles (filtered to listings)
   Lisbon: attr = 0 POIs  ⚠️ 100% tiles failed
   Lisbon: rest = 0 POIs  ⚠️ 100% tiles failed
   Lisbon: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Lisbon: Overpass returned 0 everywhere — not cached, rerun to retry
   London: 8 tiles (filtered to listings)
   London: attr = 0 POIs  ⚠️ 100% tiles failed
   London: rest = 0 POIs  ⚠️ 100% tiles failed
   London: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ London: Overpass returned 0 everywhere — not cached, rerun to retry
   Paris: 7 tiles (filtered to listings)
   Paris: attr = 0 POIs  ⚠️ 100% tiles failed
   Paris: rest = 0 POIs  ⚠️ 100% tiles failed
   Paris: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Paris: Overpass returned 0 everywhere — not cached, rerun to retry
   Rome: 3 tiles (filtered to listings)
   Rome: attr = 0 POIs  ⚠️ 100% tiles failed
   Rome: rest = 0 POIs  ⚠️ 100% tiles failed
   Rome: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Rome: Overpass returned 0 everywhere — not cached, rerun to retry
   Vienna: 5 tiles (filtered to listings)
   Vienna: attr = 0 POIs  ⚠️ 100% tiles failed
   Vienna: rest = 0 POIs  ⚠️ 100% tiles failed
   Vienna: metro = 0 POIs  ⚠️ 200% tiles failed
   ⚠️ Vienna: Overpass returned 0 everywhere — not cached, rerun to retry

[4/5] Per-row: rating + geo features…
[driver] using kwargs: []
[25/500] row  24 | rating=100.0 | dist=1.437 | metro=nan | attr=0 | rest=0
[50/500] row  49 | rating=97.8 | dist=2.041 | metro=nan | attr=0 | rest=0
[75/500] row  74 | rating=97.2 | dist=2.449 | metro=nan | attr=0 | rest=0
[100/500] row  99 | rating=98.6 | dist=0.712 | metro=nan | attr=0 | rest=0
[125/500] row 124 | rating=95.2 | dist=0.749 | metro=nan | attr=0 | rest=0
[150/500] row 149 | rating=97.2 | dist=1.488 | metro=nan | attr=0 | rest=0
[175/500] row 174 | rating=95.8 | dist=1.063 | metro=nan | attr=0 | rest=0
[200/500] row 199 | rating=98.0 | dist=2.757 | metro=nan | attr=0 | rest=0
[225/500] row 224 | rating=95.4 | dist=2.096 | metro=nan | attr=0 | rest=0
[250/500] row 249 | rating=99.0 | dist=1.504 | metro=nan | attr=0 | rest=0
[275/500] row 274 | rating=95.2 | dist=0.851 | metro=nan | attr=0 | rest=0
[300/500] row 299 | rating=98.0 | dist=1.205 | metro=nan | attr=0 | rest=0
[325/500] row 324 | rating=100.0 | dist=3.371 | metro=nan | attr=0 | rest=0
[350/500] row 349 | rating=100.0 | dist=4.798 | metro=nan | attr=0 | rest=0
[375/500] row 374 | rating=99.4 | dist=0.775 | metro=nan | attr=0 | rest=0
[400/500] row 399 | rating=94.2 | dist=1.214 | metro=nan | attr=0 | rest=0
[425/500] row 424 | rating=95.4 | dist=2.54 | metro=nan | attr=0 | rest=0
[450/500] row 449 | rating=98.0 | dist=0.342 | metro=nan | attr=0 | rest=0
[475/500] row 474 | rating=96.0 | dist=3.77 | metro=nan | attr=0 | rest=0
[500/500] row 499 | rating=96.6 | dist=3.468 | metro=nan | attr=0 | rest=0

[5/5] Normalising…

DONE → /content/drive/MyDrive/my.flutter.2025/Instant_ai_training/SPRINT_01/airbnb_listings_weekends_priced_enriched.csv
  biz                          filled: 499/500
  guest_satisfaction_overall   filled: 500/500
  dist                         filled: 499/500
  metro_dist                   filled: 0/500
  attr_index                   filled: 499/500
  attr_index_norm              filled: 499/500
  rest_index                   filled: 499/500
  rest_index_norm              filled: 499/500